### ISSUE TITLE
[Native Ad]Loading Multiple Admob Native ads in Listview

### ISSUE THREAD

**Issue by ldobreira** [googleads/googleads-mobile-flutter#568] opened 2022-05-21 05:27 UTC
## Use case
For some reason, before installing the googleads package I was expecting to be able to easily load multiple Native ads in a Listview since that's the standard for most Apps... (for example show 1 ad every 6 cards) However for my surprise that's not really the case. Documentation and examples clearly show how to put 1 ad... and that's it...

## Proposal

Sure maybe there are some advanced solutions that solve this issue (still trying to figure out what solutions... there is no clear info about it) or even some StackOverflow "hacks"... but those can easily create other serious issues, including getting those ads banned for improper usage.  Would be great to load multiple ads in a listview out of the box since that's a really common scenario for a production-ready App...

And maybe the option to easily load for example 3 ads with one request to avoid lagging in the listview...

Meanwhile, what is the proper way to do it?

**Comment by maheshmnj** [comment] 2022-05-23 13:26
Hi @ldobreira, Thanks for filing the issue.  I can reproduce the issue when trying to load multiple native ads I get ad already loaded error

<img src="https://user-images.githubusercontent.com/31410839/169829478-6943a99b-b6d6-4e70-b000-d3d8c29cc7e3.png" width ="300"> 

<details>
<summary>logs</summary>

```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Upgrading AppFrameworkInfo.plist
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Warning: CocoaPods recommended version 1.11.0 or greater not installed.
Pods handling may fail on some projects involving plugins.
To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
Xcode build done.                                           27.9s
Connecting to VM Service at ws://127.0.0.1:51945/GVO_jV8vLPs=/ws
Reloaded 1 of 596 libraries in 231ms.
<Google> To get test ads on this device, set: GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ kGADSimulatorID ];
<Google> <Google:HTML> A valid SKAdNetworkIdentifier for Google (cstr6suwn9.skadnetwork) is missing from Info.plist. See [Enable SKAdNetwork to track conversions] (https://googlemobileadssdk.page.link/enable-skadnetwork)

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building AdWidget(dirty, state: _AdWidgetState#a5cca):
This AdWidget is already in the Widget tree

If you placed this AdWidget in a list, make sure you create a new instance in the builder function with a unique ad object.
Make sure you are not using the same ad object in more than one AdWidget.

The relevant error-causing widget was
AdWidget
When the exception was thrown, this was the stack
#0      _AdWidgetState.build
#1      StatefulElement.build
#2      ComponentElement.performRebuild
#3      StatefulElement.performRebuild
#4      Element.rebuild
#5      ComponentElement._firstBuild
#6      StatefulElement._firstBuild
#7      ComponentElement.mount
...     Normal element mounting (13 frames)
#20     Element.inflateWidget
#21     Element.updateChild
#22     SingleChildRenderObjectElement.update
#23     Element.updateChild
#24     SingleChildRenderObjectElement.update
#25     Element.updateChild
#26     ComponentElement.performRebuild
#27     Element.rebuild
#28     ProxyElement.update
#29     Element.updateChild
#30     ComponentElement.performRebuild
#31     Element.rebuild
#32     ProxyElement.update
#33     Element.updateChild
#34     ComponentElement.performRebuild
#35     StatefulElement.performRebuild
#36     Element.rebuild
#37     StatefulElement.update
#38     Element.updateChild
#39     ComponentElement.performRebuild
#40     Element.rebuild
#41     StatelessElement.update
#42     Element.updateChild
#43     SliverMultiBoxAdaptorElement.updateChild
#44     SliverMultiBoxAdaptorElement.performRebuild.processElement
#45     Iterable.forEach (dart:core/iterable.dart:325:35)
#46     SliverMultiBoxAdaptorElement.performRebuild
#47     SliverMultiBoxAdaptorElement.update
#48     Element.updateChild
#49     ComponentElement.performRebuild
#50     Element.rebuild
#51     ProxyElement.update
#52     Element.updateChild
#53     SingleChildRenderObjectElement.update
#54     Element.updateChild
#55     RenderObjectElement.updateChildren
#56     MultiChildRenderObjectElement.update
#57     _ViewportElement.update
#58     Element.updateChild
#59     SingleChildRenderObjectElement.update
#60     Element.updateChild
#61     SingleChildRenderObjectElement.update
#62     Element.updateChild
#63     SingleChildRenderObjectElement.update
#64     Element.updateChild
#65     SingleChildRenderObjectElement.update
#66     Element.updateChild
#67     ComponentElement.performRebuild
#68     StatefulElement.performRebuild
#69     Element.rebuild
#70     StatefulElement.update
#71     Element.updateChild
#72     SingleChildRenderObjectElement.update
#73     Element.updateChild
#74     ComponentElement.performRebuild
#75     Element.rebuild
#76     ProxyElement.update
#77     Element.updateChild
#78     SingleChildRenderObjectElement.update
#79     Element.updateChild
#80     ComponentElement.performRebuild
#81     Element.rebuild
#82     ProxyElement.update
#83     Element.updateChild
#84     ComponentElement.performRebuild
#85     StatefulElement.performRebuild
#86     Element.rebuild
#87     StatefulElement.update
#88     Element.updateChild
#89     ComponentElement.performRebuild
#90     Element.rebuild
#91     ProxyElement.update
#92     Element.updateChild
#93     ComponentElement.performRebuild
#94     Element.rebuild
#95     StatelessElement.update
#96     Element.updateChild
#97     ComponentElement.performRebuild
#98     Element.rebuild
#99     StatelessElement.update
#100    Element.updateChild
#101    ComponentElement.performRebuild
#102    Element.rebuild
#103    ProxyElement.update
#104    Element.updateChild
#105    ComponentElement.performRebuild
#106    Element.rebuild
#107    ProxyElement.update
#108    Element.updateChild
#109    RenderObjectElement.updateChildren
#110    MultiChildRenderObjectElement.update
#111    Element.updateChild
#112    ComponentElement.performRebuild
#113    StatefulElement.performRebuild
#114    Element.rebuild
#115    StatefulElement.update
#116    Element.updateChild
#117    ComponentElement.performRebuild
#118    Element.rebuild
#119    ProxyElement.update
#120    Element.updateChild
#121    ComponentElement.performRebuild
#122    StatefulElement.performRebuild
#123    Element.rebuild
#124    StatefulElement.update
#125    Element.updateChild
#126    SingleChildRenderObjectElement.update
#127    Element.updateChild
#128    ComponentElement.performRebuild
#129    Element.rebuild
#130    ProxyElement.update
#131    Element.updateChild
#132    SingleChildRenderObjectElement.update
#133    Element.updateChild
#134    ComponentElement.performRebuild
#135    StatefulElement.performRebuild
#136    Element.rebuild
#137    StatefulElement.update
#138    Element.updateChild
#139    ComponentElement.performRebuild
#140    StatefulElement.performRebuild
#141    Element.rebuild
#142    StatefulElement.update
#143    Element.updateChild
#144    ComponentElement.performRebuild
#145    Element.rebuild
#146    ProxyElement.update
#147    Element.updateChild
#148    ComponentElement.performRebuild
#149    Element.rebuild
#150    ProxyElement.update
#151    Element.updateChild
#152    ComponentElement.performRebuild
#153    StatefulElement.performRebuild
#154    Element.rebuild
#155    StatefulElement.update
#156    Element.updateChild
#157    ComponentElement.performRebuild
#158    Element.rebuild
#159    ProxyElement.update
#160    Element.updateChild
#161    ComponentElement.performRebuild
#162    StatefulElement.performRebuild
#163    Element.rebuild
#164    StatefulElement.update
#165    Element.updateChild
#166    ComponentElement.performRebuild
#167    StatefulElement.performRebuild
#168    Element.rebuild
#169    BuildOwner.buildScope
#170    WidgetsBinding.drawFrame
#171    RendererBinding._handlePersistentFrameCallback
#172    SchedulerBinding._invokeFrameCallback
#173    SchedulerBinding.handleDrawFrame
#174    SchedulerBinding._handleDrawFrame
#178    _invoke (dart:ui/hooks.dart:151:10)
#179    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#180    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
This AdWidget is already in the Widget tree
The relevant error-causing widget was
AdWidget
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
This AdWidget is already in the Widget tree
The relevant error-causing widget was
AdWidget
════════════════════════════════════════════════════════════════════════════════

```
</details> 

<details>
<summary>code sample</summary>

```dart
import 'package:admob_inline_ads_in_flutter/ad_helper.dart';
import 'package:admob_inline_ads_in_flutter/destination.dart';
import 'package:admob_inline_ads_in_flutter/banner_inline_page.dart';
import 'package:admob_inline_ads_in_flutter/home_page.dart';
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      routes: <String, WidgetBuilder>{
        '/banner': (context) =>
            BannerInlinePage(entries: Destination.samples),
        '/native': (context) =>
            NativeInlinePage(entries: Destination.samples),
      },
      home: HomePage(),
    );
  }
}


class NativeInlinePage extends StatefulWidget {
  final List<Destination> entries;

  NativeInlinePage({
    required this.entries,
  });

  @override
  State createState() => _NativeInlinePageState();
}

class _NativeInlinePageState extends State<NativeInlinePage> {
  // COMPLETE: Add _kAdIndex
  static final _kAdIndex = 4;

  // COMPLETE: Add NativeAd instance
  late NativeAd _ad;

  // COMPLETE: Add _isAdLoaded
  bool _isAdLoaded = false;

  @override
  void initState() {
    super.initState();

    // COMPLETE: Create a NativeAd instance
    _ad = NativeAd(
      adUnitId: AdManager.nativeAdUnitId,
      factoryId: 'listTile',
      request: AdRequest(),
      listener: NativeAdListener(
        onAdLoaded: (_) {
          setState(() {
            _isAdLoaded = true;
          });
        },
        onAdFailedToLoad: (ad, error) {
          // Releases an ad resource when it fails to load
          ad.dispose();

          print('Ad load failed (code=${error.code} message=${error.message})');
        },
      ),
    );

    // COMPLETE: Load an ad
    _ad.load();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('AdMob Native Inline Ad'),
      ),
      body: ListView.builder(
        // COMPLETE: Adjust itemCount based on the ad load state
        itemCount: widget.entries.length + (_isAdLoaded ? 1 : 0),
        itemBuilder: (context, index) {
          // COMPLETE: Render a native ad
          if (_isAdLoaded && (index % _kAdIndex == 0)) {
            return Container(
              child: AdWidget(ad: _ad),
              height: 72.0,
              alignment: Alignment.center,
            );
          } else {
            // COMPLETE: Get adjusted item index from _getDestinationItemIndex()
            final item = widget.entries[_getDestinationItemIndex(index)];

            return ListTile(
              leading: Image.asset(
                item.asset,
                width: 48,
                height: 48,
                package: 'flutter_gallery_assets',
                fit: BoxFit.cover,
              ),
              title: Text(item.name),
              subtitle: Text(item.duration),
              onTap: () {
                print('Clicked ${item.name}');
              },
            );
          }
        },
      ),
    );
  }

  @override
  void dispose() {
    // COMPLETE: Dispose a NativeAd object
    _ad.dispose();
    super.dispose();
  }

  // COMPLETE: Add _getDestinationItemIndex()
  int _getDestinationItemIndex(int rawIndex) {
    if (rawIndex >= _kAdIndex && _isAdLoaded) {
      return rawIndex - 1;
    }
    return rawIndex;
  }
}

```
 </details> 

cc: @jjliu15

**Comment by ldobreira** [comment] 2022-05-23 14:18
Thank you @maheshmnj. For some reason, I keep getting the exact same error even if put the widget inside a stateful widget. Can you please show a small example?

The error is also saying that we have to assign a new ID, but how that can be done dynamically? Are not those IDs already pre-selected on Admob?!

**Comment by maheshmnj** [comment] 2022-05-25 13:38
@ldobreira I think you will needs `List<NativeAd>` to deal with this issue (as a workaround), Let me try and get back with a code sample

**Comment by ldobreira** [comment] 2022-05-25 17:07
Thank you so much @maheshmnj

**Comment by ldobreira** [comment] 2022-05-31 16:28
Exactly @maheshmnj that's the exact same issues I'm having... That's why I asked for an example...

**Comment by 04pd** [comment] 2022-06-20 05:06
Widget getBanerAd(double height){
   
      AdManagerBannerAd myBanner;
      final Completer<BannerAd> banerAdCompleter =
      Completer<BannerAd>();
      myBanner = AdManagerBannerAd(
        adUnitId:  model.bannerId!,
        sizes:   [AdSize(width: 300,height: height.toInt())],
        request: AdManagerAdRequest(),
        listener: AdManagerBannerAdListener(
            onAdLoaded: (ad){
              banerAdCompleter.complete(ad as BannerAd);
              //print("Banner Loaded from provider");
            },
            onAdFailedToLoad: (ad,error){
              print(error);
              banerAdCompleter.completeError("");
            }
        ),
      );
      myBanner.load();
      return Container(
        child: FutureBuilder<BannerAd>(
            future: banerAdCompleter.future,
            builder: (BuildContext context,
                AsyncSnapshot<BannerAd> snapshot) {
              Widget child;
              switch (snapshot.connectionState) {
                case ConnectionState.none:
                case ConnectionState.waiting:
                case ConnectionState.active:
                  child = Container(
                    color: Colors.blue.withOpacity(0.5),
                    child: Center(child: Image.asset("assets/advertise.png",height: 50,color: Colors.white,)),
                  );
                  break;
                case ConnectionState.done:
                  if (snapshot.hasData) {
                    child =  AdWidget(ad: myBanner);
                  } else {
                    child = const Center(child: Text('Error loading ad'));
                  }
              }
              //print("Error occured while displayig baner ad");
              return Container(
                child: child,
                height: height,
                color: const Color(0xfffffff),
              );
            }),
      );
  }


For work around this may help
But it freeze the scrolling of list or gride view need more fix

**Comment by maheshmnj** [comment] 2022-07-04 06:49
cc: @jjliu15

**Comment by timothyhoang-google** [comment] 2022-09-22 22:05
From a best practices standpoint, you should pick an upper limit on ads within the feed and provide a distinct ad unit ID for every ad placement in the ListView. To do this, you can simply create the ad units on your AdMob or Ad Manager account. This allows you to segment performance in reporting based on the placement location. For example, if you plan to interleave 5 ad placements in a feed, you should generate 5 ad units which will each have 5 distinct ad unit IDs.

If you want to re-use the same ad unit ID, you can destroy the ad view corresponding the that ad unit ID, load a new ad, then attach it again to the view. This is more relevant if you don't want to pick an upper limit on ads. We don't recommend doing this because user ad engagement and ad viewability will probably decrease lower in the feed, which will impact your CPMs. You also you won't be able to segment performance by placement location.

**Comment by ldobreira** [comment] 2022-09-22 23:34
> From a best practices standpoint, you should pick an upper limit on ads within the feed and provide a distinct ad unit ID for every ad placement in the ListView. To do this, you can simply create the ad units on your AdMob or Ad Manager account. This allows you to segment performance in reporting based on the placement location. For example, if you plan to interleave 5 ad placements in a feed, you should generate 5 ad units which will each have 5 distinct ad unit IDs.
> 
> If you want to re-use the same ad unit ID, you can destroy the ad view corresponding the that ad unit ID, load a new ad, then attach it again to the view. This is more relevant if you don't want to pick an upper limit on ads. We don't recommend doing this because user ad engagement and ad viewability will probably decrease lower in the feed, which will impact your CPMs. You also won't be able to segment performance by placement location.

I definitely understand what you saying, and I agree, however, I was not able to find any examples of a listview using multiple Admob ads while scrolling down (something like for example Facebook)... All examples and tutorials only use 1 or 2 ads.

**Comment by timothyhoang-google** [comment] 2022-09-27 17:01
I agree the Flutter samples do need updating to match the format and use-case coverage of the native samples.

Until the Flutter samples are updated, the best examples we have for loading multiple ads in a scrollable view are the native examples:
- [iOS (TableView)](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Objective-C/advanced/BannerTableViewExample)
- [Android (RecyclerView)](https://github.com/googleads/googleads-mobile-android-examples/tree/main/java/advanced/BannerRecyclerViewExample)

**Comment by timothyhoang-google** [comment] 2022-09-27 17:03
I'll close this issue for tracking purposes.

An update on the Flutter app samples will be provided on #567.

**Closed by timothyhoang-google** 2022-09-27 17:03 UTC
Labels: bug, wont fix - intended behavior, native ad

**Comment by vagadiyainfotech** [comment] 2022-11-09 06:19
Do you find the solution ? @maheshmnj @davemg3 @timothyhoang-google @ldobreira
