### ISSUE TITLE
Getting error while showing interstitial in Flutter

### ISSUE THREAD

**Issue by aykutuludag** [googleads/googleads-mobile-flutter#995] opened 2024-01-17 21:07 UTC
Plugin Version: 4.0.0

I'm able to show interstitial ads to most user, but some user can't see interstitial even interstitial is loaded. I am sharing my code in below. Standart implementation.

## Steps to Reproduce
NOTHING. JUST IMPLEMENTED AND RELEASED TO GOOGLE PLAY. IT WORKS FOR %97-%98 OF USERS. Rest of them getting following error **while showing interstitial.**

<img width="738" alt="Ekran Resmi 2024-01-18 00 04 17" src="https://github.com/googleads/googleads-mobile-flutter/assets/18382503/e19229c6-6583-4780-b0b1-4a31da16718c">
<img width="720" alt="Ekran Resmi 2024-01-18 00 04 28" src="https://github.com/googleads/googleads-mobile-flutter/assets/18382503/0dc8c0f3-a407-431e-8fe9-74f183438675">

```
void showInterstitialAd(BuildContext context, void Function() changeScreen) {
  fullPageAd!.fullScreenContentCallback = FullScreenContentCallback(
    onAdShowedFullScreenContent: (InterstitialAd ad) => {
      adCount++,
      createInterstitialAd(),
      FirebaseAnalytics.instance.logEvent(
        name: "interstitialSHOW",
      ),
    },
    onAdDismissedFullScreenContent: (InterstitialAd ad) {
      ad.dispose();
      changeScreen();
    },
    onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
      ad.dispose();
      createInterstitialAd();
      FirebaseAnalytics.instance.logEvent(
        name: "interstitialFAILSHOW",
        parameters: {
          "errorReason": error.message,
        },
      );
      changeScreen();
    },
  );
  fullPageAd!.show();
  fullPageAd = null;
}
```

This is my code to show interstitial. After showing interstitial (onAdDismissedFullScreenContent) or getting  error (onAdFailedToShowFullScreenContent) changeScreen function triggered and change screen in Flutter.

This code can able to show ads to most of user but some users getting error as you can see in screenshot. Those data come from onAdDismissedFullScreenContent block. I am logging that part as you can see.

Before switching flutter, my app was Native Android written in Java. I was still getting this error but it was %1 of current rate. Flutter and google-mobile-ads plugin gives this interstitial error 100 times comparing native plugin.

I look it up why it is happening. I found some results (https://github.com/googleads/googleads-mobile-flutter/issues/906) but none of them giving exact solution. I am hoping you can fix it. Have a nice day.

**Comment by aykutuludag** [comment] 2024-01-17 21:17
Also I'm using banner ad in my app, too. Standart implementation. I am getting following error very often.

<img width="738" alt="Ekran Resmi 2024-01-18 00 04 17" src="https://github.com/googleads/googleads-mobile-flutter/assets/18382503/8e1c0b71-1d7c-436f-b6ef-24ba0c3f0ba0">

```
void loadBanner(void Function() loadView) {
  if (!isPremiumUser) {
    final bannerAdUnitId = Platform.isAndroid ? bannerAndroid : banneriOS;
    bannerAd = BannerAd(
      adUnitId: bannerAdUnitId,
      request: const AdRequest(),
      size: AdSize.largeBanner,
      listener: BannerAdListener(
        onAdLoaded: (ad) async {
          FirebaseAnalytics.instance.logEvent(
            name: "bannerLOADED",
          );
        },
        onAdFailedToLoad: (ad, err) {
          ad.dispose();
          FirebaseAnalytics.instance.logEvent(
            name: "bannerFAILED",
            parameters: {
              "errorReason": err.message,
            },
          );
          loadView();
        },
      ),
    )..load();
  }
}
```

**Comment by aykutuludag** [comment] 2024-01-17 21:24
Also, I'm getting error while **trying to LOAD INTERSTITIAL**. Code is same and you can see In the above. These logs are coming from **onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error)**.

<img width="699" alt="Ekran Resmi 2024-01-18 00 21 11" src="https://github.com/googleads/googleads-mobile-flutter/assets/18382503/ea116e51-2af1-482f-8586-b70f28cefde8">

I understand that it is impossible to show ads %100 success rate. But I recently switched from native java/kotlin app to flutter app and show rate dropped dramatically and error rate increased.

Comparing with native android and flutter, show rate is so much lower and error rate high. I'm not sure why I shared what I found. Best regards.

**Comment by aykutuludag** [comment] 2024-01-17 21:34
In comparision with native android and flutter.

**AT LOADING STAGE**
nativeAndroid: %95 success on interstitial, %99 on banner.
flutter: %85 on interstitial, %90 on banner.

**(AT SHOWING STAGE)**
nativeAndroid: %99.5 successful show rate on interstitial. %99.9 on banner.
flutter: %94-%95 succesful show rate on interstitial. %96 on banner.

**Comment by aykutuludag** [comment] 2024-01-17 23:20
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22621.3007], locale en-US)
    • Flutter version 3.16.0 on channel stable at C:\FlutterSDK
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (9 weeks ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\AndroidSDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\AndroidSDK
    • ANDROID_SDK_ROOT = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.25)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33423.256
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Program Files\Android\Android Studio
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.79.2)
    • VS Code at C:\Users\Aykut\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.3007]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.217
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 120.0.2210.133

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by malandr2** [comment] 2024-01-18 16:36
Hi @aykutuludag, 

For the `Unable to obtain a JavaScriptEngine` error that appears to be related to network conditions which negatively affect SDK performance, see this [StackOverflow post](https://stackoverflow.com/questions/64020685/how-to-fix-the-android-admob-unable-to-obtain-a-javascriptengine-error) for more information. 

For the `The Ad cannot be shown when the app is in the foreground.` that is something that has been addressed in https://github.com/googleads/googleads-mobile-flutter/issues/906 and has been helpful in decreasing that error. However, user behavior such as backgrounding the app may cause this error to still happen for a perfectly valid reason. 

For the `The provided view controller is not being presented` that is an error that would appear when running iOS, not Android. This happens the `viewcontroller.view.window` is nil. This may happen, based on the timing of the interstitial being displayed, because the user may have navigated to a different screen. 

And anecdotally, the %s should take in to account the volume of ads. Based on the screenshots, we expect the % to increase to the mean when the volume has increased. 

If you have any more questions let me know. As always, if you need us to take a closer look we recommend to share a [minimum reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) with steps to replicate what you are experiencing. Thanks!

**Comment by peterweb2005** [comment] 2024-01-23 12:24
@malandr2 error not decreased but increased, 
30 days, from 3.6 to 4.4k

**Comment by malandr2** [comment] 2024-01-23 15:20
@peterweb2005 have you shared a [minimum reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) before related to this issue? I can take a look to determine if your implementation is setup correctly. 

Also if the error is only observed on Android devices, another step you can take is to fill out a thread the [Developers forum](https://groups.google.com/g/google-admob-ads-sdk)

**Comment by peterweb2005** [comment] 2024-01-23 15:26
@malandr2 as this comment https://github.com/googleads/googleads-mobile-flutter/issues/906#issuecomment-1690380593

just "crash report" the error in onAdFailedToShowFullScreenContent: (ad, error) {

**Comment by malandr2** [comment] 2024-01-29 17:41
Hey @peterweb2005, that's correct [App Open](https://developers.google.com/admob/flutter/app-open) and [Interstitial](https://developers.google.com/admob/flutter/interstitial) are separate ad formats.

If you can provide a [minimum reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) I can take a look. Thanks

**Comment by peterweb2005** [comment] 2024-01-29 19:06
@malandr2 as the comment https://github.com/googleads/googleads-mobile-flutter/issues/906#issuecomment-1691538153

just same as the sample project, but "crash report" error if code = 3, as the sample just debug print error:

1. on app init event, register AppLifecycleReactor
```dart
  @override
  void initState() {
    super.initState();
    AppOpenAdManager appOpenAdManager = AppOpenAdManager()..loadAd();
    _appLifecycleReactor =
        AppLifecycleReactor(appOpenAdManager: appOpenAdManager);
    _appLifecycleReactor.listenToAppStateChanges();
  }
```

2. on AppLifecycleReactor foreground event, call showAdIfAvailable()
```dart
  void listenToAppStateChanges() {
    AppStateEventNotifier.startListening();
    AppStateEventNotifier.appStateStream
        .forEach((state) => _onAppStateChanged(state));
  }

  void _onAppStateChanged(AppState appState) {
    print('New AppState state: $appState');
    if (appState == AppState.foreground) {
      appOpenAdManager.showAdIfAvailable();
    }
  }
```

3. "crash report" the error,
```dart
  onAdFailedToShowFullScreenContent: (ad, error) {
    if (error.code == 3) {
      FirebaseCrashlytics.instance.recordError(error, information: ['app open ad']);
    }
  }
```

**Comment by malandr2** [comment] 2024-02-05 15:55
@peterweb2005 can you share again the _exact_ steps to reproduce using the sample project?

**Comment by peterweb2005** [comment] 2024-02-05 16:02
> @peterweb2005 can you share again the _exact_ steps to reproduce using the sample project?

app open ad must be called on app notifier foreground event
while interstitial must be called on app lifecycle resumed event
there isn't any alternatives

**Comment by malandr2** [comment] 2024-02-16 19:08
Hey @peterweb2005, if the issue only occurs on Android I recommend to fill out a new thread in the [Developers forum](https://groups.google.com/g/google-admob-ads-sdk) to create a new issue for it to be properly triaged. To confirm, please try to reproduce using our [Android example](https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/AppOpenExample).

Closing this issue out as it's infeasible to reproduce (does not happen every time) and Flutter engineering [already took a look at this issue](https://github.com/googleads/googleads-mobile-flutter/issues/906). When creating the thread in the forum, please provide clear steps to consistently reproduce. Thanks.

**Closed by malandr2** 2024-02-16 19:08 UTC
Labels: feedback required, in triage

**Comment by peterweb2005** [comment] 2024-02-17 06:47
@malandr2 I believe I can't produce an android example, as my code come from flutter sample, & I cant make an Android native app which can have hundreds of users to test to report the ad no show error
