### ISSUE TITLE
Proposal for fullScreen story ads

### ISSUE THREAD

**Issue by BrianTum** [googleads/googleads-mobile-flutter#555] opened 2022-04-28 19:15 UTC
## Use case

Stories or Status content are becoming a trend. Stories are full-page list content that users go through by swiping from one page to another. This form of content has attracted many users, especially on social media sites. My app also uses such stories. 

I would like to monetize my story content with google ads. Currently, the only implementation that offers the best user experience is the native ads format. However, its implementation is hard and requires vast knowledge in native android/ios. 

## Proposal

Therefore, I am proposing a solution that will offer full-page ads with a good user experience. 

A case study can be done to see how [amp story ads](https://support.google.com/adsense/answer/10175505?hl=en) was able to monetize their content with google ads.

**Comment by maheshmnj** [comment] 2022-04-29 12:45
Hi @BrianTum, thanks for filing the issue. This is certainly a valid use case But provided that this can be achieved with the help of Native ads, I am quite not sure if the ads team would want to introduce a new type of ad. I am Labeling this issue as a valid feature request though, But I will leave the team members to decide. 

cc: @jjliu15

**Comment by BrianTum** [comment] 2022-04-30 09:19
It will be interesting to see this feature alive as more content becomes stories. Help will be highly appreciated

**Comment by Tom3652** [comment] 2022-07-12 18:46
I think you can upvote this feature request #313 :)

**Comment by timothyhoang-google** [comment] 2022-09-22 21:19
As you mentioned, the closest you can get to a Stories format ad is by using fullscreen native video.

We are working on supporting Dart only Native Ads in Q4'22. I'll provide an updated timeline closer to launch.

For tracking purposes, I'm marking this issue as a duplicate of a more [populated issue](https://github.com/googleads/googleads-mobile-flutter/issues/313) for visibility.

Duplicate of #313.

**Comment by timothyhoang-google** [comment] 2022-09-22 21:19
Duplicate of #313

**Closed by timothyhoang-google** 2022-09-22 21:19 UTC
Labels: feature request
