### ISSUE TITLE
[IOS] [PROBLEM] App enters in background/crashes when ad is loaded (iPhone 12)

### ISSUE THREAD

**Issue by RoyalCoder88** [googleads/googleads-mobile-flutter#861] opened 2023-06-08 22:01 UTC
Hi,

I'm using the latest version of Flutter 3.10.5 and XCode 14.3.1, I have problems on iPhone 12 devices, my app enters in the background/crashes when the Ad is loaded :( please guide me on how can I check why this is happening, or how to fix it, thanks in advance!

**To Mention**: on iPhones 13, and 14 it's working perfectly.

**Plugin version**: 3.0.0

**Device info:**
![device_info](https://github.com/googleads/googleads-mobile-flutter/assets/6507433/3aab7c23-b8dd-45a0-8ca4-f7fb31d34669)

**Video recording:**

https://github.com/googleads/googleads-mobile-flutter/assets/6507433/8a012905-d9fb-4543-8b41-986933a5e4e1

Any help will be much appreciated!

**Comment by huycozy** [comment] 2023-06-09 11:42
Hi @RoyalCoder88 
Have you try re-installing pods? Please also try running [ads sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and check if the issue still persists or not.

**Comment by huycozy** [comment] 2023-06-15 12:10
>google_maps_flutter_ios(FLTGoogleMapTileOverlayController.o)
                    ld: symbol(s) not found for architecture arm64

I think it could be caused by maps plugin. Can you confirm this issue also occurs on [ads sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)? 

You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages to find potential cause from plugins if any.

**Comment by RoyalCoder88** [comment] 2023-06-20 16:13
> > google_maps_flutter_ios(FLTGoogleMapTileOverlayController.o)
> > ld: symbol(s) not found for architecture arm64
> 
> I think it could be caused by maps plugin. Can you confirm this issue also occurs on [ads sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)?
> 
> You should narrow down the issue by removing the usage of 3rd party plugins/packages one by one, unrelated/unaffected pages to find potential cause from plugins if any.

@huycozy I managed to fix this only by removing my entire ios folder, and set up all the settings & pods by scratch, but now I get a problem on displaying ads on iPhone 12 :(

**Comment by huycozy** [comment] 2023-06-22 11:13
Hi @RoyalCoder88 
Since the original issue has been solved, please open new issue for your new issue that will help issue's database is consistent (others who may encounter this issue later can find out the issue easily). Closing this issue as solved.

**Closed by huycozy** 2023-06-22 11:13 UTC
Labels: in triage
