### ISSUE TITLE
native ads using dart code and flutter widgets

### ISSUE THREAD

**Issue by ghost** [googleads/googleads-mobile-flutter#233] opened 2021-05-14 12:18 UTC
It will be very great to use dart code to design native ads with flutter widgets inside the flutter app and this will be very useful especially with people that they start coding with flutter without knowing anything with native android and iOS development or flutter is their best framework like me some packages in the `pub.dev` do that before but now is no complemented with `google_mobile_ads `package and we facing some problems when we use it with `google_mobile_ads `plugin and also my cause some AdMob limitation or other AdMob problems  Couse is not official from google dev otherwise the user will need to have good knowledge about native coding with android studio and XCode to implement that     

and finally 
my thanks for all the flutter framework team they did a great job

**Comment by ramtinq** [comment] 2022-04-18 21:24
This (unfortunately deprecated) package did that:

https://github.com/bdlukaa/native_admob_flutter

Thought it might help for anyone who might be interested in implementing the same functionality in this package.

**Comment by timothyhoang-google** [comment] 2022-09-22 21:14
We are working on supporting Dart only Native Ads in Q4'22. I'll provide an updated timeline closer to launch.

While this issue was logged first, I'm marking it as a duplicate of a more [populated issue](https://github.com/googleads/googleads-mobile-flutter/issues/313) for visibility.

**Closed by timothyhoang-google** 2022-09-22 21:14 UTC
Labels: feature request

**Comment by timothyhoang-google** [comment] 2022-09-22 21:15
Duplicate of #313
