### ISSUE TITLE
What version of com.google.android.gms:play-services-ads does the non-null-safe version 0.11.0+4 use?

### ISSUE THREAD

**Issue by gracegyu** [googleads/googleads-mobile-flutter#849] opened 2023-05-22 06:55 UTC
What version of com.google.android.gms:play-services-ads does the non-null-safe version 0.11.0+4 use?

Recently in the Playstore, apps with version com.google.android.gms:play-services-ads:19.2.0 say that you cannot submit a new version.
Version 19.3.0+ is required.

Please confirm.

I'm currently having a hard time converting my App to null-safety.

------ the message ------

This version is officially deprecated, and will soon disable ad loading. Please update to a new version. See https://developers.google.com/admob/android/deprecation for more details.

From 00:00 UTC on August 21, 2023, we will not be able to release new versions including this SDK version.

**Comment by huycozy** [comment] 2023-05-23 11:55
Hi @gracegyu 
It seems you are using an old plugin version. The current ads plugin version is `google_mobile_ads: ^3.0.0` and using `com.google.android.gms:play-services-ads:22.0.0`. 

Please try the newer version and confirm if the issue is solved or not. Thank you!

**Comment by gracegyu** [comment] 2023-05-23 23:29
I am unable to convert my App to null-safety.
Can you upgrade the google ad library to the Not null-safe version?

**Comment by huycozy** [comment] 2023-05-25 11:41
Unfortunately, the plugin has been migrated to null safety since version `0.12.0`. Please check [Migrating to null safety](https://dart.dev/null-safety/migration-guide) as a guideline for your project. 

Closing as it's not a plugin's issue.

**Closed by huycozy** 2023-05-25 11:41 UTC
Labels: in triage
