### ISSUE TITLE
App Open Ads Support

### ISSUE THREAD

**Issue by pmathulan** [googleads/googleads-mobile-flutter#370] opened 2021-09-10 15:40 UTC
## Use case

Want to support AdMob new ad type of **App Open** Ad

## Proposal
An ad format that appears when users open or switcheses back to your app. Ad overlays loading screen.

**Comment by maheshmnj** [comment] 2021-09-13 12:26
Admob now supports new ad Type App Open Ads: https://developers.google.com/admob/android/app-open

Marking this issue as valid feature request.

**Comment by maheshmnj** [comment] 2021-09-14 06:30
Closing this issue as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/171

**Closed by maheshmnj** 2021-09-14 06:30 UTC
Labels: feature request
