### ISSUE TITLE
ios simulator throwing an error after package google_ads

### ISSUE THREAD

**Issue by REX2420** [googleads/googleads-mobile-flutter#604] opened 2022-07-11 17:07 UTC
same issue

**Comment by huycozy** [comment] 2022-07-12 07:35
When opening an issue, please try to provide all or some of the information indicated in the template so that we can address this issue properly.

<details>
<summary>Issue Template</summary>



## Plugin Version



## Steps to Reproduce



1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>



```
```



```
```



```
```

</details>

</details>

Closing this issue, since no information has been provided. Once you have provided information, please update the issue then I will reopen this.
Thank you.

**Closed by huycozy** 2022-07-12 07:35 UTC
Labels: in triage
