### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null

### ISSUE THREAD

**Issue by Isaacn123** [googleads/googleads-mobile-flutter#853] opened 2023-05-26 12:03 UTC
at io.flutter.plugins.googlemobileads.GoogleMobileAdsViewFactory.create(GoogleMobileAdsViewFactory.java:60)
E/flutter (12297): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
E/flutter (12297): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter (12297): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (12297): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (12297): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (12297): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (12297): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)

**Comment by huycozy** [comment] 2023-05-26 12:21
Hi @Isaacn123 
Can you please share the complete stack trace if any? 

Maybe a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/672

**Comment by Isaacn123** [comment] 2023-05-26 13:33
ok

**Comment by Isaacn123** [comment] 2023-05-26 13:34
I/flutter (12297): Failed to Load a banner ad: Received error HTTP response code: 403
E/MethodChannel#flutter/platform_views(12297): Failed to handle method call
E/MethodChannel#flutter/platform_views(12297): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#flutter/platform_views(12297): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsViewFactory.create(GoogleMobileAdsViewFactory.java:60)
E/MethodChannel#flutter/platform_views(12297): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
E/MethodChannel#flutter/platform_views(12297): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views(12297): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(12297): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views(12297): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views(12297): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(12297): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(12297): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views(12297): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(12297): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#flutter/platform_views(12297): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter/platform_views(12297): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/MethodChannel#flutter/platform_views(12297): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(12297): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter/platform_views(12297): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
D/EGL_emulation(12297): app_time_stats: avg=25.49ms min=2.24ms max=415.36ms count=37
E/flutter (12297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/flutter (12297): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsViewFactory.create(GoogleMobileAdsViewFactory.java:60)
E/flutter (12297): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
E/flutter (12297): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter (12297): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (12297): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (12297): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (12297): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter (12297): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (12297): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (12297): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (12297): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (12297): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (12297): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/flutter (12297): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12297): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (12297): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (12297): )
E/flutter (12297): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (12297): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (12297): <asynchronous suspension>
E/flutter (12297): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146:18)
E/flutter (12297): <asynchronous suspension>
E/flutter (12297): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792:5)
E/flutter (12297): <asynchronous suspension>
E/flutter (12297):

**Comment by Isaacn123** [comment] 2023-05-26 14:03
Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     ( 2133): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("2B68571209EBA6302CCDC72B4D380CD4")) to get test ads on this device.
I/art     ( 2133): Rejecting re-init on previously-failed class java.lang.Class<j$.util.concurrent.f>
I/art     ( 2133): Rejecting re-init on previously-failed class java.lang.Class<agh>
W/ConnectionStatusConfig( 2133): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.CACHE
W/Ads     ( 2133): Not retrying to fetch app settings
W/ConnectionStatusConfig( 2133): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.START
I/Ads     ( 2133): Ad failed to load : 3
D/libc    ( 2133): [NET] android_getaddrinfofornet+,hn 18(0x6d697261636c65),sn(),hints(known),family 0,flags 1024
D/libc    ( 2133): [NET] android_getaddrinfofornet-, pass to proxy
D/libc    ( 2133): [NET] android_getaddrinfo_proxy+
D/libc    ( 2133): [NET] android_getaddrinfo_proxy get netid:0
D/libc    ( 2133): [NET] android_getaddrinfo_proxy-, success
D/libc    ( 2133): [NET] android_getaddrinfofornet+,hn 18(0x6d697261636c65),sn(),hints(known),family 0,flags 1024
D/libc    ( 2133): [NET] android_getaddrinfofornet-, pass to proxy
D/libc    ( 2133): [NET] android_getaddrinfo_proxy+
D/libc    ( 2133): [NET] android_getaddrinfo_proxy get netid:0
D/libc    ( 2133): [NET] android_getaddrinfo_proxy-, success
I/flutter ( 2133): STOR null
D/libc    ( 2133): [NET] android_getaddrinfofornet+,hn 18(0x6d697261636c65),sn(),hints(known),family 0,flags 1024
D/libc    ( 2133): [NET] android_getaddrinfofornet-, pass to proxy
D/libc    ( 2133): [NET] android_getaddrinfo_proxy+
D/libc    ( 2133): [NET] android_getaddrinfo_proxy get netid:0
D/libc    ( 2133): [NET] android_getaddrinfo_proxy-, success
D/libc    ( 2133): [NET] android_getaddrinfofornet+,hn 18(0x6d697261636c65),sn(),hints(known),family 0,flags 1024
D/libc    ( 2133): [NET] android_getaddrinfofornet-, pass to proxy
D/libc    ( 2133): [NET] android_getaddrinfo_proxy+
D/libc    ( 2133): [NET] android_getaddrinfo_proxy get netid:0
D/libc    ( 2133): [NET] android_getaddrinfofornet+,hn 18(0x6d697261636c65),sn(),hints(known),family 0,flags 1024
D/libc    ( 2133): [NET] android_getaddrinfofornet-, pass to proxy
D/libc    ( 2133): [NET] android_getaddrinfo_proxy+
D/libc    ( 2133): [NET] android_getaddrinfo_proxy get netid:0
D/libc    ( 2133): [NET] android_getaddrinfo_proxy-, success
D/libc    ( 2133): [NET] android_getaddrinfo_proxy-, success
I/flutter ( 2133): Failed to Load a banner ad: Received error HTTP response code: 403
I

**Comment by huycozy** [comment] 2023-05-30 12:02
You can reproduce the issue locally, right? Can you please run [plugin example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and check if the issue still persists or not?

Also, please provide the list of affected device info as well (OS version, model). Thank you!

**Closed** 2023-06-20 12:07 UTC
Labels: feedback required, in triage
