### ISSUE TITLE
[iOS] Banner does not respect widget tree

### ISSUE THREAD

**Issue by atrope** [googleads/googleads-mobile-flutter#242] opened 2021-05-19 16:28 UTC
Hi I've Updated to the latest Ads Version and our Banners are not respecting the Widget tree.

When we load the banners they are appearing on the top of the screen until we scroll to his position and then it behaves as a normal widget until we scroll up when it follows on the bottom of the screen 😆 

Attached the video

https://user-images.githubusercontent.com/2945478/118849182-dc4bc580-b8a5-11eb-9e72-5250d2499954.mp4

tested on:
iPhone6S - iOS 12
iPhone 8 - iOS 14.4
iPhone X  - iOS 14.4

**Comment by jjliu15** [comment] 2021-05-19 19:18
Few questions:
- Could you share the output of `flutter doctor -v`?
- What was the previous version of the plugin you were using?
- Does this happen if you don't show the InterstitialAd when transitioning between screens? 
- Do you have any code you can share that reproduces the issue?

**Comment by atrope** [comment] 2021-05-19 19:36
@jjliu15 Of course:
```
~ » flutter doctor -v                                 
[✓] Flutter (Channel dev, 2.3.0-1.0.pre, on macOS 11.2.3 20D91 darwin-x64,
    locale en)
    • Flutter version 2.3.0-1.0.pre at /Users/trope/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d97f41caed (3 weeks ago), 2021-04-30 12:35:21 -0700
    • Engine revision e7939e091e
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/trope/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/trope/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.212

```

2 - was using the latest one 0.12

3 - Yes it happens independently of the Interstitial.

4 - It's pretty straightforward, i can try to create a Minimal code but i can't share right now.

I am loading and then setting state inside onLoaded.

**Comment by atrope** [comment] 2021-05-21 16:05
Hi @jjliu15 
I've managed to create a minimal code:

https://github.com/atrope/bannertest

Here is the video also:


https://user-images.githubusercontent.com/2945478/119166600-3333d500-ba35-11eb-9b96-f2cf5012a3ac.mp4

**Comment by jjliu15** [comment] 2021-05-23 04:23
I was able to reproduce this issue after downgrading my flutter version to `Flutter version 2.3.0-0.1.pre`. Can you try running `flutter upgrade` and seeing if that fixes the issue?

**Comment by atrope** [comment] 2021-05-24 17:01
@jjliu15 Yes it did work after an upgrade using dev channel. 

Do you know what changed and when it will arrive to Beta/Stable?

**Comment by jjliu15** [comment] 2021-05-25 21:47
I checked on the latest stable release (2.2.0) and could not reproduce the issue. I'm not sure what caused the issue in `2.3.0-0.1.pre`, but since it is fixed in the latest `dev` version I think this can just be considered a transient bug in `dev`. [Flutter's recommendation](https://flutter.dev/docs/development/tools/sdk/upgrading#switching-flutter-channels) is that you use the stable channel unless you need to use something's only available in dev or beta. 

@blasten and @bparrishMines may be able to comment more on when 2.3.0 will be make it to beta/stable.

**Closed** 2021-05-26 20:14 UTC

**Comment by andynvt** [comment] 2021-06-25 14:33
> I checked on the latest stable release (2.2.0) and could not reproduce the issue. I'm not sure what caused the issue in `2.3.0-0.1.pre`, but since it is fixed in the latest `dev` version I think this can just be considered a transient bug in `dev`. [Flutter's recommendation](https://flutter.dev/docs/development/tools/sdk/upgrading#switching-flutter-channels) is that you use the stable channel unless you need to use something's only available in dev or beta.
> 
> @blasten and @bparrishMines may be able to comment more on when 2.3.0 will be make it to beta/stable.

Any updates? Does it work, I am using flutter `2.0.6`, ios release not showing ads
