### ISSUE TITLE
Screen flickering when navigating to a new screen. This happens after updating to the latest 1.0.1 version.

### ISSUE THREAD

**Issue by wrteam-priyansh** [googleads/googleads-mobile-flutter#467] opened 2021-12-10 10:32 UTC
Screen flickering when navigating to a new screen. This happens after updating to the latest 1.0.1 version. Before the update, everything worked well. If removes banner ad navigation works well.

Attaching video of this issue

https://user-images.githubusercontent.com/73931541/145559808-37c4a1d0-f57b-48fa-be1f-c6afcf1fb2a3.mp4

 Result of flutter doctor -v

[✓] Flutter (Channel stable, 2.8.0, on Ubuntu 20.04.3 LTS 5.11.0-27-generic, locale en_GB.UTF-8)
    • Flutter version 2.8.0 at /home/mahek/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/mahek/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /home/mahek/Android/Sdk
    • Java binary at: /opt/android-studio-4.1/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 4.1)
    • Android Studio at /opt/android-studio-4.1/android-studio
    • Flutter plugin version 53.0.1
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.62.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • ASUS X01BDA (mobile) • JBAAGF07Z4433FF    • android-arm64  • Android 9 (API 28)
    • ASUS X01BDA (mobile) • 192.168.1.139:5555 • android-arm64  • Android 9 (API 28)
    • Linux (desktop)      • linux              • linux-x64      • Ubuntu 20.04.3 LTS 5.11.0-27-generic
    • Chrome (web)         • chrome             • web-javascript • Google Chrome 96.0.4664.45

**Comment by maheshmnj** [comment] 2021-12-10 13:26
Hi @CripyIce, Thanks for filing the issue. I was able to reproduce a similar flickering when pushing new route  is the same thing you are referring too?


https://user-images.githubusercontent.com/31410839/145580549-1097711b-e268-4469-9540-cebe4a7f9209.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.6:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```
</details>



<details>
<summary>code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: HomeScreen());
  }
}



class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(child: ListView.builder(itemBuilder: (context, index) {
            return ListTile(
              title: Text('Item $index'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            );
          })),
          const CustomBannerAd()
        ],
      ),
    );
  }
}

class ProducDetailPage extends StatelessWidget {
  const ProducDetailPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Produc Detail'),
        ),
        body: Column(children: const [
          SizedBox(
            height: 150,
            child: Placeholder(
              color: Colors.red,
            ),
          ),
          SizedBox(
            height: 150,
            child: Placeholder(
              color: Colors.green,
            ),
          ),
          CustomBannerAd()
        ]));
  }
}

class CustomBannerAd extends StatefulWidget {
  const CustomBannerAd({Key? key}) : super(key: key);

  @override
  _CustomBannerAdState createState() => _CustomBannerAdState();
}

class _CustomBannerAdState extends State<CustomBannerAd> {
  BannerAd? _anchoredAdaptiveAd;
  var _isLoaded = false;
  late Orientation _currentOrientation;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    _currentOrientation = MediaQuery.of(context).orientation;
    _loadAd();
  }

  @override
  void dispose() {
    super.dispose();

    _anchoredAdaptiveAd?.dispose();
  }

  Future<void> _loadAd() async {
    await _anchoredAdaptiveAd?.dispose();

    if (mounted) {
      setState(() {
        _anchoredAdaptiveAd = null;
        _isLoaded = false;
      });
    }

    final AnchoredAdaptiveBannerAdSize? size =
        await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
            MediaQuery.of(context).size.width.truncate());

    if (size == null) {
      debugPrint('Unable to get height of anchored banner.');
      return;
    }

    _anchoredAdaptiveAd = BannerAd(
      adUnitId: Platform.isAndroid
          ? 'ca-app-pub-3940256099942544/6300978111'
          : 'ca-app-pub-3940256099942544/2934735716',
      size: size,
      request: const AdRequest(
        nonPersonalizedAds: false,
      ),
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          debugPrint("Ad loaded");
          if (mounted) {
            setState(() {
              _anchoredAdaptiveAd = ad as BannerAd;
              _isLoaded = true;
            });
          }
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          debugPrint('$BannerAd failedToLoad: $error');
          ad.dispose();
        },
        onAdOpened: (Ad ad) => debugPrint('$BannerAd onAdOpened.'),
        onAdClosed: (Ad ad) => debugPrint('$BannerAd onAdClosed.'),
      ),
    );

    return _anchoredAdaptiveAd?.load();
  }

  @override
  Widget build(BuildContext context) {
    return OrientationBuilder(builder: (context, orientation) {
      if (_currentOrientation == orientation &&
          _anchoredAdaptiveAd != null &&
          _isLoaded) {
        return Container(
          color: Colors.transparent,
          width: _anchoredAdaptiveAd!.size.width.toDouble(),
          height: _anchoredAdaptiveAd?.size.height.toDouble(),
          child: AdWidget(ad: _anchoredAdaptiveAd!),
        );
      }

      // Reload the ad if the orientation changes.
      if (_currentOrientation != orientation) {
        _currentOrientation = orientation;
        _loadAd();
      }
      return const SizedBox.shrink();
    });
  }
}

```
</details>

Thanks

**Comment by maheshmnj** [comment] 2021-12-10 13:29
Can you also please point the versions you upgraded from?

**Comment by M97Chahboun** [comment] 2021-12-10 20:13
Me too i have this issue when i updated flutter to last version & detected the issue from ads package i hope solve it

**Comment by M97Chahboun** [comment] 2021-12-10 20:18
I get this debug

`I/ViewRootImpl@f082aaf[MainActivity](23661): ViewPostIme pointer 0
I/ViewRootImpl@f082aaf[MainActivity](23661): ViewPostIme pointer 1
I/flutter (23661): {}
I/mali_egl(23661): eglDestroySurface() in
I/mali_egl(23661): eglDestroySurface() out
I/mali_egl(23661): eglDestroySurface() in
I/mali_winsys(23661): delete_surface() [1080x2092] return
I/mali_egl(23661): eglDestroySurface() out
E/BufferQueueProducer(23661): [ImageReader-1080x2092f1m3-23661-4] disconnect: not connected (req=1)
W/libEGL  (23661): EGLNativeWindowType 0x77b3831010 disconnect failed
I/mali_egl(23661): eglDestroySurface() in
I/mali_winsys(23661): delete_surface() [1080x2092] return
I/mali_egl(23661): eglDestroySurface() out
E/BufferQueueProducer(23661): [ImageReader-1080x2092f1m3-23661-0] disconnect: not connected (req=1)
W/libEGL  (23661): EGLNativeWindowType 0x7d27a28010 disconnect failed
I/mali_winsys(23661): new_window_surface() [1080x2092] return: 0x3000
W/Ads     (23661): #004 The webview is destroyed. Ignoring action.
I/chatty  (23661): uid=11675(com.example.jahez) identical 3 lines
W/Ads     (23661): #004 The webview is destroyed. Ignoring action.
`

**Comment by M97Chahboun** [comment] 2021-12-10 20:27
I solved it 
i used pop instead of push 
like this if you want exit with popup 
`context..pop()..pop()`
first pop for hide popup & second for back to previous screen.
@wrteam-priyansh

**Comment by Paitomax** [comment] 2021-12-11 02:58
Also happens to me when push to a new route, right after upgrading to flutter 2.8.0

https://user-images.githubusercontent.com/14266027/145661452-2de3febb-d79d-48da-8652-fd9ed7c0d88f.mp4

**Comment by wrteam-priyansh** [comment] 2021-12-11 03:53
> Can you also please point the versions you upgraded from?

The previous version of google_ads was 0.13.4 and the previous version of flutter was 2.5.3

**Comment by wrteam-priyansh** [comment] 2021-12-11 03:54
> I solved it i used pop instead of push like this if you want exit with popup `Navigator.of(context)..pop()..pop()` first pop for hide popup & second for back to previous screen. @wrteam-priyansh

@M97Chahboun i will try this solution

**Comment by envercc** [comment] 2021-12-11 15:17
https://user-images.githubusercontent.com/66693592/145681691-92ca2e7d-eaf2-4f16-aceb-6ff5a085eb2c.mp4

I get this too. When I comment out the Banner, the flicker goes away.

**Comment by peterwvj** [comment] 2021-12-12 22:02
I'm experiencing this too after upgrading to 1.0.1. The flickering happens when I navigate to a new screen from another screen that has a banner. When I comment out the banner the flickering goes away.

```dart
λ flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on Ubuntu 20.04.3 LTS 5.11.0-41-generic, locale en_US.UTF-8)
    • Flutter version 2.8.0 at /home/peter/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/peter/Android/Sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /home/peter/dev/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/peter/dev/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] VS Code (version 1.62.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 32) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 96.0.4664.45

• No issues found!

```

**Comment by maheshmnj** [comment] 2021-12-13 04:05
Thanks, everyone for your inputs. I was able to the issue only on Android devices. The below sample was verified with the latest `google_mobile_ads: ^1.0.1`. It looks like this recent regression is from the flutter framework and not in the ads plugin as this is not reproducible on stable 2.5.3 with the latest ads plugin.

stable 2.5.3 ✅ | stable 2.8.0 ❌
:-: | :-:
<video src='https://user-images.githubusercontent.com/31410839/145750208-d09872cb-b164-41db-b273-508ed9c8c9a1.mov' width=180/> | <video src='https://user-images.githubusercontent.com/31410839/145750471-726e5a6b-edf9-4051-b6d5-9b0a26c0a2c6.mov' width=180/>

✅ : No Issue ❌: Issue reproduced


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (2 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.6:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.93

• No issues found!
```
</details>



<details>
<summary>code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: HomeScreen());
  }
}



class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(child: ListView.builder(itemBuilder: (context, index) {
            return ListTile(
              title: Text('Item $index'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            );
          })),
          const CustomBannerAd()
        ],
      ),
    );
  }
}

class ProducDetailPage extends StatelessWidget {
  const ProducDetailPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Produc Detail'),
        ),
        body: Column(children: const [
          SizedBox(
            height: 150,
            child: Placeholder(
              color: Colors.red,
            ),
          ),
          SizedBox(
            height: 150,
            child: Placeholder(
              color: Colors.green,
            ),
          ),
          CustomBannerAd()
        ]));
  }
}

class CustomBannerAd extends StatefulWidget {
  const CustomBannerAd({Key? key}) : super(key: key);

  @override
  _CustomBannerAdState createState() => _CustomBannerAdState();
}

class _CustomBannerAdState extends State<CustomBannerAd> {
  BannerAd? _anchoredAdaptiveAd;
  var _isLoaded = false;
  late Orientation _currentOrientation;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    _currentOrientation = MediaQuery.of(context).orientation;
    _loadAd();
  }

  @override
  void dispose() {
    super.dispose();

    _anchoredAdaptiveAd?.dispose();
  }

  Future<void> _loadAd() async {
    await _anchoredAdaptiveAd?.dispose();

    if (mounted) {
      setState(() {
        _anchoredAdaptiveAd = null;
        _isLoaded = false;
      });
    }

    final AnchoredAdaptiveBannerAdSize? size =
        await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
            MediaQuery.of(context).size.width.truncate());

    if (size == null) {
      debugPrint('Unable to get height of anchored banner.');
      return;
    }

    _anchoredAdaptiveAd = BannerAd(
      adUnitId: Platform.isAndroid
          ? 'ca-app-pub-3940256099942544/6300978111'
          : 'ca-app-pub-3940256099942544/2934735716',
      size: size,
      request: const AdRequest(
        nonPersonalizedAds: false,
      ),
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          debugPrint("Ad loaded");
          if (mounted) {
            setState(() {
              _anchoredAdaptiveAd = ad as BannerAd;
              _isLoaded = true;
            });
          }
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          debugPrint('$BannerAd failedToLoad: $error');
          ad.dispose();
        },
        onAdOpened: (Ad ad) => debugPrint('$BannerAd onAdOpened.'),
        onAdClosed: (Ad ad) => debugPrint('$BannerAd onAdClosed.'),
      ),
    );

    return _anchoredAdaptiveAd?.load();
  }

  @override
  Widget build(BuildContext context) {
    return OrientationBuilder(builder: (context, orientation) {
      if (_currentOrientation == orientation &&
          _anchoredAdaptiveAd != null &&
          _isLoaded) {
        return Container(
          color: Colors.transparent,
          width: _anchoredAdaptiveAd!.size.width.toDouble(),
          height: _anchoredAdaptiveAd?.size.height.toDouble(),
          child: AdWidget(ad: _anchoredAdaptiveAd!),
        );
      }

      // Reload the ad if the orientation changes.
      if (_currentOrientation != orientation) {
        _currentOrientation = orientation;
        _loadAd();
      }
      return const SizedBox.shrink();
    });
  }
}

```
</details>

Thanks

cc: @jjliu15

**Comment by M97Chahboun** [comment] 2021-12-13 14:34
@maheshmnj  exactly me too i downgrade flutter and working fine  can you open issue in flutter for solve it !

**Comment by chitgoks** [comment] 2021-12-14 00:24
Almost going to open up a new ticket because of this as well. Probably downgrading is the best solution for now.

**Comment by maheshmnj** [comment] 2021-12-15 05:42
@peterwvj,  Please file an issue in the flutter repo and link this issue, probably someone from the team will have some insights on this.

**Comment by peterwvj** [comment] 2021-12-15 17:19
@maheshmnj issue has been raised here https://github.com/flutter/flutter/issues/95343

**Comment by DabPb** [comment] 2021-12-16 06:49
Facing same issue!
Any Luck?

**Comment by SalsabeelaHasan** [comment] 2021-12-16 10:13
Same here, any Luck?

**Comment by peterwvj** [comment] 2021-12-16 13:05
Not that I know of. We're awaiting the Flutter team's input on this https://github.com/flutter/flutter/issues/95343

**Comment by wl1395182472** [comment] 2021-12-21 03:03
I found the same error both at that navigating to a new page and navigating back, can lifecycle support for Flutter widgets be a try?

**Comment by wl1395182472** [comment] 2021-12-21 04:00
[exmple.txt](https://github.com/googleads/googleads-mobile-flutter/files/7749445/exmple.txt)

**Comment by aenckli** [comment] 2021-12-25 08:14
Frustrated for many days, and finally found that I am not alone. I faced the same problem after upgraded to Flutter 2.8 and mobile ads 1.0.1. Sometimes, I also see "W/System  (12690): A resource failed to call release. " when navigating back in profile mode for testing, This does not occur when banner ad is removed.

**Comment by RomjanHossain** [comment] 2022-01-06 06:55
this package made my app so slow and on top of that it has that flicking issue. This is my first time using this package. I expected a better performance from it xD

**Comment by maheshmnj** [comment] 2022-01-06 07:27
This issue is marked as p1 (high priority) we should have an update soon.

**Comment by maheshmnj** [comment] 2022-01-13 18:16
This issue is fixed, and the fix is available on the latest `master, 2.9.0-1.0.pre.328`, This will be available on the stable channel in the upcoming `stable 2.10`. You may either wait until this is fixed or switch to master channel.

**Comment by MikeSchrijver** [comment] 2022-01-18 11:18
> This issue is fixed, and the fix is available on the latest `master, 2.9.0-1.0.pre.328`, This will be available on the stable channel in the upcoming `stable 2.10`. You may either wait until this lands on stable or switch to the master channel.

@maheshmnj Do you have a link to "master, 2.9.0-1.0.pre.328". I am unable to find it.

**Comment by maheshmnj** [comment] 2022-01-18 11:29
@MikeSchrijver, If you want to switch to the master channel you may run
 
```
flutter channel master
flutter upgrade
```

to switch back to your old channel e.g stable

```
flutter channel stable
flutter upgrade
```

**Comment by MikeSchrijver** [comment] 2022-01-18 11:50
> @MikeSchrijver, If you want to switch to the master channel you may run
> 
> ```
> flutter channel master
> flutter upgrade
> ```
> 
> to switch back to your old channel e.g stable
> 
> ```
> flutter channel stable
> flutter upgrade
> ```

I have done that several times but it brings me to Flutter version "2.9.0-1.0.pre.384" and in that version the screen flickering still occurs.

**Comment by maheshmnj** [comment] 2022-01-18 12:42
I am sorry I should have mentioned my flutter doctor earlier, This was my doctor where I verified that it was working fine.

```
[✓] Flutter (Channel master, 2.9.0-1.0.pre.328, on Ubuntu 20.04.3 LTS 5.11.0-43-generic, locale en_GB.UTF-8)
    • Flutter version 2.9.0-1.0.pre.328 at /home/mahesh/Development/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d290763941 (6 days ago), 2022-01-11 18:20:14 -0800
    • Engine revision 643b2787f4
    • Dart version 2.16.0 (build 2.16.0-159.0.dev)
    • DevTools version 2.9.2
```

You can switch to this flutter version using the framework revision from the `flutter doctor`, so execute

```
cd path_to_flutter_Sdk /// navigate to location where flutter SDK is installed
git checkout d290763941
```
> and in that version the screen flickering still occurs.

I will check and update on this

**Comment by MikeSchrijver** [comment] 2022-01-18 13:05
@maheshmnj Thanks for the help to get me to version "2.9.0-1.0.pre.328", but I have still screen flickering. For now I will downgrade to 2.5.3 and work with that untill the next stable is released.

**Comment by peterwvj** [comment] 2022-01-18 16:41
Consider using Flutter Version Management https://fvm.app/ if you want to switch between SDKs when developing your app

**Comment by marcellocamara** [comment] 2022-01-20 00:06
Same problems with flutter 2.8.1, dart 2.15.1 with google_mobile_ads 1.0.1

https://user-images.githubusercontent.com/18273071/150238294-c32f1dec-af99-42b5-9d16-b387d2cca844.mp4

**Comment by dipak2726** [comment] 2022-01-25 12:21
Try using this , it worked for me

google_mobile_ads:
    git:
      url: https://github.com/SuaMusica/googleads-mobile-flutter.git
      path: packages/google_mobile_ads
      ref: feature/suamusica

**Comment by maheshmnj** [comment] 2022-02-07 07:00
> I will check and update on this

https://github.com/flutter/flutter/issues/95343#issuecomment-1021947173

**Comment by muchirajunior** [comment] 2022-05-13 07:08
i have the same issue on rhe launch screen

**Comment by huycozy** [comment] 2023-07-19 12:16
We’re closing this issue due to inactivity. If you’re still impacted, please create a new issue via the [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk).

**Closed by huycozy** 2023-07-19 12:16 UTC
Labels: bug, p2-medium, e2-days, platform-android
