### ISSUE TITLE
A border pixel bleed using an inline ad (iOS on a real device)

### ISSUE THREAD

**Issue by jesteracer** [googleads/googleads-mobile-flutter#306] opened 2021-07-09 07:24 UTC
## Plugin Version

google_mobile_ads: ^0.13.1

## Steps to Reproduce

There is a pixel border bleed when using inline banner, that is integrating inside a sliver list (with a custom scroll view) or a listview.

It can be only reproduced on a real device,  but can not be captured using a screenshot or a screen-recorder (also, that the bug dissapears, when entering the app in a recording mode)

Here is a video of the bug, captured using another phone, since it is the only way to show what is going on:

[CustomScrollView with a SliverAppBar and a positioned container overlaying using stack YouTube](https://youtu.be/OJ3aAxt-HJs)

[ListView builder — video is on YouTube](https://youtu.be/1gqyNpQi2iU)

The test app is simple:

The app is a Scaffold with a Stack widget, the first child is a CustomScrollView with a generated Sliverlist, the second widget of the stack is a positioned container. 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

// Banner widget (dead simple and only using a test adUnitId for IOS)
class MdzBanner extends StatefulWidget {
  final String contentUrl;
  final bool borders;
  final Map<dynamic, dynamic> block;
  const MdzBanner({Key key, this.contentUrl, this.block, this.borders = true})
      : super(key: key);

  @override
  _MdzBannerState createState() => _MdzBannerState(contentUrl: this.contentUrl);
}

class _MdzBannerState extends State<MdzBanner> {
  final contentUrl;
  _MdzBannerState({this.contentUrl});
  BannerAd myBanner;

  @override
  void initState() {
    String adUnitId = 'ca-app-pub-3940256099942544/2934735716';

    myBanner = BannerAd(
      adUnitId: adUnitId,
      size: AdSize.mediumRectangle,
      request: AdRequest(contentUrl: this.contentUrl),
      listener: BannerAdListener(),
    );
    myBanner.load();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.only(top: 30, bottom: 0),
      alignment: Alignment.center,
      child: Column(children: [
        Container(
            width: myBanner.size.width.toDouble(),
            height: myBanner.size.height.toDouble(),
            child: AdWidget(ad: myBanner)),
        Padding(
          padding: const EdgeInsets.only(top: 5, bottom: 12.0),
          child: Text(
            'Реклама',
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Color.fromRGBO(148, 148, 148, 1),
            ),
          ),
        )
      ]),
    );
  }
}

// The test app
class TestAdmobScaf extends StatelessWidget {
  const TestAdmobScaf({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Stack(
      children: [
        customScrollViewBody(),
        // simpleListViewBody(),
        Positioned(
            bottom: 0,
            height: 80,
            left: 0,
            right: 0,
            child: Container(
                alignment: Alignment.center,
                color: Colors.black,
                child: Text(
                  'This is a positioned on top of custom scroll view',
                  style: TextStyle(color: Colors.white),
                )))
      ],
    ));
  }

  customScrollViewBody() {
    return CustomScrollView(
      slivers: [
        SliverAppBar(
          backgroundColor: Colors.black,
          title: Text(
            'A floating sliver app bar',
            style: TextStyle(color: Colors.white),
          ),
          floating: true,
        ),
        SliverList(
          delegate: SliverChildBuilderDelegate(
            (BuildContext context, int index) {
              if (index == 10) {
                return MdzBanner();
              }

              return Card(
                margin: EdgeInsets.all(15),
                child: Container(
                  color: Colors.blue[100 * (index % 9 + 1)],
                  height: 80,
                  alignment: Alignment.center,
                  child: Text(
                    "Item $index",
                    style: TextStyle(fontSize: 30),
                  ),
                ),
              );
            },
            childCount: 1000, // 1000 list items
          ),
        ),
      ],
    );
  }

  simpleListViewBody() {
    return ListView.builder(
        itemBuilder: (context, index) {
          if (index == 10) {
            return MdzBanner();
          }

          return Card(
            margin: EdgeInsets.all(15),
            child: Container(
              color: Colors.blue[100 * (index % 9 + 1)],
              height: 80,
              alignment: Alignment.center,
              child: Text(
                "Item $index",
                style: TextStyle(fontSize: 30),
              ),
            ),
          );
        },
        itemCount: 100);
  }
}

```
</details>

The bleed is visible both on a sliver app bar with a floating property and on the positioned widget.

I also tried using the Listview.builder (just in case) and the same bug is visible.

```
flutter doctor -v
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)

• No issues found!

```

I also found a similar issue here (https://github.com/flutter/flutter/issues/61340) that looks like mine.

This is a quite a glitchy (not sure if this word exists) experience for a user and it prevents us using this plugin in production for monetizing the app.

**Comment by jesteracer** [comment] 2021-07-09 08:39
There is a "workaround" — not to constrain the banner with a width (like in my example) — this way the left and right border will not be "visible" since they will be near device real borders. But the webview part (the banner with a content) will be rendered on an html with a black background and it will only work (design wise) in scenarios where everything is "black". 

But it will not help the top/bottom border
![IMAGE 2021-07-09 11:38:54](https://user-images.githubusercontent.com/823333/125050008-3e58c800-e0aa-11eb-9cf9-8c2323fb1c60.jpg)

**Comment by jesteracer** [comment] 2021-07-09 08:46
And another workaround that will work only in certain design scenarios — if a scaffold backgroundColor is the same as a color of an overlayed widget and they are both dark you can almost get away with the bleed.

**Comment by pynner** [comment] 2021-07-09 18:45
+1 on this, from flutter links looks like a UIKit bug, this is a killer bug for me when I open a menu and the ad below is bleeding on top :/

**Comment by maheshmnj** [comment] 2021-08-17 13:10
Hi @jesteracer Thanks for filing the issue, Could you please share on which device are you facing this issue? I ran your code sample on the latest stable and the master channel on Xiaomi k20 Pro (Android 11) and I could not reproduce the issue.

https://user-images.githubusercontent.com/31410839/129731415-445233ba-1a0d-46f6-9cdc-4617c4e3298d.mov


<details>
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.2.3 at /Users/mahesh/Documents/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2
      20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```

```console
[✓] Flutter (Channel master, 2.5.0-7.0.pre.8, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.5.0-7.0.pre.8 at /Users/mahesh/Documents/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 40e8620a27 (7 days ago), 2021-08-06 09:14:50 +0430
    • Engine revision 431ac604da
    • Dart version 2.14.0 (build 2.14.0-383.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (4 available)
    • iPhone 12 Pro Max (mobile) • 5430F628-A903-402C-A635-D55D7E6EEFCA • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 11.5.2
      20G95 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      92.0.4515.131

• No issues found!
```
</details>


Thank you.

**Comment by jesteracer** [comment] 2021-08-17 13:21
Hey @maheshmnj,

this issue can be seen only on a real iOS device — I checked it on my iPhone 12 mini, I checked on a variety of simulators (iOS) and on a simulator it can not be seen. I checked on all my Android phones and on them — everything is great — so the issue is only with iPhones. 

Also, when I tried to capture this bug on a real device using a native screen capture the bug just disappeared — that is why on the original issue post the video is captured using another phone.

PS. It looks like it is a bug with web view implementation

**Comment by TahaTesser** [comment] 2021-08-18 14:16
Hi @jesteracer 
This is a known Flutter platform view issue, check out https://github.com/flutter/flutter/issues/61340, not a bug `google_mobile_ads` itself.
This only reproduces on certain layouts and screenshots, doesn't reproduce on XR when running minimal code samples with just a banner on the screen.

Closing, as this isn't an issue with `google_mobile_ads` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-08-18 14:16 UTC
Labels: in triage
