### ISSUE TITLE
Actions in alertdialog are transparent when using banner as content for alert dialog

### ISSUE THREAD

**Issue by Junaidhassan99** [googleads/googleads-mobile-flutter#479] opened 2022-01-02 12:49 UTC
When I use a banner inside an alert dialog, the action widget become transparent

....

```

 final BannerAd _bannerAdForExitDialog = BannerAd(
    adUnitId: Constants.getBannerAdUnit,
    size: AdSize.mediumRectangle,
    request: const AdRequest(),
    listener: BannerAdListener(
      onAdFailedToLoad: (ad, error) {
        ad.dispose();
      },
    ),
  );

```

.....

```

@override
  void initState() {
    super.initState();

    _bannerAdForExitDialog.load();
  }

```

.... 

```

  TextStyle _getActionTextStyle() {
    return const TextStyle(fontSize: 18, color: Colors.red);
  }

```

....

```

 AlertDialog(
          title: const Text(
            "Do you want to exit?",
            style: TextStyle(color: Colors.black),
          ),
          content: Container(
            alignment: Alignment.center,
            color: Colors.transparent,
            height: _bannerAdForExitDialog.size.height.toDouble(),
            width: _bannerAdForExitDialog.size.width.toDouble(),
            child: AdWidget(ad: _bannerAdForExitDialog),
          ),
          actions: [
            TextButton(
              //onPressed: () => exit(0),
              onPressed: () => print('yes'),
              child: Text(
                'Yes',
                style: _getActionTextStyle(),
              ),
            ),
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: Text(
                'No',
                style: _getActionTextStyle(),
              ),
            ),
          ],
        );

```

.....

Here is the output. Even if I have assigned red color to 'yes' and 'no' text buttons the color is still transperent

![Untitled design](https://user-images.githubusercontent.com/61021884/147876198-379d2dec-344f-42ef-a6c2-b54c5f9ae888.png)

**Comment by maheshmnj** [comment] 2022-01-03 12:35
Hi @Junaidhassan99, Thanks for filing the issue. Is this issue only with ads or without the ads too? if the latter this issue must be filed in the flutter repo https://github.com/flutter/flutter/.

In former, Please share your output of `flutter doctor -v` the version of the ads plugin, and a minimal and complete code sample that can be directly run.

Thanks

**Comment by Junaidhassan99** [comment] 2022-01-03 13:12
> Hi @Junaidhassan99, Thanks for filing the issue. Is this issue only with ads or without the ads too? if the latter this issue must be filed in the flutter repo https://github.com/flutter/flutter/.
> 
> In former, Please share your output of `flutter doctor -v` the version of the ads plugin, and a minimal and complete code sample that can be directly run.
> 
> Thanks

Yes Sir, this issue is only with ads

**Comment by maheshmnj** [comment] 2022-01-06 13:26
Hi, I am unable to reproduce the issue. Please share the output of `flutter doctor -v` and verify with the below code sample.

<img src="https://user-images.githubusercontent.com/31410839/148389462-275c0f73-ab63-440d-8099-aefe22b8e177.png" width ="300">


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(BannerApp());
}

class BannerApp extends StatelessWidget {
  const BannerApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: BannerSample1());
  }
}

class BannerSample1 extends StatefulWidget {
  const BannerSample1({Key? key}) : super(key: key);

  @override
  _BannerSample1State createState() => _BannerSample1State();
}

class _BannerSample1State extends State<BannerSample1> {
  late BannerAd _bannerAd;
  bool isAdloaded = false;

  @override
  void initState() {
    super.initState();
    _bannerAd = BannerAd(
      adUnitId: BannerAd.testAdUnitId,
      size: AdSize.banner,
      request: AdRequest(),
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          print('$BannerAd loaded.');
          setState(() {
            isAdloaded = true;
          });
        },
      ),
    );
    _bannerAd.load();
  }

  Widget dialog() {
    return AlertDialog(
      title: Text('Exit App'),
      content: Container(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              'Are you sure you want to exit app?',
              style: TextStyle(fontSize: 20),
            ),
            Container(
              color: Colors.red,
              child: SizedBox(
                width: _bannerAd.size.width.toDouble(),
                height: _bannerAd.size.height.toDouble(),
                child: AdWidget(ad: _bannerAd),
              ),
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          child: Text(
            'Yes',
            style:
                TextStyle(color: Theme.of(context).primaryColor, fontSize: 16),
          ),
          onPressed: () => Navigator.of(context).pop(true),
        ),
        TextButton(
          child: Text(
            'No',
            style:
                TextStyle(color: Theme.of(context).primaryColor, fontSize: 16),
          ),
          onPressed: () => Navigator.of(context).pop(false),
        ),
      ],
    );
  }

  @override
  void dispose() {
    // TODO: implement dispose
    _bannerAd.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Banner Ad')),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Center(
            child: ElevatedButton(
                onPressed: () {
                  showDialog(
                    context: context,
                    builder: (BuildContext context) {
                      return dialog();
                    },
                  );
                },
                child: Text('show dialog')),
          ),
        ],
      ),
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```dart
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>

**Comment by maheshmnj** [comment] 2022-01-11 13:32
Duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/485

**Closed by maheshmnj** 2022-01-11 13:32 UTC
Labels: feedback required, in triage
