### ISSUE TITLE
Ad failed to load: LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No ad config.... In production version only

### ISSUE THREAD

**Issue by sgshivamgarg8** [googleads/googleads-mobile-flutter#331] opened 2021-08-04 14:46 UTC
I am getting this Ad failed to load error: 3 in my app while using real ad ids in production.

1. Test ads are working fine.
2. Admob account has no issues.
3. Ads are working fine when I created a release apk and installed on my physical device.
4. But when I updated it in play store and downloaded from play store, it is not showing any ads, but on same device if I open the version which I installed from apk, it shows ads (real not test ads).

I am not sure what is the issue here, please help.

**Comment by VoidElle** [comment] 2021-08-04 15:03
I have the same issue.

**Comment by VoidElle** [comment] 2021-08-04 15:12
Just checked the issues list, it's a duplicate of #296

**Comment by sgshivamgarg8** [comment] 2021-08-04 15:14
> Just checked the issues list, it's a duplicate of #296

It might be but that issue didnt mention that ads are working on manually created apk but not on production version.

**Comment by sgshivamgarg8** [comment] 2021-08-05 04:31
Issue #59 also seems to be the same. I am surprised it is more than 4 months old and it isn't closed yet.
#212 also looks same issue.

None of these are closed yet.

**Comment by TahaTesser** [comment] 2021-08-05 14:47
Hi @sgshivamgarg8 
This seems to be a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/59
Please upvote the duplicate issue, closing

**Closed by TahaTesser** 2021-08-05 14:47 UTC
Labels: in triage
