### ISSUE TITLE
[Android]AppOpen ads and interstitial ads affect the status bar style in version 5.0.0. 

### ISSUE THREAD

**Issue by ruiyong-lee** [googleads/googleads-mobile-flutter#1039] opened 2024-03-27 12:38 UTC
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/flutter/quick-start),
   send your feedback by pressing the **Send Feedback** button at the top right of the
   documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

---

## Plugin Version
v5.0.0

### [REQUIRED] Step 2: Describe the problem
When I use the v5.0.0 version of the plug-in, after displaying AppOpen ads or Interstitial ads, the status bar turns black when I return to the app.
Version v4.0.0 does not have this problem.

## Steps to Reproduce

1. Open the app and display the AppOpen ad.
2. Turn off screen-opening ads.
3. Then switch the application to the background.
4. Open the application again.

**Expected results:** 
The status bar maintains its original style.

**Actual results:** 
The status bar background color changes to black.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

Record screen:
[o061s-zyoyu.webm](https://github.com/googleads/googleads-mobile-flutter/assets/12726826/e4029340-1ecd-4902-b24e-64aa5b815a5b)

**Comment by malandr2** [comment] 2024-03-27 17:33
Hey @ruiyong-lee, we are currently working on a fix for AppOpen and Interstitial ads https://github.com/googleads/googleads-mobile-flutter/issues/1013 that may inherently fix this as well. Will check to see if that's the case

**Comment by ruiyong-lee** [comment] 2024-03-28 05:14
@malandr2 Thank you for your reply. I saw that this issue appeared in version v4.0.0, and it was a bug that prevented advertisements from going full screen. But my problem is that it works fine in version v4.0.0. When using version v5.0.0, after the ads are turned off, the immersive status bar is affected by the ads and a black status bar appears.

**Comment by malandr2** [comment] 2024-03-29 15:59
Thanks @ruiyong-lee, I've shared this engineering to take a closer look.

**Comment by LTPhantom** [comment] 2024-03-29 22:14
Hello @ruiyong-lee, could you share more information regarding this issue? It would help figure it out. I want to know if it happens on any device and/or API levels.

**Comment by ruiyong-lee** [comment] 2024-04-02 09:29
@LTPhantom 
flutter: 3.16.9 or 3.19.4
Divice: 
1.Galaxy A53 5G UW (API33)
2.Simulator Pixel 7 Pro API30
3.Simulator Pixel 7 Pro API34

**Comment by ruiyong-lee** [comment] 2024-04-02 09:50
Video：
https://github.com/googleads/googleads-mobile-flutter/assets/12726826/9eb7abbb-eb27-4aae-842c-d7c57eb32c4e

**Comment by alihassan143** [comment] 2024-04-04 05:36
facing same issue

**Comment by devchenli** [comment] 2024-04-07 04:10
same issue ,  when interstital ads showed , the app status bar became black !!!

**Comment by lhdio** [comment] 2024-04-09 11:53
same issue.

**Comment by FernandoUFS** [comment] 2024-04-16 14:05
Having the same issue here.

**Comment by malandr2** [comment] 2024-04-16 21:54
The engineering is looking into this and working on a fix. Thanks all.

**Comment by LTPhantom** [comment] 2024-04-24 22:02
Hello I have been trying to replicate the issue without luck, @ruiyong-lee could it be possible to share a code sample with the issue?

**Comment by ruiyong-lee** [comment] 2024-04-26 09:29
@LTPhantom Set a transparent status bar.
`WidgetsBinding.instance.addPostFrameCallback((_) {
      SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarBrightness: Brightness.dark,
        statusBarIconBrightness: Brightness.light,
        systemNavigationBarColor: Colors.white,
      ));
    });`

**Comment by lunasoft79** [comment] 2024-04-27 06:56
same issue.

**Comment by malandr2** [comment] 2024-04-27 18:23
@all

For those replying same issue, can you provide a [minimum reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example)? This will help engineering debug (https://github.com/googleads/googleads-mobile-flutter/issues/1039#issuecomment-2075919511)

Thanks!

**Comment by ruiyong-lee** [comment] 2024-04-28 05:38
Oh my god, I found this incredible reason. This problem will occur as long as this library is introduced.
`implementation 'com.blankj:utilcodex:1.31.1'`

**Comment by ruiyong-lee** [comment] 2024-04-29 08:02
I removed this plug-in, but this bug still occurs during hot reloading occasionally, so you can use this plug-in to see if there is any problem. After all, this will not happen in version 4.0.0.

**Comment by malandr2** [comment] 2024-04-29 13:33
@ALL 

If you are using `implementation 'com.blankj:utilcodex:1.31.1'` can you confirm the issue can no longer be reproduced when removed?

If you not using `implementation 'com.blankj:utilcodex:1.31.1'` and the issue can still be reproduced, can your provide a minimum reproducible sample?

**Comment by devchenli** [comment] 2024-04-30 02:58
> @ALL
> 
> If you are using `implementation 'com.blankj:utilcodex:1.31.1'` can you confirm the issue can no longer be reproduced when removed?
> 
> If you not using `implementation 'com.blankj:utilcodex:1.31.1'` and the issue can still be reproduced, can your provide a minimum reproducible sample?

It seems like the latest version of Flutter has fixed this issue. I'm not sure if it's an AdMob plugin issue or a Flutter issue. Three weeks ago, I was using Flutter version stable-3.19.4, and the status bar would turn black every time an interstitial ad was displayed. However, when I updated to the latest stable version-3.19.6, this issue is no longer present.

**Comment by iskamal** [comment] 2024-05-01 20:09
I have updated Flutter to 3.19.6 and the problem is still there. 

Once I reopen the app from the background and the App-open-ad appears, the status bar turns black and the page shifts up.
While in an emulator it turns back to normal with the closure of the app open. in real devices, it stays there.
The code that was used is exactly like https://developers.google.com/admob/flutter/app-open with the exception of removing  the line "orientation: AppOpenAd.orientationPortrait,"
Hope my comment helps

**Comment by malandr2** [comment] 2024-05-02 14:43
@iskamal what device and OS are you on?

**Comment by iskamal** [comment] 2024-05-02 15:14
@malandr2 For real device is S20+ Android 13, also saw it on an older device with an older Android version.

for Emulators, pretty much all from Android 11 up to 14. but it returns to normal right after the closure of the app-open Ad

below are the screenshots of what happens to the status bar and SliverAppBar() before and after the app-open ad appears on a real device

![Screenshot_20240502_180519](https://github.com/googleads/googleads-mobile-flutter/assets/101970408/9dbd9b3a-258a-4c7f-ba58-92c906b8a37f)
![Screenshot_20240502_180530](https://github.com/googleads/googleads-mobile-flutter/assets/101970408/0df8f2ac-24cc-42d5-b0bd-2a469d2745de)

**Comment by ClebsonDantasUchoa** [comment] 2024-05-03 19:38
The same problem occurs here using version 5.0.0.

After displaying the App Open Ad it is not possible to change the color of the Status Bar, the following code does not work after displaying the App Open Ad:

```
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light.copyWith(
        statusBarColor:  Colors.red,
        statusBarBrightness: Brightness.light,
        statusBarIconBrightness: Brightness.dark
      ));
```


https://github.com/googleads/googleads-mobile-flutter/assets/39413696/3956e986-f174-428b-90b2-bc65662eac2e

**Comment by ClebsonDantasUchoa** [comment] 2024-05-03 19:46
The same problem occurs here using version 5.0.0.

After displaying the App Open Ad it is not possible to change the color of the Status Bar, the following code does not work after displaying the App Open Ad:

```
SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle.light.copyWith(
        statusBarColor:  Colors.red,
        statusBarBrightness: Brightness.light,
        statusBarIconBrightness: Brightness.dark
      ));
```
      
Device: Samsung Galaxy A72 - SM-A725M/DS

**Comment by LTPhantom** [comment] 2024-05-03 21:41
Thanks everyone for sharing more info. I want to nail down exactly what could everyone have in common to find the root cause of this issue.

These are my thoughts so far:
* This might not be a device related issue nor an android version related problem since it seems to happen on [real devices](https://github.com/googleads/googleads-mobile-flutter/issues/1039#issuecomment-2090783132) and [emulators](https://github.com/googleads/googleads-mobile-flutter/issues/1039#issuecomment-2031512628) on all kind of API numbers.
* Given the screenshots and videos shared, this seems to be related to the way the Flutter apps are built, so I would like to get more information related to the app constitution:
  * Am I right to believe that you don't use the `AppBar` widget?
  * Similar to this [comment](https://github.com/googleads/googleads-mobile-flutter/issues/1039#issuecomment-2093664881), are there any theme configuration done? Either direct Android theme xml configuration, or dart theme values that are related to the status bar that could be related to the issue?
  * Is minimizing and returning to the app a necessary step to reproduce this issue or does it happen right after closing the app open ad? Does the same happen if the phone screen is turned off and then back on?
* If anyone could share a minimum code app with this issue, that would be extremely helpful since even with the sample mentioned [here](https://github.com/googleads/googleads-mobile-flutter/issues/1039#issuecomment-2089056384), I am not able to get the same behavior.

**Comment by ruiyong-lee** [comment] 2024-05-10 08:36
@LTPhantom I found the steps that will surely lead to the bug and provided a demo. This seems to be related to video-type native ads. Once a video-type native ad is displayed, the status bar turns black. Image-type native ads do not have this problem. But the new 5.1.0 version seems to have fixed this bug.
demo：[https://github.com/ruiyong-lee/test_google_ad](https://github.com/ruiyong-lee/test_google_ad)

**Comment by malandr2** [comment] 2024-05-10 16:14
> But the new 5.1.0 version seems to have fixed this bug.

Can others confirm if this cannot be replicated with 5.1.0?

**Comment by iskamal** [comment] 2024-05-11 21:11
Yes, after updating to  5.1.0 the bug no longer appears

**Comment by lunasoft79** [comment] 2024-05-12 02:35
I still have the same error using version 5.1.0, attached is an image showing it.

![Screenshot_20240511_193406](https://github.com/googleads/googleads-mobile-flutter/assets/29025074/cc698b91-e198-4657-872d-a092172bd919)

**Comment by GeceGibi** [comment] 2024-05-12 11:44
> Yes, after updating to 5.1.0 the bug no longer appears

Yeah same here. Black status bar bug is not seems like fixed after 5.1.0.

**Comment by malandr2** [comment] 2024-05-14 01:21
@all 

Can others confirm? If no one can reproduce the issue on version 5.1.0 I'll close this issue out. Will keep it open for a few days.

**Comment by alihassan143** [comment] 2024-05-14 06:25
![Screenshot_1715666531](https://github.com/googleads/googleads-mobile-flutter/assets/71745182/56b60355-2dcc-4de0-9e06-fe86985d0d28)
5.1.0
showing white bar its shold show full screen not background white bar

**Comment by malandr2** [comment] 2024-05-14 14:36
Hi @alihassan143 that is working as intended. 

I tested this behavior using our [Android Interstitial example](https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/InterstitialExample) and the ad does not cover the notch. 

![Screenshot_1715697287](https://github.com/googleads/googleads-mobile-flutter/assets/5905170/3d98022c-6895-4407-8633-088d28aedbd6)

**Closed** 2024-05-28 15:43 UTC
Labels: interstitial ad, app open ad

**Comment by rahsuttushar** [comment] 2024-08-02 08:23
This issue is still present `google_mobile_ads: ^5.1.0.`

**Comment by IMHitesh** [comment] 2024-10-09 08:38
This issue is still present google_mobile_ads: ^5.1.0.

**Comment by Jigneshiosdeveloper** [comment] 2024-10-22 03:48
I am using google_mobile_ads: 5.1.0 in my Flutter app. It is working fine for both platforms (Android and iOS). You can see the output of Android and iOS devices. I implemented [**app open ads**](https://fluttertutorialhub.com/admob/app-open-ads-admob-flutter-example/) in my Flutter project.

**Comment by aykutuludag** [comment] 2024-10-22 20:49
This issue is still present google_mobile_ads: ^5.2.0.

**Sceneario**
As general the other apps, I am showing interstitial ads between screen changes. Here is my code:

InterstitialAd? fullPageAd;

// load interstitial codes

```
Future<void> showInterstitialAd(
    BuildContext context, void Function() changeScreen) async {
  if (fullPageAd == null || isPremiumUser) {
    changeScreen();
    return;
  }

  WidgetsBinding.instance.addPostFrameCallback((_) async {
    if (fullPageAd != null) {
      fullPageAd!.fullScreenContentCallback = FullScreenContentCallback(
        onAdShowedFullScreenContent: (InterstitialAd ad) => {
          adCount++,
          createInterstitialAd(),
          FirebaseAnalytics.instance.logEvent(
            name: "interstitialSHOW",
          ),
          if (adCount == 2)
            {
              Fluttertoast.showToast(
                  msg: AppLocalizations.of(context).lastAd,
                  toastLength: Toast.LENGTH_SHORT,
                  gravity: ToastGravity.CENTER,
                  timeInSecForIosWeb: 1,
                  backgroundColor: Colors.transparent,
                  textColor: Colors.white,
                  fontSize: 16.0),
            },
        },
        onAdDismissedFullScreenContent: (InterstitialAd ad) {
          ad.dispose();
        },
        onAdFailedToShowFullScreenContent: (InterstitialAd ad, AdError error) {
          ad.dispose();
          createInterstitialAd();
          FirebaseAnalytics.instance.logEvent(
            name: "interstitialFAILSHOW",
            parameters: {
              "errorReason": error.message,
            },
          );
        },
      );
      await fullPageAd!.show();
      fullPageAd = null;
    }
  });

  changeScreen();
}
```

```
Future<void> changeScreen() async {
    await Navigator.push(
      context,
      MaterialPageRoute(
          builder: (context) => SecondScreen()),
    );
}
```
Thanks to firebase logs i can see how many device can trigger the **onAdFailedToShowFullScreenContent**

![image](https://github.com/user-attachments/assets/8e759539-0db8-49d5-8b32-4270b90a5f15)

As you can see if the device is Android errorReason is **The ad can not be shown when app is not in foreground.**. If it is iOS, **the provided view controller is not being presented.**

Adding **WidgetsBinding.instance.addPostFrameCallback** reduced the errors but it is still continuing. Google should fix this because it is almost reduces incomes significantly. Kind regards.

**Comment by Azzeccagarbugli** [comment] 2024-12-12 14:41
The issue still seems to be here, I'm on `5.2.0` version 🥲

**Comment by danoa-software** [comment] 2024-12-12 15:00
Hi guys, I found a workaround! My app passed Admob review.

Call the "hideStatusBar()" method before displaying your Interstitial or Rewarded Ad and then call the "restoreStatusBar()" method after the ad is closed or if it fails to display.

```
import 'package:flutter/services.dart';

abstract class StatusBarController {

  static Future<void> restoreStatusBar() async {
    try {
      await SystemChrome.setEnabledSystemUIMode(
        SystemUiMode.manual,
        overlays: SystemUiOverlay.values
      );
    } catch(_) {
    }
  }

  static Future<void> hideStatusBar() async {
    try {
      await SystemChrome.setEnabledSystemUIMode(
        SystemUiMode.manual,
        overlays: []
      );
    } catch(_) {
    }
  }

}
```

**Comment by istiaksaif** [comment] 2025-05-17 10:56
> **Issue: Fullscreen interstitial ads affected by Android 15's edge-to-edge enforcement**
>
> On **Android 15 (API 35)**, fullscreen ads (such as interstitials) may experience **UI content being overlapped by the status or navigation bars** due to the new **edge-to-edge rendering behavior** enforced by default.
>
> To resolve this, we recommend **opting out of this enforcement** by adding the following attribute to the ad activity theme in `styles.xml`:
>
> ```xml
> <resources xmlns:tools="http://schemas.android.com/tools">
>
>     <style name="AdActivityTheme" parent="Theme.AppCompat.Light.NoActionBar.FullScreen">
>         
>         <item name="android:windowDrawsSystemBarBackgrounds">true</item>
>         <item name="android:statusBarColor">@android:color/transparent</item>
>
>         
>         <item name="android:windowOptOutEdgeToEdgeEnforcement" tools:targetApi="35">true</item>
>     </style>
>
> </resources>
> ```
>
> ⚠️ Please make sure the `tools` namespace is declared at the top of the file:
>
> ```xml
> <resources xmlns:tools="http://schemas.android.com/tools">
> ```
>
> This will ensure consistent and safe display of ads across all Android versions, particularly Android 15 and above.

👉 **Please add this fix to the respective ad activity themes in the Google Mobile Ads SDK library. Once added there, it should solve the layout issue for developers automatically.**

---
