### ISSUE TITLE
iOS Build Error: Showing Recent Errors Only Linker command failed with exit code 1

### ISSUE THREAD

**Issue by ARE-DEV00** [googleads/googleads-mobile-flutter#1187] opened 2024-10-10 00:32 UTC
I have imported google_mobile_ads: ^5.2.0, and the Android project builds successfully, but the iOS project fails to build. If I remove google_mobile_ads, the iOS project builds without issues.

The error in the iOS project is as follows:

<img width="444" alt="스크린샷 2024-10-10 오전 9 32 33" src="https://github.com/user-attachments/assets/f4b82ead-6aa3-4d0a-ab24-290e4f7f5b40">

**Linker command failed with exit code 1 (use -v to see invocation)**

-o /Users/shshsh/Library/Developer/Xcode/DerivedData/Runner-assddkxkrcxmqqdbuzvqhkoiualw/Build/Products/Debug-iphonesimulator/Runner.app/Runner

ld: warning: Could not find or use auto-linked library 'swiftXPC': library 'swiftXPC' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'MarketplaceKit': framework 'MarketplaceKit' not found
ld: Undefined symbols:
  enum case for MarketplaceKit.AppDistributor.testFlight(MarketplaceKit.AppDistributor.Type) -> MarketplaceKit.AppDistributor, referenced from:
      l007 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
      l008 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
  enum case for MarketplaceKit.AppDistributor.marketplace(MarketplaceKit.AppDistributor.Type) -> (Swift.String) -> MarketplaceKit.AppDistributor, referenced from:
      l007 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
      l008 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
  enum case for MarketplaceKit.AppDistributor.other(MarketplaceKit.AppDistributor.Type) -> MarketplaceKit.AppDistributor, referenced from:
      l007 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
      l008 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
  static MarketplaceKit.AppDistributor.current.getter : MarketplaceKit.AppDistributor, referenced from:
      function signature specialization <Arg[0] = Dead> of static GoogleMobileAds.GADMarketplaceKitSignals.appDistributor() async -> Swift.String in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
  async function pointer to static MarketplaceKit.AppDistributor.current.getter : MarketplaceKit.AppDistributor, referenced from:
      function signature specialization <Arg[0] = Dead> of static GoogleMobileAds.GADMarketplaceKitSignals.appDistributor() async -> Swift.String in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
  enum case for MarketplaceKit.AppDistributor.appStore(MarketplaceKit.AppDistributor.Type) -> MarketplaceKit.AppDistributor, referenced from:
      l007 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
      l008 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
  type metadata accessor for MarketplaceKit.AppDistributor, referenced from:
      l007 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
      l008 in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
  nominal type descriptor for MarketplaceKit.AppDistributor, referenced from:
      _symbolic _____Sg 14MarketplaceKit14AppDistributorO in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
  __swift_FORCE_LOAD_$_swiftXPC, referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_GoogleMobileAds in GoogleMobileAds[arm64][398](GADMarketplaceKitSignals.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols:

Linker command failed with exit code 1 (use -v to see invocation)

**Comment by peterweb2005** [comment] 2024-10-10 10:09
https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/issues/339
the solution is to upgrade xcode to 15.3
but not everyone can

**Comment by malandr2** [comment] 2024-10-11 14:10
Duplicate of #1185:

Plugin version 5.2.0 uses iOS Google Mobile Ads SDK [11.10.0](https://developers.google.com/admob/ios/rel-notes) which requires >= Xcode 15.3. Updating your Xcode should resolve the issue.

**Closed by malandr2** 2024-10-11 14:10 UTC
