### ISSUE TITLE
android API 29 quits on loading any ads except for test ones

### ISSUE THREAD

**Issue by Fima2003** [googleads/googleads-mobile-flutter#998] opened 2024-01-22 09:40 UTC
Hello support team, I am using VS code on mac m1 to integrate ads in my application. Until recently during testing it worked perfectly, and now it stopped. And initially I thought the problem was with my admob app or ad unit, so I changed the first one, the second one, but nothing worked. the same behaviour(full error later). on API 34 it doesn't crash, but it still doesn't show the ad, whilst on API 29 it crashes, the app stops working. My implementation is simple. It is similar to the implementation of [Flutter game template](https://github.com/flutter/samples/tree/main/game_template/lib/src/ads), but with interstitial land rewarded ads.

```
adsController = context.read<AdsController?>();
adsController?.preloadInterstitialAd();
```

```
void preloadInterstitialAd() {
    _preloadedInterstitialAd =
        PreloadedInterstitialAd(adUnitId: adInterstitialUnitId);

    Future<void>.delayed(const Duration(seconds: 1)).then((_) {
      return _preloadedInterstitialAd?.load();
    });
  }
```

```
class PreloadedInterstitialAd {
  static final _log = Logger('PreloadedInterstitialAd');
  final String adUnitId;
  InterstitialAd? _interstitialAd;

  final _adCompleter = Completer<InterstitialAd>();

  PreloadedInterstitialAd({
    required this.adUnitId,
  });

  Future<InterstitialAd> get ready => _adCompleter.future;

  Future<void> load() {
    return InterstitialAd.load(
      adUnitId: adUnitId,
      request: const AdRequest(),
      adLoadCallback: InterstitialAdLoadCallback(
        onAdLoaded: (InterstitialAd ad) {
          ad.fullScreenContentCallback = FullScreenContentCallback(
              // Called when the ad showed the full screen content.
              onAdShowedFullScreenContent: (ad) {},
              // Called when an impression occurs on the ad.
              onAdImpression: (ad) {},
              // Called when the ad failed to show full screen content.
              onAdFailedToShowFullScreenContent: (ad, err) {
                ad.dispose();
              },
              // Called when the ad dismissed full screen content.
              onAdDismissedFullScreenContent: (ad) {
                ad.dispose();
              },
              // Called when a click is recorded for an ad.
              onAdClicked: (ad) {});

          // Keep a reference to the ad so you can show it later.
          _interstitialAd = ad;
        },
        // Called when an ad request failed.
        onAdFailedToLoad: (LoadAdError error) {
          // ignore: avoid_print
          print('InterstitialAd failed to load: $error');
        },
      ),
    );
  }

  void show() {
    _interstitialAd?.show();
  }

  void dispose() {
    _log.info('preloaded banner ad being disposed');
    _interstitialAd?.dispose();
  }
}
```

My plugin's version 4.0.0

The problem is that on devices with api less than 29 for any mobile ad apps I use except for the test ones, I get the following error:

```
W/m.rlabs.worder( 3657): Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
W/m.rlabs.worder( 3657): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
I/chatty  ( 3657): uid=10145(com.rlabs.wordera) ThreadPoolForeg identical 2 lines
W/m.rlabs.worder( 3657): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/CCodec  ( 3657): previous call to queue exceeded timeout
E/MediaCodec( 3657): Codec reported err 0x80000000, actionCode 0, while in state 6
D/SurfaceUtils( 3657): disconnecting from surface 0x77e32c4010, reason disconnectFromSurface
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
E/MediaCodecVideoRenderer( 3657): Video codec error
E/MediaCodecVideoRenderer( 3657):   java.lang.IllegalStateException
E/MediaCodecVideoRenderer( 3657):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/MediaCodecVideoRenderer( 3657):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
E/MediaCodecVideoRenderer( 3657):       at m.tf.b(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:6)
E/MediaCodecVideoRenderer( 3657):       at m.su.S(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:862)
E/MediaCodecVideoRenderer( 3657):       at m.yq.S(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:1)
E/MediaCodecVideoRenderer( 3657):       at m.ls.p(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:936)
E/MediaCodecVideoRenderer( 3657):       at m.ls.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:199)
E/MediaCodecVideoRenderer( 3657):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/MediaCodecVideoRenderer( 3657):       at android.os.Looper.loop(Looper.java:214)
E/MediaCodecVideoRenderer( 3657):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 3657): Playback error
E/ExoPlayerImplInternal( 3657):   m.jv: MediaCodecVideoRenderer error, index=1, format=Format(1, null, null, video/x-vnd.on2.vp9, null, -1, en, [358, 640, -1.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, NA, NA)], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal( 3657):       at m.ls.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:233)
E/ExoPlayerImplInternal( 3657):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 3657):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal( 3657):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 3657):   Caused by: m.yk: Decoder failed: c2.android.vp9.decoder
E/ExoPlayerImplInternal( 3657):       at m.yq.am(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:5)
E/ExoPlayerImplInternal( 3657):       at m.su.S(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:1271)
E/ExoPlayerImplInternal( 3657):       at m.yq.S(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:1)
E/ExoPlayerImplInternal( 3657):       at m.ls.p(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:936)
E/ExoPlayerImplInternal( 3657):       at m.ls.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:199)
E/ExoPlayerImplInternal( 3657):       ... 3 more
E/ExoPlayerImplInternal( 3657):   Caused by: java.lang.IllegalStateException
E/ExoPlayerImplInternal( 3657):       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
E/ExoPlayerImplInternal( 3657):       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
E/ExoPlayerImplInternal( 3657):       at m.tf.b(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:6)
E/ExoPlayerImplInternal( 3657):       at m.su.S(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:862)
E/ExoPlayerImplInternal( 3657):       ... 6 more
D/CCodecBuffers( 3657): [c2.android.aac.decoder#893:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 0
D/CCodecBuffers( 3657): [c2.android.aac.decoder#893:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 1
D/CCodecBuffers( 3657): [c2.android.aac.decoder#893:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 2
D/CCodecBuffers( 3657): [c2.android.aac.decoder#893:1D-Output.Impl[N]] Client returned a buffer it does not own according to our record: 3
W/Codec2Client( 3657): query -- param skipped: index = 1342179345.
W/Codec2Client( 3657): query -- param skipped: index = 2415921170.
W/Codec2Client( 3657): query -- param skipped: index = 1610614798.
E/ExoPlayerImplInternal( 3657): Disable failed.
E/ExoPlayerImplInternal( 3657):   java.lang.IllegalStateException
E/ExoPlayerImplInternal( 3657):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal( 3657):       at android.media.MediaCodec.flush(MediaCodec.java:2194)
E/ExoPlayerImplInternal( 3657):       at m.tf.g(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:3)
E/ExoPlayerImplInternal( 3657):       at m.su.aB(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:6)
E/ExoPlayerImplInternal( 3657):       at m.su.at(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:45)
E/ExoPlayerImplInternal( 3657):       at m.su.u(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:14)
E/ExoPlayerImplInternal( 3657):       at m.yq.u(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:10)
E/ExoPlayerImplInternal( 3657):       at m.jp.p(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:26)
E/ExoPlayerImplInternal( 3657):       at m.ls.o(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:25)
E/ExoPlayerImplInternal( 3657):       at m.ls.B(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:39)
E/ExoPlayerImplInternal( 3657):       at m.ls.L(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:14)
E/ExoPlayerImplInternal( 3657):       at m.ls.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:250)
E/ExoPlayerImplInternal( 3657):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 3657):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal( 3657):       at android.os.HandlerThread.run(HandlerThread.java:67)
W/Ads     ( 3657): Precache error
W/Ads     ( 3657): m.jv: MediaCodecVideoRenderer error, index=1, format=Format(1, null, null, video/x-vnd.on2.vp9, null, -1, en, [358, 640, -1.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, NA, NA)], [-1, -1]), format_supported=YES
W/Ads     ( 3657):      at m.ls.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:233)
W/Ads     ( 3657):      at android.os.Handler.dispatchMessage(Handler.java:103)
W/Ads     ( 3657):      at android.os.Looper.loop(Looper.java:214)
W/Ads     ( 3657):      at android.os.HandlerThread.run(HandlerThread.java:67)
W/Ads     ( 3657): Caused by: m.yk: Decoder failed: c2.android.vp9.decoder
W/Ads     ( 3657):      at m.yq.am(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:5)
W/Ads     ( 3657):      at m.su.S(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:1271)
W/Ads     ( 3657):      at m.yq.S(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:1)
W/Ads     ( 3657):      at m.ls.p(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:936)
W/Ads     ( 3657):      at m.ls.handleMessage(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:199)
W/Ads     ( 3657):      ... 3 more
W/Ads     ( 3657): Caused by: java.lang.IllegalStateException
W/Ads     ( 3657):      at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
W/Ads     ( 3657):      at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2789)
W/Ads     ( 3657):      at m.tf.b(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:6)
W/Ads     ( 3657):      at m.su.S(:com.google.android.gms.policy_ads_fdr_dynamite@234310605@234310602057.578924991.578924991:862)
W/Ads     ( 3657):      ... 6 more
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/AudioManager( 3657): dispatching onAudioFocusChange(-1) to android.media.AudioManager@501adb7xyz.luan.audioplayers.player.FocusManager$$ExternalSyntheticLambda0@b0d8a51
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 3657): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 3657): cleanDrmObj: mDrmObj=null mDrmSessionId=null
```
And then the UI is not responding. I expect it to work;)

to recreate get the example from [Example repo](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/interstitial_example)

`flutter analyze` output:

```
Analyzing multiplatform...                                              

   info • Don't invoke 'print' in production code • lib/main.dart:101:7 • avoid_print
   info • Empty catch block • lib/src/audio/audio_controller.dart:195:14 • empty_catches
   info • Don't invoke 'print' in production code • lib/src/crossword_generation_service/words.dart:72:5 • avoid_print
warning • Unused import: '../in_app_purchase/in_app_purchase.dart' • lib/src/play_session/play_level_screen.dart:19:8 • unused_import
   info • Empty catch block • lib/src/play_session/play_level_screen.dart:444:17 • empty_catches

5 issues found. (ran in 2.1s)
```

output of `flutter doctor -v`:

```
[✓] Flutter (Channel stable, 3.16.7, on macOS 14.2.1 23C71 darwin-arm64, locale en-UA)
    • Flutter version 3.16.7 on channel stable at /Users/fimarubin/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ef1af02aea (11 days ago), 2024-01-11 15:19:26 -0600
    • Engine revision 4a585b7929
    • Dart version 3.2.4
    • DevTools version 2.28.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/fimarubin/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 120.0.6099.234

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by malandr2** [comment] 2024-01-22 18:39
Hey @Fima2003, thank you for your inquiry. Given that the issue is only occurring on Android devices we suspect the issue is more closely related to the Android platform and not the google_mobile_ads flutter plugin. As a next step to directly address your concern, please create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) for it to be triaged appropriately. 

Closing this issue out. Thanks!

**Closed by malandr2** 2024-01-22 18:39 UTC
