### ISSUE TITLE
Flutter Anchored Adaptive Test Ad hides textfield until it reloads

### ISSUE THREAD

**Issue by DktPhl2019** [googleads/googleads-mobile-flutter#832] opened 2023-05-04 23:44 UTC
Hello!

I am working on a test ad in my app. I am running into the issue all the time. 

Issue: Flutter Anchored Adaptive Test Ad hides textfield until it reloads

When I start the app, things look fine meaning nothing is hidden.

Then, the textfield becomes hidden until a test ad is loaded, then the textfield is shown again.

I don't have a code to show hide a textfield.

When I remove the test ad, then the issue goes away.

I don't understand what is going on and how to fix the issue. 

I created Stackoverflow issue with all the details including the code: https://stackoverflow.com/questions/76177901/flutter-anchored-adaptive-test-ad-hides-textfield-until-it-reloads

Please note that the sample code shown is not the same code I actually use in my app.

I cannot share the code that I actually use.

I am using Windows 11 Android Studio Eel.
I am using google_mobile_ads: ^2.4.0

Flutter version: 3.7.0
Dart version: 2.19.0
Android Emulator: PIXEL XP API 33

Any feedback or suggestions will be appreciated.

Thank You

**Comment by huycozy** [comment] 2023-05-05 10:58
Hi @DktPhl2019 
I ran your sample code but can't see the issue on the latest plugin version and Flutter stable channel. The TextFields can be displayed normally before ad is loaded. 

https://user-images.githubusercontent.com/104349824/236440059-6edc53ea-4b14-4dd7-8f37-2a3ef0eaa514.mov

Could you provide a recorded video for this? 

Also, you may retry this on the latest plugin version and Flutter stable channel to see if it works or not. The latest ads plugin version is `google_mobile_ads: ^3.0.0` and Flutter stable `3.7.12`.

**Comment by DktPhl2019** [comment] 2023-05-05 13:48
Hello! I think you can close the issue for now. 
I was thinking that I added too many hidden buttons with setState on a single screen.
I cannot reproduce the issue in the original code and this example since I cannot come up with exact steps to reproduce. 
I have seen the issue happening. The issue does not seem to appear after I cleared Cashe on VM image. 
Thank You Very Much

**Comment by huycozy** [comment] 2023-05-08 12:05
Thanks for your response. Closing the issue since it's not reproducible anymore.

**Closed by huycozy** 2023-05-08 12:05 UTC
Labels: in triage
