### ISSUE TITLE
Ad close button is in SafeArea

### ISSUE THREAD

**Issue by Tutorialwork** [googleads/googleads-mobile-flutter#611] opened 2022-07-24 09:17 UTC
## Plugin Version

1.3.0

## Steps to Reproduce

1. Show an interstitial ad

**Expected results:**

A close button that is not in the safe area.

**Actual results:**

[Actual results](https://i.imgur.com/Kvga0Ph.png)

<details>
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale de-DE)
    • Flutter version 3.0.5 at /Users/manuel/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (11 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/manuel/Library/Android/sdk
    • Platform android-31, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 66.0.3
    • Dart plugin version 213.7306

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • C0453790-3ACC-49F9-AD50-D229C66B81A4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 103.0.5060.134
    ! Error: iPhone von Manuel is busy: Making iPhone von Manuel ready for development. Xcode will continue when iPhone von Manuel is finished. (code -10)
    ! Error: iPhone von Manuel Schuler is not connected. Xcode will continue when iPhone von Manuel Schuler is connected. (code -13)
    ! Error: iPad von Manuel (2) is not connected. Xcode will continue when iPad von Manuel (2) is connected. (code -13)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
</details>

**Comment by huycozy** [comment] 2022-07-25 03:45
Hi @Tutorialwork 
I can not reproduce the issue on the latest `stable` and `master` channels with sample code [google_mobile_ads/example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)
The ad close button of interstitial ad is shown inside SafeArea as expected.

Tested on iOS emulator: iPhone 13, iOS 15.4
google_mobile_ads: ^1.3.0

<details>
<summary>Demo</summary>

<img width="400" src="https://user-images.githubusercontent.com/104349824/180694127-27d9f62e-b2b1-49de-bb63-d0b41ba2edfc.png">

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-x64, locale en-VN)
    • Flutter version 3.0.5 at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM T225 (mobile) • R9JT3004VRJ • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 103.0.5060.114

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1839, on macOS 12.5 21G72 darwin-x64, locale en-VN)
    • Flutter version 3.1.0-0.0.pre.1839 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fa5618082d (3 hours ago), 2022-07-24 20:29:07 -0400
    • Engine revision d9c084560e
    • Dart version 2.19.0 (build 2.19.0-31.0.dev)
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (4 available)
    • SM T225 (mobile)   • R9JT3004VRJ                          • android-arm64  • Android 11 (API 30)
    • iPhone 13 (mobile) • 2526BC1A-435D-4B08-B99C-44B928F2517B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 12.5 21G72 darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>

Which device did you experience this issue with? (please specify the device information: device model, iOS version, etc) Could you reproduce the issue with [google_mobile_ads/example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)?

**Comment by atrope** [comment] 2022-08-04 19:03
We are having some issues in iOS with 2.0.0.

It depends on the creative so we don't have a way to reproduce:

![image](https://user-images.githubusercontent.com/2945478/182932615-92bf0da4-946c-42fa-865d-daad246f6830.png)

**Comment by huycozy** [comment] 2022-08-05 02:27
@atrope 
>We are having some issues in iOS with 2.0.0.
It depends on the creative so we don't have a way to reproduce:

Which device did you experience this issue with? (please specify the device information: device model, iOS version, etc) Could you reproduce the issue with [google_mobile_ads/example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example)?

**Comment by atrope** [comment] 2022-08-05 03:21
@huycozy 
Already happened iPhone 8 and 11 ios 14 and 15

It happens with specific ads(programatic, ad manger) so cannot use example adunit..

**Comment by huycozy** [comment] 2022-08-05 04:39
@atrope 
Thanks for the report! This is a known issue being tracked at https://github.com/googleads/googleads-mobile-flutter/issues/191
It looks like this behavior is only happening with production ads, please see https://github.com/googleads/googleads-mobile-flutter/issues/191#issuecomment-898244627

@Tutorialwork, @atrope: I close this issue as a duplicate, so please follow up on https://github.com/googleads/googleads-mobile-flutter/issues/191 for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue. If you disagree, please write in the comments and I will reopen it.

**Closed by huycozy** 2022-08-05 04:39 UTC
Labels: feedback required, in triage
