### ISSUE TITLE
FlutterRequestAgentProvider.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by ajaylakhimale** [googleads/googleads-mobile-flutter#1169] opened 2024-09-06 07:07 UTC
Note: C:\Users\devel\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterRequestAgentProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

- this is the error i'm gettin over and over again. tried to fix it in various projects but i didn't get the expected results . is this problem everywhere or just me , i don't know . but if you can help me fix it please do it.

- the complete error mesage as follows:
Note: C:\Users\devel\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterRequestAgentProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction

**Comment by malandr2** [comment] 2024-09-06 16:36
Hi @ajaylakhimale, this a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/1089 which we have already resolved and will be fixed in the next release.

**Closed by malandr2** 2024-09-06 16:36 UTC

**Comment by ajaylakhimale** [comment] 2024-09-08 15:39
> Hi @ajaylakhimale, this a duplicate of #1089 which we have already resolved and will be fixed in the next release.

okay
