### ISSUE TITLE
[gma_mediation] gma_mediation_xxx plugin fails to build or gets stuck on iOS。

### ISSUE THREAD

**Issue by ruiyong-lee** [googleads/googleads-mobile-flutter#1107] opened 2024-06-04 09:21 UTC
## Plugin Version

v5.1.0

## Steps to Reproduce

Related issues:
#1049 
#1066 
#544 

The above issue gives the relevant answer.

1. Delete `use_frameworks!`
2. Modify `use_frameworks!` to `use_frameworks! :linkage => :static`
3. Add `s.static_framework = true` to the `gma_mediation_xxx.podspec` file

- [×] If I use the first or second solution, and the project also uses Firebase Crashlytics, then the Xcode build will be stuck at the last step: `Run custom shell script 'FlutterFire:"flutterfire upload-crashlytics-symbols"`.
- [√] I downloaded the gma_mediation_xxx plugin locally, modified it according to the third solution, and built it successfully.

**Expected results:**
I found that `packages/google_mobile_ads/ios/google_mobile_ads.podspec` also has `s.static_framework = true`. Why doesn't `packages/mediation/gma_mediation_xxx` use the same configuration, but instead requires developers to modify the configuration of their own projects, thus affecting other plug-ins and causing failure to build?

**Actual results:** 

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.22.1 on channel stable at /Library/Developer/flutter
    • Upstream repository [GitHub - flutter/flutter: Flutter makes it easy and fast to build beautiful apps for mobile and beyo](https://github.com/flutter/flutter.git)
    • Framework revision a14f74ff3a (13 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/lry/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] Connected device (2 available)
    • iPhone 15 Pro (mobile)          • 1C031F8F-E78A-4D2F-9FE0-556CD92E4520 • ios    • com.apple.CoreSimulator.SimRuntime.iOS-17-5 (simulator)
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin • macOS 14.5 23F79 darwin-arm64

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by malandr2** [comment] 2024-06-04 14:39
@ruiyong-lee I've escalated this to engineering to determine if this is by design or if this is something to address on our end

**Comment by malandr2** [comment] 2024-06-12 16:11
Hi @ruiyong-lee I've confirmed with engineering option #3 is something that the engineering team can apply to the mediation adapters

**Comment by malandr2** [comment] 2024-06-24 14:05
Closing as https://github.com/googleads/googleads-mobile-flutter/pull/1112 has been merged in.

**Closed by malandr2** 2024-06-24 14:05 UTC
Labels: mediation
