### ISSUE TITLE
Crash - Ad for following adId already exists

### ISSUE THREAD

**Issue by yyyy-ltd** [googleads/googleads-mobile-flutter#78] opened 2021-03-11 14:59 UTC
following sequence crash the app:

if ad not null -> dispose
create new ad
load
***fast run my app - (clear my app memory and reference to old ad)***
if ad not null -> dispose
create new ad
load

E/flutter ( 4234): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Ad for following adId already exists: 2, null, java.lang.IllegalArgumentException: Ad for following adId already exists: 2

**Comment by HiroshiHorie** [comment] 2021-03-15 13:31
Having the same issue, tried a few methods to avoid this with no success. Probably related to #50 #47

**Comment by arieuqis** [comment] 2021-03-16 23:15
Having the same problem

**Comment by jjliu15** [comment] 2021-03-22 17:32
Should be resolved in 0.11.0+4, via #94.

**Comment by maheshmnj** [comment] 2021-12-10 13:16
@jjliu15 

Looks like this has resurfaced in the new release 1.0.1, I was able to reproduce by showing a simple banner and hot restarting the app.

<details>
<summary>flutter doctor -v</summary>

```
Restarted application in 2,538ms.
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): Failed to handle method call
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): java.lang.IllegalArgumentException: Ad for following adId already exists: 0
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at io.flutter.plugins.googlemobileads.AdInstanceManager.trackAd(AdInstanceManager.java:79)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:351)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at android.os.Looper.loop(Looper.java:236)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(25041): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (25041): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Ad for following adId already exists: 0, null, java.lang.IllegalArgumentException: Ad for following adId already exists: 0
E/flutter (25041): 	at io.flutter.plugins.googlemobileads.AdInstanceManager.trackAd(AdInstanceManager.java:79)
E/flutter (25041): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:351)
E/flutter (25041): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (25041): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/flutter (25041): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/flutter (25041): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/flutter (25041): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (25041): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (25041): 	at android.os.Looper.loop(Looper.java:236)
E/flutter (25041): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
E/flutter (25041): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25041): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/flutter (25041): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (25041): )
E/flutter (25041): #0      StandardMethodCodec.decodeEnvelope
E/flutter (25041): #1      MethodChannel._invokeMethod
E/flutter (25041): <asynchronous suspension>
E/flutter (25041): #2      BannerAd.load
E/flutter (25041): <asynchronous suspension>
E/flutter (25041):

```
</details>

**Comment by jjliu15** [comment] 2021-12-10 18:44
I just checked the example app and wasn't able to reproduce this on android or iOS. 
@maheshmnj could you share more reproduction steps or a code sample?

**Comment by maheshmnj** [comment] 2021-12-13 04:25
I was able to reproduce it again.

### Steps to reproduce 

- run the below code sample on android in debug mode
   using `google_mobile_ads: ^1.0.1` on flutter `stable 2.8.0`
- hot restart the app


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter_beta
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (8 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

mahesh@Maheshs-MacBook-Air-M1 ads_example % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.8.0 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (4 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • FC644E6C-7F02-40E5-9998-1F0CD162FBD8 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 96.0.4664.93
    ! Device 192.168.1.6:5555 is offline.

• No issues found!

```
</details>


<details>
<summary>logs</summary>

```console
W/ContentCatcher(20971): Failed to notify a WebView
Restarted application in 2,499ms.
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): Failed to handle method call
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): java.lang.IllegalArgumentException: Ad for following adId already exists: 0
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at io.flutter.plugins.googlemobileads.AdInstanceManager.trackAd(AdInstanceManager.java:79)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:351)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at android.os.Looper.loop(Looper.java:236)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/MethodChannel#plugins.flutter.io/google_mobile_ads(20971): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (20971): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Ad for following adId already exists: 0, null, java.lang.IllegalArgumentException: Ad for following adId already exists: 0
E/flutter (20971): 	at io.flutter.plugins.googlemobileads.AdInstanceManager.trackAd(AdInstanceManager.java:79)
E/flutter (20971): 	at io.flutter.plugins.googlemobileads.GoogleMobileAdsPlugin.onMethodCall(GoogleMobileAdsPlugin.java:351)
E/flutter (20971): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (20971): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/flutter (20971): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/flutter (20971): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/flutter (20971): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter (20971): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (20971): 	at android.os.Looper.loop(Looper.java:236)
E/flutter (20971): 	at android.app.ActivityThread.main(ActivityThread.java:8061)
E/flutter (20971): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (20971): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/flutter (20971): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (20971): )
E/flutter (20971): #0      StandardMethodCodec.decodeEnvelope
E/flutter (20971): #1      MethodChannel._invokeMethod
E/flutter (20971): <asynchronous suspension>
E/flutter (20971): #2      BannerAd.load
E/flutter (20971): <asynchronous suspension>
E/flutter (20971):

```
</details>


<details>
<summary>code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: HomeScreen());
  }
}



class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          Expanded(child: ListView.builder(itemBuilder: (context, index) {
            return ListTile(
              title: Text('Item $index'),
              onTap: () {
                Navigator.push(context, MaterialPageRoute(builder: (context) {
                  return const ProducDetailPage();
                }));
              },
            );
          })),
          const CustomBannerAd()
        ],
      ),
    );
  }
}

class ProducDetailPage extends StatelessWidget {
  const ProducDetailPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Produc Detail'),
        ),
        body: Column(children: const [
          SizedBox(
            height: 150,
            child: Placeholder(
              color: Colors.red,
            ),
          ),
          SizedBox(
            height: 150,
            child: Placeholder(
              color: Colors.green,
            ),
          ),
          CustomBannerAd()
        ]));
  }
}

class CustomBannerAd extends StatefulWidget {
  const CustomBannerAd({Key? key}) : super(key: key);

  @override
  _CustomBannerAdState createState() => _CustomBannerAdState();
}

class _CustomBannerAdState extends State<CustomBannerAd> {
  BannerAd? _anchoredAdaptiveAd;
  var _isLoaded = false;
  late Orientation _currentOrientation;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();

    _currentOrientation = MediaQuery.of(context).orientation;
    _loadAd();
  }

  @override
  void dispose() {
    super.dispose();

    _anchoredAdaptiveAd?.dispose();
  }

  Future<void> _loadAd() async {
    await _anchoredAdaptiveAd?.dispose();

    if (mounted) {
      setState(() {
        _anchoredAdaptiveAd = null;
        _isLoaded = false;
      });
    }

    final AnchoredAdaptiveBannerAdSize? size =
        await AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize(
            MediaQuery.of(context).size.width.truncate());

    if (size == null) {
      debugPrint('Unable to get height of anchored banner.');
      return;
    }

    _anchoredAdaptiveAd = BannerAd(
      adUnitId: Platform.isAndroid
          ? 'ca-app-pub-3940256099942544/6300978111'
          : 'ca-app-pub-3940256099942544/2934735716',
      size: size,
      request: const AdRequest(
        nonPersonalizedAds: false,
      ),
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          debugPrint("Ad loaded");
          if (mounted) {
            setState(() {
              _anchoredAdaptiveAd = ad as BannerAd;
              _isLoaded = true;
            });
          }
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          debugPrint('$BannerAd failedToLoad: $error');
          ad.dispose();
        },
        onAdOpened: (Ad ad) => debugPrint('$BannerAd onAdOpened.'),
        onAdClosed: (Ad ad) => debugPrint('$BannerAd onAdClosed.'),
      ),
    );

    return _anchoredAdaptiveAd?.load();
  }

  @override
  Widget build(BuildContext context) {
    return OrientationBuilder(builder: (context, orientation) {
      if (_currentOrientation == orientation &&
          _anchoredAdaptiveAd != null &&
          _isLoaded) {
        return Container(
          color: Colors.transparent,
          width: _anchoredAdaptiveAd!.size.width.toDouble(),
          height: _anchoredAdaptiveAd?.size.height.toDouble(),
          child: AdWidget(ad: _anchoredAdaptiveAd!),
        );
      }

      // Reload the ad if the orientation changes.
      if (_currentOrientation != orientation) {
        _currentOrientation = orientation;
        _loadAd();
      }
      return const SizedBox.shrink();
    });
  }
}

```
</details>

Let me know if you need any additional info.

Thanks

**Comment by maheshmnj** [comment] 2021-12-13 14:21
Labeling this issue as a regression bug, feel free to close it if you disagree.

**Comment by anandyadav21219** [comment] 2022-05-28 11:51
Having same issue

**Comment by felipecastrosales** [comment] 2022-10-13 13:09
I have the same problem here.
Any news about this?

**Comment by huycozy** [comment] 2023-07-20 11:52
We’re closing this issue due to inactivity. If you’re still impacted, please create a new issue via the [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk).

**Closed by huycozy** 2023-07-20 11:52 UTC
Labels: bug, p2-medium, e2-days, platform-android

**Comment by andraskloczl** [comment] 2025-01-17 13:51
The issue is still there and it's quite annoying that when I'm doing hot reload the ad throws an error.
