### ISSUE TITLE
[IOS] LoadAdError code: 1, domain: com.google.admob, message: Request Error: No ad to show.

### ISSUE THREAD

**Issue by davideroffo** [googleads/googleads-mobile-flutter#458] opened 2021-12-05 11:26 UTC
Hi, I have implemented the Flutter `google_mobile_ads: ^1.0.0` .
The test Ad Units are showing fine in the App (debug mode), but the real Ad Units, once the App has been built and deployed in Test Flight (iOS) are not showing at all.
In the console I get this error:

`flutter: Ad failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))`

What I checked:
- Real Ad Units Ids are correct
- The GADApplicationIdentifier is correct
- I have filled all the information requested in the Payment section (AdMob), except for the Payment Method (I can't add it yet, current balance < 10 dollars)

What should I do?

## Plugin Version

google_mobile_ads: ^1.0.0

## Steps to Reproduce

1. Create a banner Ad Unit (more than 24 hours ago)
2. Add it in a flutter widget (main screen)
3. Make sure you have updated the Info.plist file with the pub id (related to your admob account)

**Expected results:** AdMob banner is working and rendering

**Actual results:** AdMob banner is not working and is not rendering

`flutter: Ad failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))`

**Comment by maheshmnj** [comment] 2021-12-07 10:49
Hi @davideroffo, Thanks for filing the issue. 

> LoadAdError(code: 1

Generally indicates an invalid request [as per the documentation](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#ERROR_CODE_INTERNAL_ERROR),

How long has it been since the ad unitId was created?

Leaving this issue open for further investigation as I won't be able to reproduce production bugs.

**Comment by davideroffo** [comment] 2021-12-07 10:52
Hi @maheshmnj , thanks for the reply.
With iOS I get this error code number 1, but if I start the application on an Android device (with the proper banner ad unit for android) I get error code number 3: No ad config.
It's really strange, because test ads are working properly and everything is set up correctly, just as the documentation explains (google mobile sdk for flutter).
The Ad Units have been created more than 5 days ago and the app-ads.txt has been scanned properly 3 days ago.

**Comment by maheshmnj** [comment] 2021-12-07 11:04
Thanks for the info.

>if I start the application on an Android device (with the proper banner ad unit for android) I get error code number 3: No ad config.

For the Android-specific bug you may follow up on this issue https://github.com/googleads/googleads-mobile-flutter/issues/59

**Comment by maheshmnj** [comment] 2021-12-08 10:59
@davideroffo I  was able to reproduce this with test ads, the ads were working fine and when showing rewarded ads after a hot restart the issue was reproduced using `google_mobile_ads: ^1.0.1`

<details>
<summary>logs</summary>

```
Restarted application in 349ms.
flutter: Instance of 'InterstitialAd' loaded
flutter: AdManagerBannerAd loaded.
flutter: BannerAd loaded.
flutter: Ad impression.
flutter: RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: iI-wYZbXAuyh3LUP9NeoqA0, mediationAdapterClassName: null, adapterResponses: [AdapterResponseInfo(adapterClassName: GADMAdapterGoogleAdMobAds, latencyMillis: 2665), description: {
    Credentials =     {
        "campaign_id" = 1057492276;
        pubid = "ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=b6&caqid=iI-wYdOVApGrz7sPmNOBiAI";
    };
    Error = "Error Domain=com.google.admob Code=5 \"Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.\" UserInfo={NSLocalizedDescription=Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.}";
    Latency = "2.665";
    Network = GADMAdapterGoogleAdMobAds;
}, credentials: {
    "campaign_id" = 1057492276;
    pubid = "ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=b6&caqid=iI-wYdOVApGrz7sPmNOBiAI";
}<…>
flutter: RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: i4-wYYzhD_bRz7sPpve4mAI, mediationAdapterClassName: null, adapterResponses: [AdapterResponseInfo(adapterClassName: GADMAdapterGoogleAdMobAds, latencyMillis: 2633), description: {
    Credentials =     {
        "campaign_id" = 1057492276;
        pubid = "ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=b6&caqid=i4-wYcOdD8ah4t4Pw-qjwA8";
    };
    Error = "Error Domain=com.google.admob Code=5 \"Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.\" UserInfo={NSLocalizedDescription=Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.}";
    Latency = "2.633";
    Network = GADMAdapterGoogleAdMobAds;
}, credentials: {
    "campaign_id" = 1057492276;
    pubid = "ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=b6&caqid=i4-wYcOdD8ah4t4Pw-qjwA8";
}<…>
flutter: RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: jo-wYffdF4OR3LUP-6OmmAU, mediationAdapterClassName: null, adapterResponses: [AdapterResponseInfo(adapterClassName: GADMAdapterGoogleAdMobAds, latencyMillis: 147), description: {
    Credentials =     {
        pubid = "ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=b6&caqid=jo-wYdOXF6vb3LUPuLSmgAo";
    };
    Error = "Error Domain=com.google.admob Code=5 \"Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.\" UserInfo={NSLocalizedDescription=Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.}";
    Latency = "0.147";
    Network = GADMAdapterGoogleAdMobAds;
}, credentials: {
    pubid = "ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=b6&caqid=jo-wYdOXF6vb3LUPuLSmgAo";
}, adError: AdError(code: 5, domain: com.google.admob, message: Reques<…>
flutter: RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: j4-wYYgcscrPuw_N0bW4DQ, mediationAdapterClassName: null, adapterResponses: [AdapterResponseInfo(adapterClassName: GADMAdapterGoogleAdMobAds, latencyMillis: 2652), description: {
    Credentials =     {
        "campaign_id" = 1057492276;
        pubid = "ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=b6&caqid=jo-wYdLKPNS-3LUPxPOhSA";
    };
    Error = "Error Domain=com.google.admob Code=5 \"Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.\" UserInfo={NSLocalizedDescription=Request Error: The Google ad request was unable to be fulfilled before a timeout occurred.}";
    Latency = "2.652";
    Network = GADMAdapterGoogleAdMobAds;
}, credentials: {
    "campaign_id" = 1057492276;
    pubid = "ca-app-pub-3940256099942544/1712485313/cak=no_cache&cadc=b6&caqid=jo-wYdLKPNS-3LUPxPOhSA";
}, a<…>

```
</details>

**Comment by davideroffo** [comment] 2021-12-08 11:08
Is needed a fix to the library? Or is it Admob side?

**Comment by maheshmnj** [comment] 2021-12-08 11:12
Looks like it's from AdMob but I am not really sure, someone from the team will investigate this further.

**Comment by davideroffo** [comment] 2021-12-08 11:15
Thank you, just a side note, I'm getting these errors on:
- Banner ad units 
- Interstitial ad units

**Comment by Luciano-Magnus** [comment] 2022-01-03 13:01
Any news about this?
I have the same problem

**Comment by yoloxo** [comment] 2022-01-14 20:03
Any updates? Got same issue here

**Comment by nelsonspbr** [comment] 2022-01-21 01:48
Same here, it has been like this for over a month now.

**Comment by Luciano-Magnus** [comment] 2022-01-24 21:43
Hello, I just came to inform you that my ads appeared again yesterday, I tested today and for now it is still ok, I did some steps that I was instructed to follow by the Admob community, this [LINK](https://support.google.com/admob/thread/144885095/ol%C3%A1-s%C3%B3-estou-recebendo-erros-na-configura%C3%A7%C3%A3o-do-an%C3%BAncio?hl=en) may help you to solve your problem. IMPORTANT: I ​​DON'T KNOW IF THIS SOLVE MY PROBLEM. I simply followed the steps and a few days later it started working again, maybe it was some correction made by their team. I really do not know.

**Comment by nelsonspbr** [comment] 2022-01-26 17:13
Unfortunately no luck here. Everything looks good -- no policy center issues, app is approved (it was working before), connected to the store, ready, verified, ad unit works (well, used to work), app-ads.txt found and verified. It seems there is no actual support from AdMob -- meaning, someone **from** AdMob that we can contact to get help. If there is a way to contact their team, please let me know.

**Comment by yoloxo** [comment] 2022-01-27 13:21
This was my solution https://stackoverflow.com/a/70795526/16666091

**Comment by Luciano-Magnus** [comment] 2022-01-27 22:11
Hi @nelsonspbr , unfortunately I don't know how to contact the admob team, just the community, but try there, you might be lucky.

**Comment by 31Carlton7** [comment] 2022-02-06 02:38
Any proper fix for this? Nothing is working for me

**Comment by azazadev** [comment] 2022-03-07 19:02
any update ?

**Comment by alinsary37** [comment] 2022-05-23 08:45
> Hi @maheshmnj , thanks for the reply. With iOS I get this error code number 1, but if I start the application on an Android device (with the proper banner ad unit for android) I get error code number 3: No ad config. It's really strange, because test ads are working properly and everything is set up correctly, just as the documentation explains (google mobile sdk for flutter). The Ad Units have been created more than 5 days ago and the app-ads.txt has been scanned properly 3 days ago.

solve it ?

**Comment by mraaz97** [comment] 2022-07-06 08:16
The issue still exists...

**Comment by maheshmnj** [comment] 2022-07-06 12:53
please see if this comment helps resolve the issue https://github.com/googleads/googleads-mobile-flutter/issues/59#issuecomment-912724307

**Comment by keybow007** [comment] 2022-08-26 06:13
> please see if this comment helps resolve the issue [#59 (comment)](https://github.com/googleads/googleads-mobile-flutter/issues/59#issuecomment-912724307)

Unfortunately, it was not helpful.
With the test ID, the ad is displayed correctly, but with the production ad ID, I get "LoadAdError code: 1".

・The app-ads.txt file is set up correctly (account approved in the Admob console).
・Ads are displayed correctly in the Android app.
・No mistakes in pasting Admob ad IDs into Android Studio project.

**Comment by large** [comment] 2022-10-05 06:09
I have checked with Ads SDK team and they confirm the same error:

```
Hi Large,

Thank you for providing the requested information.

I've checked your Ad Unit against our iOS sample app, and getting the same no fill error on my end.
Also, I've checked your account and can confirm that it is fully setup (Billing and PIN verification) and there's no policy violation under your account.
This could be an ad serving issue.
However, since you're using flutter app, they we would suggest to reach out to our AdMob team who specifically handles our flutter app via this link and have them check this.

Regards,
Google Logo	
Teejay Wennie
Mobile Ads SDK Team
```

My iOS have "Ad exposure / session" around 73% and  Android (with same code) is 93% in production code / official app. These numbers was quite equal before I upgraded my app. I saw an decrease in income after my latest update too.
Even got a thank you note from one user for removing the ads 🤔

This issue has to be addressed asap, people are probably loosing money here...

**Comment by large** [comment] 2022-10-13 17:18
@maheshmnj are there any progress regarding this issue?

**Comment by maheshmnj** [comment] 2022-10-13 21:18
Unfortunately no updates so far.

**Comment by yasin1376** [comment] 2023-01-15 05:45
any update on this error?

**Comment by wz003** [comment] 2023-03-19 08:24
Still same issue, I use flutter and integrate admob with google_mobile_ads: ^2.3.0, 
ads were able to show with formal ad unit id after I link admob application to app store/play store.

Few days later, both banner and interstitial ads always fail to load due to same error 
In IOS it's "code = 1, Msg = Request Error: No ad to show."
In Android it's "code = 3, Msg = No fill."

Where as ads are still able to loaded if I change my own ad unit ID to [test ad unit ID](https://developers.google.com/admob/android/test-ads?hl=zh-tw)


I've followed instruction in [here](https://support.google.com/admob/thread/151811211/com-google-admob-code-1-request-error-no-ad-to-show?hl=en), include
1. add app-ads.txt and verified success by admob
2. Create and link accounts of google adsense and google ads to admob.
(I cannot verify my payment in admob website, it might caused by balance of admob too low in my account (< 2 USD))

but nothing changes at this moment, 

any help would be appreciated,

**Comment by kimalphaville** [comment] 2023-03-29 20:18
Getting the same issue

**Comment by ZhongTaoTian** [comment] 2023-04-13 09:28
If the device is added to the testing machine and then `didFailToReceiveAdWithError` Recursive execution `bannerView?.load(GADRequest())` , Occasionally successful...

**Comment by arash01** [comment] 2023-05-17 12:26
Any updates on this? It's still happening. It was all good for couple of weeks but all of the sudden stopped working with no code changes.
LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: #######, mediationAdapterClassName: null, adapterResponses: [], loadedAdapterResponseInfo: AdapterResponseInfo(adapterClassName: , latencyMillis: 0, description: , adUnitMapping: {}, adError: null, adSourceName: , adSourceId: , adSourceInstanceName: , adSourceInstanceId: )), responseExtras: {mediation_group_name: Campaign})

**Comment by Alex-web0** [comment] 2023-06-21 07:47
Any help? still no ads showing with err code 1

**Comment by brijeshNimavat11** [comment] 2023-07-24 13:49
For me below iOS 16 is getting same issue, Any Update?

**Comment by malandr2** [comment] 2023-07-24 21:42
Hi all,

If you are running into this error please reach out to our support team on the [Developer Forum](https://groups.google.com/g/google-admob-ads-sdk) for assistance. 

A `LoadAdError code: 1` or `error 3: No ad config` is typically not a plugin issue. The reason you are receiving that error may vary case by case. This is something our support team can help with. Please rout your concerns there. Thanks. 

Closing this out. Any follow ups should be directed to the [Developer Forum](https://groups.google.com/g/google-admob-ads-sdk).

**Closed by malandr2** 2023-07-24 21:42 UTC
Labels: bug, p2-medium, e3-weeks, platform-ios, admob

**Comment by Abdulah-butt** [comment] 2023-10-11 10:33
GETTING SAME ISSUE

`flutter: BannerAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [], loadedAdapterResponseInfo: AdapterResponseInfo(adapterClassName: , latencyMillis: 0, description: , adUnitMapping: {}, adError: null, adSourceName: , adSourceId: , adSourceInstanceName: , adSourceInstanceId: )), responseExtras: {})`

**Comment by imajercsik** [comment] 2023-11-16 15:23
Same issue here with rewarded ads:

RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [], loadedAdapterResponseInfo: AdapterResponseInfo(adapterClassName: , latencyMillis: 0, description: , adUnitMapping: {}, adError: null, adSourceName: , adSourceId: , adSourceInstanceName: , adSourceInstanceId: )), responseExtras: {})

**Comment by AxiatCode** [comment] 2023-12-29 11:04
Still getting the same issue for iOS only:

`flutter: Anchored adaptive banner failedToLoad: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [], loadedAdapterResponseInfo: AdapterResponseInfo(adapterClassName: , latencyMillis: 0, description: , adUnitMapping: {}, adError: null, adSourceName: , adSourceId: , adSourceInstanceName: , adSourceInstanceId: )), responseExtras: {})`

Wondering for almost more than 2 years and the issue persists, even with the latest version of both google ads.

Any chance for a hot fix ??

Thanks.

**Comment by shreyash-sharechat** [comment] 2024-01-11 06:16
I can confirm issue is still there in 2024 (iOS).


> Hi all,
> 
> If you are running into this error please reach out to our support team on the [Developer Forum](https://groups.google.com/g/google-admob-ads-sdk) for assistance.
> 
> A `LoadAdError code: 1` or `error 3: No ad config` is typically not a plugin issue. The reason you are receiving that error may vary case by case. This is something our support team can help with. Please rout your concerns there. Thanks.
> 
> Closing this out. Any follow ups should be directed to the [Developer Forum](https://groups.google.com/g/google-admob-ads-sdk).
There should better documented communication as to what are possible scenarios that could make this happen, so that we do inital diagnosis by ourselves and then reach out support if needed.

**Comment by johnwiese-ms** [comment] 2024-04-03 18:36
Yup, seeing the same thing, though it is not every time so I can't track down what the circumstances are that cause the error.

`LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [], loadedAdapterResponseInfo: AdapterResponseInfo(adapterClassName: , latencyMillis: 0, description: , adUnitMapping: {}, adError: null, adSourceName: , adSourceId: , adSourceInstanceName: , adSourceInstanceId: )), responseExtras: {})`

**Comment by alionurozdemir** [comment] 2024-06-24 10:37
**_The error still persists. Did anyone solve it?_**

flutter: BannerAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [], loadedAdapterResponseInfo: AdapterResponseInfo(adapterClassName: , latencyMillis: 0, description: , adUnitMapping: {}, adError: null, adSourceName: , adSourceId: , adSourceInstanceName: , adSourceInstanceId: )), responseExtras: {})
Lost connection to device.
