### ISSUE TITLE
"AdWidget requires Ad.load to be called before AdWidget is inserted into the tree" exception

### ISSUE THREAD

**Issue by rafaellop** [googleads/googleads-mobile-flutter#733] opened 2022-12-31 08:18 UTC
## Plugin Version
2.3.0

## Steps to Reproduce

The exception occurs if I turn off internet connection on the device and navigate between pages where the `AdWidget` is placed. The build function is called for the page which I'm switching out of and the exception occurs. 

Test case

Start a project with no connection
* Page 1 and Page 2 use the same banner widget `AdWidget` displayed depending on `BannerAd != null && isLoaded` flag. The flag is set to true in `onAdLoaded`
* Start the app with no internet connection

1. Page 1 is displayed and `AdWidget` is not because the `BannerAd == null && isLoaded` is false
2. Turn ON the internet connection
3. Banner is still invisible on the Page 1 (no connection detection is utilized) so we navigate to Page 2
4. Flutter calls build for the page 2 which loads banner and sets the flag on the page 2, but...
5. Flutter also rebuilds the page 1 which has `AdWidget` depending on the `BannerAd == null && isLoaded` but due to the Page 2 navigation they are no longer set to false and cause the "AdWidget requires Ad.load" exception for the page 1.

**Expected results:** 
No exception

**Actual results:** 
Exception is thrown: "AdWidget requires Ad.load to be called before AdWidget is inserted into the tree"

<details>
  <summary>Logs</summary>

```
[        ]  Running with sound null safety 
[        ] An Observatory debugger and profiler on SM G990B is available at: http://127.0.0.1:18221/uk9y-XRvgxs=/
[   +6 ms] I/.example.app(21737): Compiler allocated 4564KB to compile void android.view.ViewRootImpl.performTraversals()
[ +576 ms] I/BufferQueueProducer(21737): [SurfaceView - com.example.app/com.example.app.MainActivity@f14c1bf@0#1(BLAST Consumer)1](id:54e900000001,api:1,p:21737,c:21737) queueBuffer: queued for the
first time.
[   +5 ms] The Flutter DevTools debugger and profiler on SM G990B is available at: http://127.0.0.1:9104?uri=http://127.0.0.1:18221/uk9y-XRvgxs=/
[        ] D/ViewRootImpl@76e0a42[MainActivity](21737): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
[        ] D/ViewRootImpl@76e0a42[MainActivity](21737): Creating frameCompleteCallback
[        ] I/SurfaceView@f14c1bf(21737): uSP: rtp = Rect(0, 0 - 1080, 2340) rtsw = 1080 rtsh = 2340
[        ] D/ViewRootImpl@76e0a42[MainActivity](21737): Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
[        ] I/SurfaceView@f14c1bf(21737): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
[        ] I/SurfaceView@f14c1bf(21737): aOrMT: uB = true t = android.view.SurfaceControl$Transaction@6ee8fab fN = 1 android.view.SurfaceView.access$500:124
android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:319 
[        ] I/SurfaceView@f14c1bf(21737): aOrMT: vR.mWNT, vR = ViewRootImpl@76e0a42[MainActivity]
[        ] I/ViewRootImpl@76e0a42[MainActivity](21737): mWNT: t = android.view.SurfaceControl$Transaction@6ee8fab fN = 1 android.view.SurfaceView.applyOrMergeTransaction:1628
android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 
[        ] I/ViewRootImpl@76e0a42[MainActivity](21737): mWNT: merge t to BBQ
[   +2 ms] I/BufferQueueProducer(21737): [ViewRootImpl@76e0a42[MainActivity]#0(BLAST Consumer)0](id:54e900000000,api:1,p:21737,c:21737) queueBuffer: queued for the first time.
[   +2 ms] D/OpenGLRenderer(21737): GPIS:: SetUp Pid : 21737    Tid : 21766
[        ] D/ViewRootImpl@76e0a42[MainActivity](21737): Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
[   +1 ms] I/ViewRootImpl@76e0a42[MainActivity](21737): [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:5000
android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
[        ] I/ViewRootImpl@76e0a42[MainActivity](21737): [DP] rdf()
[        ] D/ViewRootImpl@76e0a42[MainActivity](21737): reportDrawFinished (fn: -1) 
[  +25 ms] I/ViewRootImpl@76e0a42[MainActivity](21737): MSG_WINDOW_FOCUS_CHANGED 1 1
[        ] D/InputMethodManager(21737): startInputInner - Id : 0
[        ] I/InputMethodManager(21737): startInputInner - mService.startInputOrWindowGainedFocus
[   +1 ms] D/DynamitePackage(21737): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
[  +13 ms] I/Ads     (21737): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("2C8F4C65BD0E100B46BF0E9E15C7687E")) to get test ads on this device.
[   +9 ms] I/DynamiteModule(21737): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:224400003
[  +11 ms] W/ConnectionStatusConfig(21737): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.CACHE
[        ] D/ConnectivityManager(21737): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4186)]
[android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4750)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4717)]
[android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4691)] [aea.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:2)]     
[aea.a(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:0)] [adl.b(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:11)]   
[adl.a(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:0)]
[com.google.android.gms.ads.internal.i.run(:com.google.android.gms.policy_ads_fdr_dynamite@224400003@224400003057.484457631.484457631:9)]
[java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)] [java.lang.Thread.run(Thread.java:1012)]   
[   +1 ms] I/DynamiteModule(21737): Selected remote version of com.google.android.gms.ads.dynamite, version >= 224400003
[   +1 ms] D/InputMethodManager(21737): startInputInner - Id : 0
[  +25 ms] W/ziparchive(21737): Unable to open '/data/user/0/com.example.app/app_pccache/5/26AA3B2CD79D49EF34C1F34468F9D88FC1B3CD1A/pcam.dm': No such file or directory
[  +19 ms] D/nativeloader(21737): Configuring classloader-namespace for other apk . target_sdk_version=33, uses_libraries=ALL, library_path=, permitted_path=/data:/mnt/expand
[        ] D/nativeloader(21737): Extending system_exposed_libraries:
libhal.wsm.samsung.so:libheifcapture_jni.media.samsung.so:libjpegsq.media.samsung.so:libsemimagecrop_jni.media.samsung.so:libapex_jni.media.samsung.so:libsume_mediabuffer_jni.media.samsung.so:libBeauty_v4.ca
mera.samsung.so:libexifa.camera.samsung.so:libjpega.camera.samsung.so:libOpenCv.camera.samsung.so:libVideoClassifier.camera.samsung.so:libtensorflowLite.dynamic_viewing.camera.samsung.so:libImageScreener.cam
era.samsung.so:libMyFilter.camera.samsung.so:libtflite2.myfilters.camera.samsung.so:libHIDTSnapJNI.camera.samsung.so:libSmartScan.camera.samsung.so:libRectify.camera.samsung.so:libDocRectifyWrapper.camera.sa
msung.so:libUltraWideDistortionCorrection.camera.samsung.so:libHpr_RecGAE_cvFeature_v1.0.camera.samsung.so:libHprFace_GAE_api.camera.samsung.so:libFace_Landmark_API.camera.samsung.so:libHprFace_GAE_jni.camer
a.samsung.so:libFacialBasedSelfieCorrection.camera.samsung.so:libcolor_engine.camera.samsung.so:libDLInterface_hidl.camera.samsung.so:libObjectDetector_v1.came
[  +42 ms] W/Ads     (21737): Not retrying to fetch app settings
[   +4 ms] W/ConnectionStatusConfig(21737): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.START
[  +88 ms] I/Ads     (21737): Ad failed to load : 0
[  +10 ms] I/flutter (21737): Ad failed to load: LoadAdError(code: 0, domain: com.google.android.gms.ads, message: Error while connecting to ad server: Unable to resolve host "googleads.g.doubleclick.net":
No address associated with hostname, responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: [], loadedAdapterResponseInfo: null), responseExtras: {})
[+14314 ms] I/ViewRootImpl@76e0a42[MainActivity](21737): MSG_WINDOW_FOCUS_CHANGED 0 1
[+2786 ms] D/InsetsSourceConsumer(21737): ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.example.app/com.example.app.MainActivity
[        ] D/InsetsSourceConsumer(21737): ensureControlAlpha: for ITYPE_STATUS_BAR on com.example.app/com.example.app.MainActivity
[   +3 ms] I/ViewRootImpl@76e0a42[MainActivity](21737): MSG_WINDOW_FOCUS_CHANGED 1 1
[        ] D/InputMethodManager(21737): startInputInner - Id : 0
[        ] I/InputMethodManager(21737): startInputInner - mService.startInputOrWindowGainedFocus
[+4320 ms] I/ViewRootImpl@76e0a42[MainActivity](21737): ViewPostIme pointer 0
[  +88 ms] I/ViewRootImpl@76e0a42[MainActivity](21737): ViewPostIme pointer 1
[  +32 ms] I/flutter (21737): Utils.showPage(foodlist)
[ +270 ms] D/DynamitePackage(21737): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
[   +2 ms] I/Ads     (21737): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("2C8F4C65BD0E100B46BF0E9E15C7687E")) to get test ads on this device.
[  +10 ms] I/DynamiteModule(21737): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:224400003
[        ] I/DynamiteModule(21737): Selected remote version of com.google.android.gms.ads.dynamite, version >= 224400003
[  +14 ms] W/ConnectionStatusConfig(21737): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.START
[ +575 ms] I/FA      (21737): Tag Manager is not found and thus will not be used
[   +3 ms] E/FA      (21737): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
[ +242 ms] I/DynamiteModule(21737): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:224400003
[        ] I/DynamiteModule(21737): Selected remote version of com.google.android.gms.ads.dynamite, version >= 224400003
[  +19 ms] I/flutter (21737): Ad impression.
[   +2 ms] I/flutter (21737): Ad loaded.
[  +89 ms] 
           ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
           The following assertion was thrown while applying parent data.:
           Incorrect use of ParentDataWidget.
           The ParentDataWidget Positioned(bottom: 8.0) wants to apply ParentData of type StackParentData to a
           RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.
           Usually, this means that the Positioned widget has the wrong ancestor RenderObjectWidget. Typically,
           Positioned widgets are placed directly inside Stack widgets.
           The offending Positioned is currently placed inside a Padding widget.
           The ownership chain for the RenderObject that received the incompatible parent data was:
             Align ← Positioned ← MediaQuery ← Padding ← SafeArea ← LayoutBuilder ← OrientationBuilder ←
           GetBuilder<AdsController> ← BannerAD ← Stack ← ⋯

           When the exception was thrown, this was the stack:
           #0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:6042:11)
           #1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:6059:6)
           #2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6082:7)
           #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5751:5)
           #4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6299:11)
           ...     Normal element mounting (22 frames)
           #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
           #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
           #28     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:135:18)
           #29     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:19)
           #30     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153:12)
           #31     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2246:59)
           #32     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1035:15)
           #33     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2246:14)
           #34     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228:7)
           #35     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:316:5)
           #36     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
           #37     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
           #38     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
           #39     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:595:43)
           #40     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:622:12)
           #41     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
           #42     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
           #43     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
           #44     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1055:7)
           #45     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
           #46     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410:14)
           #47     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
           #48     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
           #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
           #50     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
           #51     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
           #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
           #53     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1462:11)
           #54     RenderObject.layout (package:flutter/src/rendering/object.dart:2135:7)
           #55     RenderBox.layout (package:flutter/src/rendering/box.dart:2418:11)
           #56     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
           #57     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1055:7)
           #58     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
           #59     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:410:14)
           #60     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1973:7)
           #61     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:999:18)
           #62     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:513:19)
           #63     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
           #64     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
           #65     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
           #66     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
           #67     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
           #68     _invoke (dart:ui/hooks.dart:148:13)
           #69     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
           #70     _drawFrame (dart:ui/hooks.dart:115:31)
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[   +9 ms] 
           Another exception was thrown: AdWidget requires Ad.load to be called before AdWidget is inserted into the tree
[   +3 ms]
           Another exception was thrown: Incorrect use of ParentDataWidget.
[ +523 ms] I/PlatformViewsController(21737): Hosting view in view hierarchy for platform view: 0

```

```
no issues for the flutter analyze
```

```
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.22000.1335])
    • Flutter version 3.3.10 on channel stable at C:\Mobile\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

Checking Android licenses is taking an unexpectedly long time...[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Mobile\Android_SDK\sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = C:\Mobile\Android_SDK\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32929.385
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.74.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.56.0

[√] Connected device (4 available)
    • SM G990B (mobile) • RFCRC174LXM • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22000.1335]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 108.0.5359.125
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 108.0.1462.46

[√] HTTP Host Availability
    • All required HTTP hosts are available

```

</details>

**Comment by darshankawar** [comment] 2023-01-02 10:10
Thanks for the report @rafaellop 
The exception you mentioned is the second exception from the log, but the first one is:

```
The following assertion was thrown while applying parent data.:
           Incorrect use of ParentDataWidget.
           The ParentDataWidget Positioned(bottom: 8.0) wants to apply ParentData of type StackParentData to a
           RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.
           Usually, this means that the Positioned widget has the wrong ancestor RenderObjectWidget. Typically,
           Positioned widgets are placed directly inside Stack widgets.
           The offending Positioned is currently placed inside a Padding widget.
           The ownership chain for the RenderObject that received the incompatible parent data was:
             Align ← Positioned ← MediaQuery ← Padding ← SafeArea ← LayoutBuilder ← OrientationBuilder ←
           GetBuilder<AdsController> ← BannerAD ← Stack ← ⋯
```

This looks like a code implementation issue, so please try to fix it first and then try the steps to replicate you mentioned above and see if using it, you still get the `AdWidget requires Ad.load to be called before AdWidget is inserted` or not.
If yes, please provide a complete minimal reproducible code sample that we can use to verify this behavior properly.

**Comment by rafaellop** [comment] 2023-01-02 18:30
Thank you for the hint and I'm sorry I missed that. I've moved `Positioned` widget higher in the hierarchy and it seems that it fixed the "Ad.load" exception issue.

**Comment by darshankawar** [comment] 2023-01-03 05:25
Good to know the issue is resolved. Closing based on above comment.

**Closed by darshankawar** 2023-01-03 05:25 UTC
Labels: in triage
