### ISSUE TITLE
 childViewControllerForStatusBarHidden not implemented that blocking to close the full screen add

### ISSUE THREAD

**Issue by alihassan143** [googleads/googleads-mobile-flutter#648] opened 2022-09-14 07:32 UTC
## Plugin Version

  google_mobile_ads: ^2.0.1

## Issue

Status bar could not be hidden for full screen ad. Ensure that your app is configured to allow full screen ads to control the status bar. For example, consider whether you need to set the childViewControllerForStatusBarHidden property on your ad's rootViewController.

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```

flutter doctor -v
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.6 21G115 darwin-x64, locale en-PK)
    • Flutter version 3.3.1 on channel stable at /usr/local/Caskroom/flutter/3.3.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4f9d92fbbd (7 days ago), 2022-09-06 17:54:53 -0700
    • Engine revision 3efdf03e73
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • A878B2E8-784D-4362-9E75-556B5CE6F748 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 105.0.5195.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available 


```

</details>

**Comment by huycozy** [comment] 2022-09-14 10:10
Hi @alihassan143 
There was a closed issue https://github.com/googleads/googleads-mobile-flutter/issues/639 that had a workaround at https://github.com/googleads/googleads-mobile-flutter/issues/639#issuecomment-1237614700. Please try it to see if it can solve your issue.

**Comment by alihassan143** [comment] 2022-09-14 10:13
but that is not and ideal solution

**Comment by huycozy** [comment] 2022-09-14 11:58
>but that is not and ideal solution

@alihassan143 Can you provide more information about this?

**Comment by alihassan143** [comment] 2022-09-14 12:02
every time when full screen add open we have to show and hide the app bar by our self it should be inside the package

**Comment by huycozy** [comment] 2022-09-14 12:20
@alihassan143 thanks for responding.
Keeping this issue open for further insights from the team due to issue #639 has been finished by OP.

**Comment by timothyhoang-google** [comment] 2022-10-07 22:53
Similar to #191. We are still investigating. It's likely this is a native GMA SDK issue that must be resolved in the next granular release of the iOS and Android GMA SDKs.

**Comment by jjliu15** [comment] 2022-11-03 18:13
Closing as duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/191

**Closed by jjliu15** 2022-11-03 18:13 UTC
Labels: documentation, duplicate, platform-ios, interstitial ad
