### ISSUE TITLE
Ads placed in ListView is getting impression before they appear on the screen in Flutter 3

### ISSUE THREAD

**Issue by ilkanimal** [googleads/googleads-mobile-flutter#580] opened 2022-06-06 15:52 UTC
Hi, I originally posted this here https://github.com/googleads/googleads-mobile-flutter/issues/269#issuecomment-1059741368, before the new Android PlatformView implementation was merged with the stable channel, but this issue is now in Flutter 3 stable channel.

With the new Android PlatformView implementation, banner placed in `ListView` is getting impression before it appears on the screen.
This conflicts with Admob policy. (https://support.google.com/admob/answer/3269069?hl=en)
In the previous version, getting impression only when the first pixel of banner is seen on the screen.

This is a critical issue, apps using this plugin with Flutter 3 can be banned by Admob, because technically you are creating fake impressions with this implementation.

## Steps to Reproduce

To reproduce, try this example code with Flutter 3, plugin version doesn't matter.
```dart
class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: 15,
        itemBuilder: (context, index) {
          if (index != 0 && index % 5 == 0) {
            return const _BannerAd();
          }

          return Container(
            height: 200,
            color: Color((Random().nextDouble() * 0xFFFFFF).toInt())
                .withOpacity(1),
          );
        },
      ),
    );
  }
}

class _BannerAd extends StatefulWidget {
  const _BannerAd({Key? key}) : super(key: key);

  @override
  _BannerAdState createState() => _BannerAdState();
}

class _BannerAdState extends State<_BannerAd>
    with AutomaticKeepAliveClientMixin {
  @override
  bool get wantKeepAlive => true;

  late BannerAd myBanner;

  @override
  void initState() {
    super.initState();
    myBanner = BannerAd(
      adUnitId: BannerAd.testAdUnitId,
      size: AdSize.banner,
      request: const AdRequest(),
      listener: BannerAdListener(
        onAdLoaded: (ad) => print('Ad loaded.'),
        onAdFailedToLoad: (ad, error) {
          ad.dispose();
          print('Ad failed to load .');
        },
        onAdOpened: (ad) => print('Ad opened.'),
        onAdClosed: (ad) => print('Ad closed.'),
        onAdImpression: (ad) => print('Ad impression.'),
      ),
    )..load();
  }

  @override
  void dispose() {
    myBanner.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);

    return Container(
      width: myBanner.size.width.toDouble(),
      height: myBanner.size.height.toDouble(),
      margin: const EdgeInsets.all(20),
      alignment: Alignment.center,
      child: AdWidget(ad: myBanner),
    );
  }
}
```

**Expected results:** Ads placed in the ListView should get impression when they appear on the screen.

**Actual results:** All ads in ListView are simultaneously get impression when the ListView is built.

**Comment by maheshmnj** [comment] 2022-06-07 10:34
Hi @ilkanimal, Thanks for filing the issue.  The code sample looks fine, I will leave this issue for further investigation from the team.

**Comment by jjliu15** [comment] 2022-07-07 23:59
@bparrishMines could someone from the Flutter team could take a look at this issue?

I confirmed that this issue does not happen until cl/439863832, so most likely it's from the changes in https://github.com/flutter/flutter/pull/100091.

Previously the platform view is not attached until it becomes visible: https://screenshot.googleplex.com/BXdAFvVhNKFNzv8. 
Now the platform view is rendered off screen: https://screenshot.googleplex.com/8HHAMwoqaAeHQwz, and if you register a [ViewTreeObserver.OnGlobalLayoutListener](https://developer.android.com/reference/android/view/ViewTreeObserver.OnGlobalLayoutListener) on the platform view, you can see that the android system thinks the view is visible on the initial render.

**Comment by ilkanimal** [comment] 2022-07-08 10:41
@jjliu15 @bparrishMines also, impressions do not work correctly during navigation.
I have two lists on different screens that are synchronized to each other, and when I navigate to next screen and scroll the list, the ads on the previous screen continue to get impressions.
In a more common scenario, a video ad on the previous screen might keep playing until the end and get impression, which is technically a fraud.
I think there is a general lack of visibility states in this new PlatformView implementation.

**Comment by maheshmnj** [comment] 2022-07-08 12:23
Adding flutter label based on https://github.com/googleads/googleads-mobile-flutter/issues/580#issuecomment-1178384351

**Comment by bparrishMines** [comment] 2022-07-14 01:29
@jjliu15 You may be able to temporarily fix this by changing the default Android surface back to Hybrid Composition. You can change the line at: https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/lib/src/ad_containers.dart#L649 to use `initExpensiveAndroidView` instead of `initSurfaceAndroidView`.

Our team is still looking into the bugs caused by the new Android PlatformView implementaiton.

**Comment by ilkanimal** [comment] 2022-07-14 08:25
@bparrishMines I think using `initExpensiveAndroidView` for this package is not a good workaround because it causes a performance issue that makes apps almost unusable.

Those who are concerned about this issue can find a temporary solution using the [`visibility_detector`](https://pub.dev/packages/visibility_detector) package. You can still preload the ad but only show the `AdWidget` when `visibleFraction > 0.01`. This is not a sure solution, but it can keep the impression numbers at levels that would not make the Google Admob AI suspicious.

**Comment by ilkanimal** [comment] 2022-07-15 14:47
Also, this issue https://github.com/googleads/googleads-mobile-flutter/issues/608 is probably TLHC related. Clicking on the `AdWidget` in the `ListView` causes the `Invalid click coordinates detected.` error. However, if I don't put `AdWidget` in `ListView` and put it in `Expanded` to fill the screen, it doesn't cause the same error.

**Comment by jjliu15** [comment] 2022-08-17 20:09
[Version 2.0.1](https://github.com/googleads/googleads-mobile-flutter/releases/tag/v2.0.1) added the visibility_detector workaround mentioned in https://github.com/googleads/googleads-mobile-flutter/issues/580#issuecomment-1184149961. Could you help verify if this fixes the issue?

**Comment by dayron9110** [comment] 2022-10-11 22:05
News?

**Comment by bparrishMines** [comment] 2022-10-17 20:33
@jjliu15 is the AdView only visible on the initial render? It looks like we are using a default value of `(0.0, 0.0)` for the initial placement of the view: https://github.com/flutter/engine/blob/main/shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformViewsChannel.java#L121

**Comment by jjliu15** [comment] 2022-10-26 23:39
@bparrishMines  I tried checking out https://github.com/bparrishMines/flutter/tree/current_engine_main and commenting out the changes in https://github.com/googleads/googleads-mobile-flutter/pull/610/files. I'm still seeing the impression occur before the ad is scrolled into view.

**Comment by bparrishMines** [comment] 2022-10-28 14:26
Hmm, thats interesting. I'll check to verify that the Ad is being placed in the right position in the engine. Also, how are you testing for impressions? Are you using the `AdListener` callback?

**Comment by bparrishMines** [comment] 2022-10-28 17:53
I was using that as well, but I noticed that callback was being triggered before the platform view was even created. If you switch it to Hybrid Composition (`initExpensiveAndroidView`), the callback triggers before any of the platform view code runs too.

**Comment by jjliu15** [comment] 2022-10-31 21:38
@bparrishMines You're right. The ad response return from the Admob banner test ad unit actually uses a `loaded` impression definition and always fires the impression when the ad loads. However the [`AdManagerBannerAd`](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/reusable_inline_example.dart#L148) and [`NativeAd`](https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/example/lib/reusable_inline_example.dart#L128) test ads use a normal 1px impression, and I was originally able to reproduce the issue with those ads. However I'm no longer able to reproduce the issue with those ad types. 

I've also tried checking out older versions of flutter (3.0.0) and the plugin (2.0.0) and have not been able to reproduce the issue anymore.

However the issue is still reproducible in Google3, using blaze to run the test app (see cl/463890301). I'm not sure yet what's changed that's causing it to pass now on my local mac env vs in Google3.

**Comment by jjliu15** [comment] 2022-10-31 23:09
@bparrishMines I did some more testing and have confirmed that https://github.com/bparrishMines/flutter/tree/current_engine_main fixes the issue.
You can also verify by checking out https://github.com/jjliu15/googleads-mobile-flutter-1/tree/impression_bug and running the example app. 

After removing the visibility workaround and using `flutter:stable` the current behavior is:
- The test `BannerAd` uses a `loaded` impression definition, so it should not be used for testing this issue
- If you slowly scroll the `AdManagerBannerAd` and `NativeAd` into view, you'll see that their impressions are fired about half a screen before they are actually visible

After removing the visibility workaround and using https://github.com/bparrishMines/flutter/tree/current_engine_main, the impressions occur when the ad views are scrolled into view.

**Comment by abhinavsinghring** [comment] 2022-12-18 09:52
is it fixed now?

**Comment by ilkanimal** [comment] 2023-01-18 09:06
@jjliu15 @bparrishMines @stuartmorgan 

Will this fix https://github.com/flutter/flutter/pull/114103 be included in the next stable release? This issue has been going on for more than two quarters and it's a serious revenue loss issue as show rates have dropped significantly due to the current workaround.
Thanks for your work.

**Comment by stuartmorgan** [comment] 2023-01-18 11:25
> Will this fix [flutter/flutter#114103](https://github.com/flutter/flutter/pull/114103) be included in the next stable release?

Yes.

**Comment by stuartmorgan** [comment] 2023-01-18 12:38
The release cadence for `stable` is explained [here](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#stable).

**Comment by ilkanimal** [comment] 2023-01-25 11:14
Hi, since this issue is expected to be closed with the new Flutter stable release, I think there should be an opt-out option for the current workaround.
I have filed an issue here: https://github.com/googleads/googleads-mobile-flutter/issues/754

**Comment by westy92** [comment] 2023-03-30 04:28
Version 2.4.0 has been released with an opt-out flag for the fix on Flutter 3.7.0+.
https://pub.dev/packages/google_mobile_ads/changelog

**Closed** 2023-04-05 22:04 UTC
Labels: bug, p0-critical, banner ad, admob, flutter

**Comment by KristijanZic** [comment] 2023-05-17 20:05
I can still see the issue, I get the ad impression before like 3 tiles before the AdWidget tile comes into view inside the ListView. I get the same result with or without the opt-out option.

**Comment by Coreteams-harshit** [comment] 2023-08-16 06:25
As @KristijanZic mentioned above I am also facing the same issue where in a listview.builder. where if the ads are within 4 or 5 list items they are being said to be already already present in the 'widget tree' and requires to create a new instance, where as the next loaded add will work just fine and will not so any issue. I can provide a copy of my code file if any one can help me with this issue.
