### ISSUE TITLE
Google Ads don't work on iOS

### ISSUE THREAD

**Issue by RoyalCoder88** [googleads/googleads-mobile-flutter#624] opened 2022-08-04 15:17 UTC
Hi friends,

My Flutter Doctor:

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.22000.795], locale en-GB)
    • Flutter version 3.0.5 at C:\Users\burac\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\burac\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.
    • VS Code at C:\Users\burac\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.46.0

[√] Connected device (4 available)
    • SM A908B (mobile) • RFCMA02W5WT • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22000.795]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 104.0.5112.79
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 103.0.1264.77

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

My Test ads are displayed correctly on Android but no more on iOS, I get this error, please help me:

```
o get test ads on this device, set: Objective-C        GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"6490ca18f82177ab9c0739867ab4ae5d" ];Swift        
GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ @"6490ca18f82177ab9c0739867ab4ae5d" ]
<Google> Note that test device identifiers may be reset when uninstalling and reinstalling the application.<Google> 
<Google:HTML> A valid SKAdNetworkIdentifier for Google (cstr6suwn9.skadnetwork) is missing from Info.plist. 
See [Enable SKAdNetwork to track conversions] (https://googlemobileadssdk.page.link/enable-skadnetwork)flutter: Inline adaptive banner failedToLoad: LoadAdError(code: 1, domain: com.google.admob, message: 
Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))flutter: Inline adaptive banner failedToLoad: 
LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))
```

Any ideas why, thanks!

**Comment by huycozy** [comment] 2022-08-05 04:46
Hi @RoyalCoder88 
Based on your logs:
><Google:HTML> A valid SKAdNetworkIdentifier for Google (cstr6suwn9.skadnetwork) is missing from Info.plist. 

It looks like you have not completed the setup for `Info.plist` file. Please check this: https://developers.google.com/admob/ios/quick-start#update_your_infoplist

**Comment by expertdev-designer** [comment] 2022-08-09 10:43
@huycozy  is this issue fixed for you? 
i also have same issue ..android's ads showing well but not on iOS

**Comment by RoyalCoder88** [comment] 2022-08-09 11:58
Hi @huycozy, thanks I added these lines in my Info.plist:

> <key>GADApplicationIdentifier</key>
<string>ca-app-pub-3940256099942544~1458002511</string>
<key>SKAdNetworkItems</key>
  <array>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>cstr6suwn9.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>4fzdc2evr5.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>2fnua5tdw4.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>ydx93a7ass.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>5a6flpkh64.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>p78axxw29g.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>v72qych5uu.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>c6k4g5qg8m.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>s39g8k73mm.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>3qy4746246.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>3sh42y64q3.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>f38h382jlk.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>hs6bdukanm.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>prcb7njmu6.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>v4nxqhlyqp.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>wzmmz9fp6w.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>yclnxrl5pm.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>t38b2kh725.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>7ug5zh24hu.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>9rd848q2bz.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>n6fk4nfna4.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>kbd757ywx3.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>9t245vhmpl.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>4468km3ulz.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>2u9pt9hc89.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>8s468mfl3y.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>av6w8kgt66.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>klf5c3l5u5.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>ppxm28t8ap.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>424m5254lk.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>uw77j35x4d.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>578prtvx9j.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>4dzt52r2t5.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>e5fvkxwrpn.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>8c4e2ghe7u.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>zq492l623r.skadnetwork</string>
    </dict>
    <dict>
      <key>SKAdNetworkIdentifier</key>
      <string>3qcr597p9d.skadnetwork</string>
    </dict>
  </array>

But still, the ads are not showing in my app, I have configured also the test device etc. still the same problem :( 
```
  MobileAds.instance.initialize();

  List<String> testDeviceIds = [ ... ];
```

@expertdev-designer no I still not

**Comment by huycozy** [comment] 2022-08-09 12:31
Hi @RoyalCoder88, @expertdev-designer 
What type of ads are you having issues with?
And are you able to reproduce this issue when using sample code from https://github.com/googleads/googleads-mobile-flutter/tree/main/packages?

**Comment by expertdev-designer** [comment] 2022-08-09 12:58
Hii @huycozy Thanks for quick response
actually i am using this this package https://pub.dev/packages/google_mobile_ads with latest version also using ad manager ad unit 's id .Ads are showing well on Android but not on iOS devices as well on simulator.Two weeks ago ad's were showing but not now ,,i don't whats issue with iOS.

**Comment by RoyalCoder88** [comment] 2022-08-09 14:56
> Hii @huycozy Thanks for quick response actually i am using this this package https://pub.dev/packages/google_mobile_ads with latest version also using ad manager ad unit 's id .Ads are showing well on Android but not on iOS devices as well on simulator.Two weeks ago ad's were showing but not now ,,i don't whats issue with iOS.

It's exactly the same for me, I will post the log soon!

**Comment by huycozy** [comment] 2022-08-10 02:10
Hi @RoyalCoder88, @expertdev-designer 
Are you having this issue with all types of ads (banner, interstitial, native, open app) or just one of them?
And are you able to reproduce this issue when using sample code from https://github.com/googleads/googleads-mobile-flutter/tree/main/packages?

Please provide specific information indicated above so we can investigate properly. Thanks!

**Comment by expertdev-designer** [comment] 2022-08-10 04:40
@huycozy  I have issue with banner ads ..I integrated only banner ads in my app...Let me check with sample code

**Comment by RoyalCoder88** [comment] 2022-08-10 13:56
I just made a build test with the sample **googleads** on Android works like a charm but on iOS I still getting these errors:

```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(NativeAdError, Can't find NativeAdFactory with id: adFactoryExample, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      NativeAd.load (package:google_mobile_ads/src/ad_containers.dart:986:5)
<asynchronous suspension>
flutter: BannerAd failedToLoad: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))
flutter: RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))
flutter: RewardedInterstitialAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))
flutter: InterstitialAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [])).
flutter: AdManagerBannerAd loaded.
flutter: RewardedInterstitialAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))
flutter: RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))
flutter: InterstitialAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [])).
flutter: RewardedInterstitialAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))
flutter: InterstitialAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [])).
flutter: RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))



flutter: Anchored adaptive banner failedToLoad: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))
```

**Comment by expertdev-designer** [comment] 2022-08-11 12:35
@RoyalCoder88 Are you facing issue with test ad unit id  or your own ad id?

**Comment by expertdev-designer** [comment] 2022-08-11 12:39
<img width="347" alt="Screenshot 2022-08-11 at 6 07 28 PM" src="https://user-images.githubusercontent.com/52417551/184135136-d54ad6c7-fa8c-44f3-8df1-2a227e44a2eb.png">

**Comment by RoyalCoder88** [comment] 2022-08-11 12:46
> <img alt="Screenshot 2022-08-11 at 6 07 28 PM" width="347" src="https://user-images.githubusercontent.com/52417551/184135136-d54ad6c7-fa8c-44f3-8df1-2a227e44a2eb.png">
> 
> when i am using this testing ad unit id : /6499/example/banner' then testing ads are showing
> 
> but if am using my own id then ads are not showing

exactly the same :(

**Comment by expertdev-designer** [comment] 2022-08-11 12:48
@huycozy Please look into this issue

**Comment by jeevanson-vivriti** [comment] 2022-08-13 09:40
Facing the same issue. Test ads showing in Android but not in iOS emulators. 
`flutter: RewardedAd failed to load: LoadAdError(code: 9, domain: com.google.admob, message: Request Error: No ad to show from all configured ad networks., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))

InterstitialAd failed to load: LoadAdError(code: 9, domain: com.google.admob, message: Request Error: No ad to show from all configured ad networks., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [])).
`

**Comment by RoyalCoder88** [comment] 2022-08-13 11:58
I don't know what is wrong, I tested in so many ways, I don't know what to try anymore 😞

**Comment by huycozy** [comment] 2022-08-15 08:03
Hi guys, sorry for replying late. 
Do you guys have the similar log like this?

<details>
<summary>Logs</summary>

```bash
<Google> To get test ads on this device, set: 
Objective-C
	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ GADSimulatorID ];
Swift
	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ GADSimulatorID ]
<Google> User interactions must be disabled on the asset view to enable click handling.
userInteractionEnabled has been set to NO on <UIButton: 0x7fabe186d250; frame = (318 259.5; 47 34); opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <CALayer: 0x600002226260>>.
flutter: RewardedInterstitialAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: t_v5Yt6eHLiZ7APCm6m4Dg, mediationAdapterClassName: null, adapterResponses: []))
flutter: RewardedAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: t_v5YvzaHJakYPmev8AE, mediationAdapterClassName: null, adapterResponses: []))
flutter: BannerAd loaded.
flutter: AdManagerBannerAd loaded.
flutter: NativeAd loaded.
```
</details>

If so, please follow the guideline from the log by adding this code:

```
Objective-C
	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ GADSimulatorID ];
Swift
	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ GADSimulatorID ]
```

<details>
<summary>Demo (all ads formats are shown)</summary>


https://user-images.githubusercontent.com/104349824/184597749-afbbadf6-1513-4c67-80f5-edd103afb4d3.mp4


</details>

**Comment by expertdev-designer** [comment] 2022-08-16 04:55
Hii @huycozy Thank for look into this but test ad's showing well for me and @RoyalCoder88 in iOS .
but My test ad's not showing

**Comment by RoyalCoder88** [comment] 2022-08-16 12:37
Hi @huycozy thanks I will test right away, what you suggest ;) thanks!

BTW: where do we need to add this line?..in AppDelegate? Thanks!

**Comment by huycozy** [comment] 2022-08-16 16:25
@RoyalCoder88 
>BTW: where do we need to add this line?..in AppDelegate? Thanks!

Yes, let's add that line into `AppDelegate.m` file. For example:

```
@implementation AppDelegate
- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GeneratedPluginRegistrant registerWithRegistry:self];

  NativeAdFactoryExample *nativeAdFactory =
      [[NativeAdFactoryExample alloc] init];
  [FLTGoogleMobileAdsPlugin registerNativeAdFactory:self
                                          factoryId:@"adFactoryExample"
                                    nativeAdFactory:nativeAdFactory];

    GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ GADSimulatorID ];

  return [super application:application
      didFinishLaunchingWithOptions:launchOptions];
}
```

**Comment by RoyalCoder88** [comment] 2022-08-17 13:31
Hi @huycozy ,

I tried to add what you suggested but I got some problems :( can you guide me please

<img width="850" alt="Screenshot 2022-08-17 at 13 19 28" src="https://user-images.githubusercontent.com/6507433/185131786-a6fb5009-0b28-4a35-b0bc-2ad528ff4c89.png">

**Comment by huycozy** [comment] 2022-08-19 13:54
Hi @RoyalCoder88 
It looks like you are making the changes in `Swift` file instead of `Objective-C` file. Please read again https://github.com/googleads/googleads-mobile-flutter/issues/624#issuecomment-1214729520 for more detail, there is the guideline for `Objective-C` and `Swift` from the logs. In my case, I made the changes on `Objective-C` file: `AppDelegate.m`.

**Comment by keybow007** [comment] 2022-08-24 13:01
Still having the same issue on iOS even if I added the below code in AppDelegate.swift. Worked fine on Android.


![スクリーンショット 2022-08-24 21 51 27](https://user-images.githubusercontent.com/12907755/186424394-14f14727-af11-4b7c-905f-0e1e21cdcb7a.png)


（Error Log)
BannerAd
`ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []) | Request Error: No ad to show. | 1 | com.google.admob`

InterstitialAd
`LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: []))`

**Comment by huycozy** [comment] 2022-08-26 02:43
Hi @keybow007 
And are you able to reproduce this issue when using sample code from https://github.com/googleads/googleads-mobile-flutter/tree/main/packages?

**Comment by keybow007** [comment] 2022-08-26 05:46
Hi @huycozy 

Thanks for your reply.

When we ran the sample app you sent us with the app ID and ad ID on the actual iOS device, it displayed correctly.

However, when we changed the app ID and ad ID to those of our app in this sample app, the same error occurred.

The app that generated the error is registered with Admob and has a "ready" status, and there is no mistake in pasting the ID, so I am not sure what the cause is, but I will look into it further.

**Comment by expertdev-designer** [comment] 2022-08-26 11:56
@huycozy i added this 	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ GADSimulatorID ]
bot ads not showing yet

**Comment by huycozy** [comment] 2022-08-29 01:55
@keybow007 
For production Ads IDs, please follow issue #458 which is a known issue being tracked.

@expertdev-designer 
Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. Also, please provide the plugin version you are using as well. Thanks!

**Comment by expertdev-designer** [comment] 2022-09-14 08:15
Hii @RoyalCoder88 did you solve this issue?

**Comment by huycozy** [comment] 2022-09-21 07:50
@expertdev-designer 
As far as I can see from your log, the ads are loaded. If you have another issue, please file a new one and try to provide all information in the template so that we can verify it. 

@RoyalCoder88 
Given your last message, I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.
Thank you!

**Closed by huycozy** 2022-09-21 07:50 UTC
Labels: in triage

**Comment by expertdev-designer** [comment] 2022-09-28 10:17
@RoyalCoder88 Is your iOS app published or not ? is there any issue because of to if my app is not publish yet

**Comment by RoyalCoder88** [comment] 2022-09-28 11:45
Hi @expertdev-designer ,

No, it's not published yet, did you try to Ad the advertiser ID from Debug Console? 
If your advertize id from config is like 32138-32131-54783...etc. remove all the dashes, (321383213154783...) in this way it worked for me ;)

**Comment by expertdev-designer** [comment] 2022-10-05 12:44
Hii @RoyalCoder88 @huycozy 
This issue fixed for me.Thanks for your support.
I added this package https://pub.dev/packages/app_tracking_transparency then ads are showing.
I read this here : https://developers.google.com/admob/ios/ios14
