### ISSUE TITLE
Native Ads and Banner Ads show above the UI widgets

### ISSUE THREAD

**Issue by cmedamine** [googleads/googleads-mobile-flutter#588] opened 2022-06-23 17:10 UTC
## Plugin Version

google_mobile_ads: ^1.3.0

## Steps to Reproduce

**native ad widgets in separated file**

<details>
<summary>code sample</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

class NativeAdWidget extends StatefulWidget {
  const NativeAdWidget({Key? key}) : super(key: key);

  @override
  State<NativeAdWidget> createState() => _NativeAdWidgetState();
}

class _NativeAdWidgetState extends State<NativeAdWidget> {
  late final NativeAd _nativeAd;
  bool _nativeAdLoaded = false;

  final String _nativeAdUnit = Platform.isAndroid
      ? 'ca-app-pub-3940256099942544/2247696110'
      : 'ca-app-pub-3940256099942544/3986624511';

  @override
  void initState() {
    super.initState();
    _nativeAd = NativeAd(
      adUnitId: _nativeAdUnit,
      factoryId: 'listTile',
      listener: NativeAdListener(
        // Called when an ad is successfully received.
        onAdLoaded: (Ad ad) {
          debugPrint('Ad loaded.');
          setState(() {
            _nativeAdLoaded = true;
          });
        },
        // Called when an ad request failed.
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          // Dispose the ad here to free resources.
          ad.dispose();
          debugPrint('Ad failed to load: $error');
          setState(() {
            _nativeAdLoaded = false;
          });
        },
        // Called when an ad opens an overlay that covers the screen.
        onAdOpened: (Ad ad) => debugPrint('Ad opened.'),
        // Called when an ad removes an overlay that covers the screen.
        onAdClosed: (Ad ad) => debugPrint('Ad closed.'),
        // Called when an impression occurs on the ad.
        onAdImpression: (Ad ad) => debugPrint('Ad impression.'),
        // Called when a click is recorded for a NativeAd.
        onNativeAdClicked: (NativeAd ad) => debugPrint('Ad clicked.'),
      ),
      request: const AdRequest(),
    )..load();
  }

  @override
  void dispose() {
    super.dispose();
    _nativeAd.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_nativeAdLoaded) {
      return Container(

        margin: const EdgeInsets.symmetric(vertical: 4.0),
        color: Colors.white,
        width: MediaQuery.of(context).size.width,
        height: 70,
        child: AdWidget(ad: _nativeAd),
      );
    } else {
      return const SizedBox(height: 4);
    }
  }
}
```

**The List view to show the ads**
```
import 'package:deal_hunter/src/widgets/native_ad_widget.dart';

import '../services/api/deals.dart';
import 'package:internet_connection_checker/internet_connection_checker.dart';
import 'package:infinite_scroll_pagination/infinite_scroll_pagination.dart';
import 'package:provider/provider.dart';

import 'custom_loading_indicator.dart';
import 'deal_card.dart';
import '../models/deal.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

import '../../constants.dart';
import 'deal_hunter_icons.dart';

class PaginatedListView extends StatefulWidget {
  final Future<List<Deal>?> Function() loadDeals;
  final Deals deal;

  final Size size;

  const PaginatedListView({
    Key? key,
    required this.loadDeals,
    required this.deal,
    required this.size,
  }) : super(key: key);

  @override
  PaginatedListViewState createState() => PaginatedListViewState();
}

class PaginatedListViewState extends State<PaginatedListView> {
  final _pagingController = PagingController<int, Deal>(
    firstPageKey: 0,
  );

  Future<void> _fetchPage(int pageKey) async {
    try {
      final pageSetter = Provider.of<Deals>(context, listen: false);

      final dealItemsList = await widget.loadDeals();

      final nextPageKey = pageKey + 1;

      pageSetter.incrementPageNumber(nextPageKey);

      if (dealItemsList != null && dealItemsList.isEmpty) {
        _pagingController.appendLastPage(dealItemsList);
      } else {
        _pagingController.appendPage(dealItemsList!, nextPageKey);
      }
    } catch (error) {
      _pagingController.error = error;
    }
  }

  @override
  void initState() {
    super.initState();

    Provider.of<Deals>(context, listen: false).resetPage();
    _pagingController.addPageRequestListener((pageKey) {
      _fetchPage(pageKey);
    });
  }

  @override
  void dispose() {
    super.dispose();
    _pagingController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return RefreshIndicator(
      onRefresh: () => Future.sync(
        () => _pagingController.refresh(),
      ),
      child: PagedListView.separated(
        padding: const EdgeInsets.only(top: 8.0),
        addAutomaticKeepAlives: true,
        pagingController: _pagingController,
        separatorBuilder: (context, index) {
          if ((index + 1) % 4 == 0) {
            return const NativeAdWidget();
          } else {
            return const SizedBox(height: 4);
          }
        },
        builderDelegate: PagedChildBuilderDelegate<Deal>(
          itemBuilder: (context, deal, index) {
            return DealCard(
              useLocalStorage: false,
              title: deal.title,
              salePrice: deal.salePrice,
              thumb: deal.thumb,
              normalPrice: deal.normalPrice,
              lastChange: deal.lastChange,
              savings: deal.savings,
              dealRating: deal.dealRating,
              releaseDate: deal.releaseDate,
              metacriticScore: deal.metacriticScore,
              steamRatingPercent: deal.steamRatingPercent,
              storeId: deal.storeId,
              dealId: deal.dealId,
            );
          },
          firstPageErrorIndicatorBuilder: (context) {
            return FirstPageErrorIndicator(
              widget: widget,
              pagingController: _pagingController,
            );
          },
          noItemsFoundIndicatorBuilder: (context) => Center(
            child: SvgPicture.asset(
              emptyState,
              width: widget.size.width * .7,
            ),
          ),
          firstPageProgressIndicatorBuilder: (context) =>
              const CustomLargeLoadingIndicator(),
          newPageProgressIndicatorBuilder: (context) => const Center(
            child: CustomLargeLoadingIndicator(),
          ),
        ),
      ),
    );
  }
}

class FirstPageErrorIndicator extends StatelessWidget {
  const FirstPageErrorIndicator({
    Key? key,
    required this.widget,
    required PagingController<int, Deal> pagingController,
  })  : _pagingController = pagingController,
        super(key: key);

  final PaginatedListView widget;
  final PagingController<int, Deal> _pagingController;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: SizedBox(
        height: widget.size.height * .5,
        child: Column(
          children: [
            Expanded(
              child: SvgPicture.asset(
                error,
                width: widget.size.width * .7,
              ),
            ),
            FloatingActionButton(
              child: Icon(
                DealHunterIcons.refresh,
                size: 35,
                color: Theme.of(context).primaryColor,
              ),
              onPressed: () async {
                final isConnected =
                    await InternetConnectionChecker().hasConnection;

                if (isConnected) {
                  _pagingController.refresh();
                } else {
                  ScaffoldMessenger.of(context).hideCurrentSnackBar();
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text('No internet 😢, Please try again.'),
                      behavior: SnackBarBehavior.floating,
                    ),
                  );
                }
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
</details> 

**Flutter Doctor**

```
[✓] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Version 10.0.19044.1766], locale en-US)
    • Flutter version 3.0.2 at C:\Development\flutter-sdk\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Development\android-sdk
    • Platform android-31, build-tools 32.0.0
    • ANDROID_SDK_ROOT = C:\Development\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32516.85
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[✓] VS Code (version 1.68.1)
    • VS Code at C:\Users\Skywalker\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.42.0

[✓] Connected device (4 available)
    • hi6210sft (mobile) • QLF7N15A06000515 • android-arm64  • Android 5.0 (API 21)
    • Windows (desktop)  • windows          • windows-x64    • Microsoft Windows [Version 10.0.19044.1766]
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 102.0.5005.115
    • Edge (web)         • edge             • web-javascript • Microsoft Edge 102.0.1245.44

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Image 1| Image 2 |  Image 3
:-------------------------:|:-------------------------:|:-------------------------:
![Screenshot_2022-06-23-17-51-15](https://user-images.githubusercontent.com/68339403/175355962-9fbaa561-51e1-4abd-abc8-129cda060e2f.png) | ![Screenshot_2022-06-23-17-51-22](https://user-images.githubusercontent.com/68339403/175355974-24e7dc00-e2aa-4077-8aab-cb9fb2855eb1.png) | ![Screenshot_2022-06-23-17-51-44](https://user-images.githubusercontent.com/68339403/175355991-b152a353-2dfe-4afe-a740-f8d046e81437.png)

**Comment by maheshmnj** [comment] 2022-06-27 11:38
Hi @cmedamine, Thanks for filing the issue. I believe this issue is caused by a recent change in platforms views introduced in flutter 3.0. A similar instance of the issue   https://github.com/flutter/flutter/issues/103630 which has been fixed and landed on the latest master. This fix should land on stable in upcoming releases.
You may verify the fix by switching to master channel, You can switch to master channel by running 

```
flutter channel master
flutter upgrade
```

**Closed** 2022-07-18 12:08 UTC
Labels: feedback required, in triage
