### ISSUE TITLE
Native Ad - Image Responsiveness Issues

### ISSUE THREAD

**Issue by ldobreira** [googleads/googleads-mobile-flutter#582] opened 2022-06-08 03:26 UTC
## Plugin Version

google_mobile_ads: ^1.2.0

## Steps to Reproduce

1. Create a Native Ad
2. Create a listview with cards
3. Try to make the native ad look like the cards like this example: https://lh3.googleusercontent.com/KtEoccHt7kwMVm4GdhwA-DyEcd2DEQCqWZuiQi0z2OoBQOUkD0OUIgnb75iGqHSPCHmsoPjTvVS3LprzHGGDlR2S2YUrIt7fPJZ9=w0
4. First issue - I was only able to find 2 templates?! Small and medium sizes? The Flutter version of the official documentation is not really clear about it.
5. I used the medium size template, and just tried to move the image banner to the top of the ad to look more like a card using the xml template file.
6. Seems easy but to my surprise I was not able to make the banner image fit the card, the image is not using the full size horizontally or vertically properly. And since phone screens are different, the image banner always looks weird on different screens. Screenshot example here: https://drive.google.com/file/d/1AI-hXibMXlQv8_DYQaICfE6XrRdk3RUL/view?usp=sharing
7. Tried to change the xml file, and tried different sizes in the AdWidget without any success. I'm sure I'm missing something probably simple, but I was not able to find anything about it in the official documentation or examples.

**Expected results:** 

Trying to make the Native Ad to look like a card. Example: https://lh3.googleusercontent.com/KtEoccHt7kwMVm4GdhwA-DyEcd2DEQCqWZuiQi0z2OoBQOUkD0OUIgnb75iGqHSPCHmsoPjTvVS3LprzHGGDlR2S2YUrIt7fPJZ9=w0

**Actual results:** 

The image inside the Native does not fit the card properly, and always looks out of place on different mobile screens: Screenshot example here: https://drive.google.com/file/d/1AI-hXibMXlQv8_DYQaICfE6XrRdk3RUL/view?usp=sharing

I changed the xml template file several times, and tried different sizes in the AdWidget without any success. I'm sure I'm missing something probably simple, but I was not able to find anything about it in the official documentation or examples.

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by maheshmnj** [comment] 2022-06-08 10:33
Hi @ldobreira, Thanks for filing the issue. Can you please share a minimal and complete sample project(which I can directly run with minimal or no changes) to investigate further?

**Comment by ldobreira** [comment] 2022-06-08 23:25
Hi @maheshmnj! Thank you for your fast reply.

Sure, I made an example for you at https://github.com/ldobreira/testnativeadcard

Please let me know what I'm missing.

**Comment by ldobreira** [comment] 2022-06-14 15:54
Hi @maheshmnj, unfortunately, it's not working in all screen sizes... If you change the Container padding around the cards (or emulate other devices) you can easily reproduce the issue... Please check the example at https://imgur.com/a/O9sgOJJ

**Comment by maheshmnj** [comment] 2022-06-20 12:53
Thanks for the update @ldobreira, I don't have much idea on the native code. I am labeling this issue for further insights from the team.

sample project can be found here https://github.com/googleads/googleads-mobile-flutter/issues/582#issuecomment-1150510781

cc: @jjliu15

**Comment by timothyhoang-google** [comment] 2022-07-27 21:26
@ldobreira - Can you confirm whether you are using AdMob or Ad Manager? 
- For Ad Manager, you can request fluid size native ads, which contain assets that expand into the available inventory space. 
- For AdMob, there is only support for the small and medium templates, which can receive fixed size assets which may create whitespace when inflated into the available inventory space. This occurs because the aspect ratio of the advertiser provided images must be preserved.

**Comment by ldobreira** [comment] 2022-07-27 22:23
> @ldobreira - Can you confirm whether you are using AdMob or Ad Manager?
> 
>     * For Ad Manager, you can request fluid size native ads, which contain assets that expand into the available inventory space.
> 
>     * For AdMob, there is only support for the small and medium templates, which can receive fixed size assets which may create whitespace when inflated into the available inventory space. This occurs because the aspect ratio of the advertiser provided images must be preserved.

I'm just using Admob.... what should be the standard size for the medium templates?

**Comment by timothyhoang-google** [comment] 2022-08-01 14:25
The standard size for medium rectangle ads is 300x250. This size tends to have more ad inventory available from advertisers. The fixed sizes that tend to have more ad inventory available (and are therefore more likely to serve) follow [IAB standard ad size specifications](https://www.iab.com/wp-content/uploads/2019/04/IABNewAdPortfolio_LW_FixedSizeSpec.pdf). 

Since native ads can be of arbitrary size, there will be whitespace around the ad image whenever the native ad image container is larger than the image asset. For Fluid native assets, whitespace can still occur around the image if the native ad image container has an aspect ratio that doesn't match the image asset aspect ratio.

@ldobreira - since you're using AdMob, I suspect [this issue](https://drive.google.com/file/d/1AI-hXibMXlQv8_DYQaICfE6XrRdk3RUL/view) is occurring because the native image asset doesn't match the image container precisely. Unfortunately this is working as intended as not all advertisers campaigns are capable for supporting fluid.

I'll close this issue but feel free to reopen if you think there is a problem with native rendering (e.g. image asset in ad response should actually fit the native ad image container).

**Closed** 2022-08-01 14:26 UTC
Labels: bug, p3-low, platform-android, native ad
