### ISSUE TITLE
Google Mobile Ads 1.0.5 - Deprecated API.

### ISSUE THREAD

**Issue by DabPb** [googleads/googleads-mobile-flutter#1121] opened 2024-07-01 09:58 UTC
When I try to run application, generate signed apk or app bundle I face this warning of uses or overrides a deprecated API. Please help me to resolve this for android apps.
### Error
```
Note: /Users/user/.pub-cache/hosted/pub.dev/google_mobile_ads-5.1.0/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterRequestAgentProvider.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓ Built build/app/outputs/flutter-apk/app-debug.apk
Installing build/app/outputs/flutter-apk/app-debug.apk...
```
I used **Android Studio Koala | 2024.1.1**
### Flutter version
```
Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (4 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3
```
### Flutter Doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.22.2, on macOS 12.7.5 21H1222 darwin-x64, locale en-US)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/3.0.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/user/Library/Android/flutter. Consider adding /Users/user/Library/Android/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 14.2)
    ! Flutter recommends a minimum Xcode version of 15.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (2 available)
    ! Device 192.0.0.4:5555 is offline.
[✓] Network resources

! Doctor found issues in 2 categories.
```

**Comment by malandr2** [comment] 2024-07-01 14:27
This is a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/1089, which has been resolved and will be officially fixed in the next release. Thanks for flagging

**Closed by malandr2** 2024-07-01 14:27 UTC
