### ISSUE TITLE
[app_open] Critical : Disruptive Ads - PlayStore rejection

### ISSUE THREAD

**Issue by EArminjon** [googleads/googleads-mobile-flutter#979] opened 2023-12-16 14:33 UTC
## Plugin Version

4.0.0

### [REQUIRED] Step 2: Describe the problem

PlayStore rejection because of Disruptive Ads.

## Steps to Reproduce

1. Clone https://github.com/googleads/googleads-mobile-flutter.git
2. Run app_open_example project.
3. After launch, put app in background and then put app in foreground
4. Most of the time, ad will appear and user can not during the first few second dismiss the app by clicking on back button.
5. That lead to a playstore rejection for Disruptive Ads.

**Expected results:** 

On back button : app should be dismissed (normal behavior I mean if we didn't use will pop scope or stuff like this) or ad should be dismissed.

**Actual results:** 

Nothing happen and randomly the back button will work after a period.

<details>
  <summary>Logs from logcat (back button spammed until ad dismissed)</summary>

```
... LOGS CUTTED ELSE TOO LONG
2023-12-16 15:31:34.590   624-645   AutofillManagerService  system_process                       D  onBackKeyPressed()
2023-12-16 15:31:34.590   624-645   RemoteAugm...illService system_process                       E  Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2023-12-16 15:31:34.738   624-645   AutofillManagerService  system_process                       D  onBackKeyPressed()
2023-12-16 15:31:34.738   624-645   RemoteAugm...illService system_process                       E  Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2023-12-16 15:31:34.894   624-645   AutofillManagerService  system_process                       D  onBackKeyPressed()
2023-12-16 15:31:34.895   624-645   RemoteAugm...illService system_process                       E  Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2023-12-16 15:31:35.100   624-645   AutofillManagerService  system_process                       D  onBackKeyPressed()
2023-12-16 15:31:35.101   624-645   RemoteAugm...illService system_process                       E  Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2023-12-16 15:31:35.246   624-645   AutofillManagerService  system_process                       D  onBackKeyPressed()
2023-12-16 15:31:35.246   624-645   RemoteAugm...illService system_process                       E  Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2023-12-16 15:31:35.408   624-645   AutofillManagerService  system_process                       D  onBackKeyPressed()
2023-12-16 15:31:35.409   624-645   RemoteAugm...illService system_process                       E  Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2023-12-16 15:31:35.569   624-645   AutofillManagerService  system_process                       D  onBackKeyPressed()
2023-12-16 15:31:35.569   624-645   RemoteAugm...illService system_process                       E  Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService
2023-12-16 15:31:35.590   624-1245  ActivityTaskManager     system_process                       W  Duplicate finish request for r=ActivityRecord{94a3467 u0 com.example.app_open_example/com.google.android.gms.ads.AdActivity} t17 f}}
2023-12-16 15:31:35.613 17791-17791 Ads                     com.example.app_open_example         W  #004 The webview is destroyed. Ignoring action.
2023-12-16 15:31:35.614 17791-17791 Ads                     com.example.app_open_example         W  #004 The webview is destroyed. Ignoring action.
2023-12-16 15:31:35.615 17791-17791 Ads                     com.example.app_open_example         W  #004 The webview is destroyed. Ignoring action.
2023-12-16 15:31:35.615 17791-18257 flutter                 com.example.app_open_example         I  Instance of 'AppOpenAd' onAdDismissedFullScreenContent

```

```
```

```
[!] Flutter (Channel stable, 3.16.4, on Microsoft Windows [version 10.0.19045.3570], locale fr-FR)
    • Flutter version 3.16.4 on channel stable at C:\Users\engue\fvm\versions\3.16.4
    ! The flutter binary is not on your path. Consider adding C:\Users\engue\fvm\versions\3.16.4\bin to your path.
    ! The dart binary is not on your path. Consider adding C:\Users\engue\fvm\versions\3.16.4\bin to your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (5 days ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\Android
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Users\engue\AppData\Local\Programs\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2019 16.11.18)
    • Visual Studio at D:\dev
    • Visual Studio Community 2019 version 16.11.32802.440
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Users\engue\AppData\Local\Programs\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
    • IntelliJ at C:\Users\engue\AppData\Local\Programs\IntelliJ IDEA Ultimate
    • Flutter plugin version 77.0.1
    • Dart plugin version 233.11799.172

[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [version 10.0.19045.3570]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 120.0.6099.109
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 119.0.2151.72

[√] Network resources
    • All expected network resources are available.

```

</details>

**Comment by EArminjon** [comment] 2023-12-16 14:35
I also spammed the Google PlayStore team to got more info about the rejection but all i found was this error.

Also I remember have opened a similar issue for simple Interstitial by the past which was closed without fix : https://github.com/googleads/googleads-mobile-flutter/issues/211
I couldn't reopen it because the option was greyed.

**Comment by malandr2** [comment] 2023-12-19 18:57
Hi @EArminjon are you able to replicate this issue with the test ad units, or production ads? I see the loading spinner appear and then display `"Continue to app"'. Are you referring to the loading spinner appearing for x amount of time?

![Screenshot_1703012197](https://github.com/googleads/googleads-mobile-flutter/assets/5905170/19956eb9-efb0-4b6e-9ec7-d7aeb3960429)

**Comment by EArminjon** [comment] 2023-12-19 19:03
> Hi @EArminjon are you able to replicate this issue with the test ad units, or production ads? I see the loading spinner appear and then display `"Continue to app"'. Are you referring to the loading spinner appearing for x amount of time?
> 
> ![Screenshot_1703012197](https://private-user-images.githubusercontent.com/5905170/291686718-19956eb9-efb0-4b6e-9ec7-d7aeb3960429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMTI1ODgsIm5iZiI6MTcwMzAxMjI4OCwicGF0aCI6Ii81OTA1MTcwLzI5MTY4NjcxOC0xOTk1NmViOS1lZmIwLTRiNmUtOWVjNy1kN2FlYjM5NjA0MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTg1ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQwNzEwM2FmNTVjYjQ0MjJiM2JjMDlhNjM0NDEyZGJmYjU5OGEwYTI3NmI5MTVkMmFlNjQ3OTUxOTU1ZWRhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.g6PzWlXV2E9NFkT22TuxnYKhVIXWBHA8qKGZfPL59kY)

Issue be reproduced for both Test and Pro ads.
Even after or during loading indicator, back button didn't work.

**Comment by malandr2** [comment] 2023-12-19 19:19
@EArminjon can you send over a recording of the issue you're describing? When you say even after the loading indicator, the "Continue to app" button doesn't work? I was unable to reproduce the button not working after the loading indicator transitioned to text.

**Comment by EArminjon** [comment] 2023-12-19 19:41
Find bellow the video : 
I spammed during 35s the back button until it work.
https://drive.google.com/file/d/1FysApCg7rKMoNJM6yAcuGNPWKTiGOdX7/view?usp=drive_link

**Comment by malandr2** [comment] 2023-12-19 20:31
@EArminjon Thank you for providing that video, I was clicking on the ad and not the device's back button. Now I can replicate your issue. I can also replicate the issue in our [Android App Open Example app](https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/AppOpenExample). This leads to me to believe that the issue is not a google_mobile_ads plugin issue but rather associated with the Android platform. The next step for you would be to create a thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk), include that video you sent over and it will be addressed by our team. Closing this issue out. Thanks!

**Closed by malandr2** 2023-12-19 20:31 UTC
Labels: in triage
