### ISSUE TITLE
Bad performance on Android

### ISSUE THREAD

**Issue by erperejildo** [googleads/googleads-mobile-flutter#334] opened 2021-08-09 23:43 UTC
## Plugin Version

google_mobile_ads: ^0.12.1+1 

## Details

Facing some bad performance issues on Android when displaying banner:
https://youtu.be/khZ86bb8ErE

Ad service:

```
import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:my_rents/main.dart';

// You can also test with your own ad unit IDs by registering your device as a
// test device. Check the logs for your device's ID value.
const String testDevice = 'YOUR_DEVICE_ID';

String get bannerAdUnitId => Platform.isAndroid
    ? 'ca-app-pub-29452252'
    : 'ca-app-pub-2947209';
String get interstitialUnitId => Platform.isAndroid
    ? 'ca-app-pub-29111328'
    : 'ca-app-pub-29450679613';
String get rewardeUnitId => Platform.isAndroid
    ? 'ca-app-pub-294502796'
    : 'ca-app-pub-2945024989';
String get nativeAdUnitId => Platform.isAndroid
    ? 'ca-app-pub-29472397'
    : 'ca-app-pub-294502429013';

class AdState extends ChangeNotifier {
  bool showAds = false;

  final AdRequest request = AdRequest(
    // testDevices: <String>[testDevice],
    keywords: <String>['rents', 'rentals', 'financial', 'state agent'],
    nonPersonalizedAds: false,
  );

  InterstitialAd? interstitialAd;
  bool interstitialReady = false;

  RewardedAd? rewardedAd;
  bool rewardedReady = false;

  void toggleAds(bool state) {
    showAds = state;
    notifyListeners();
  }

  void createInterstitialAd() {
    interstitialAd ??= InterstitialAd(
      adUnitId: interstitialUnitId,
      request: request,
      listener: AdListener(
        onAdLoaded: (Ad ad) {
          interstitialReady = true;
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          ad.dispose();
          interstitialAd = null;
          createInterstitialAd();
        },
        onAdOpened: (Ad ad) => {},
        onAdClosed: (Ad ad) {
          ad.dispose();
          createInterstitialAd();
        },
        onApplicationExit: (Ad ad) => {},
      ),
    )..load();
  }

  // TODO: not being used. Find listener for onRewardedAdUserEarnedReward
  void createRewardedAd() {
    rewardedAd ??= RewardedAd(
      adUnitId: rewardeUnitId,
      request: request,
      listener: AdListener(
          onAdLoaded: (Ad ad) {
            rewardedReady = true;
          },
          onAdFailedToLoad: (Ad ad, LoadAdError error) {
            ad.dispose();
            rewardedAd = null;
            createRewardedAd();
          },
          onAdOpened: (Ad ad) => print('${ad.runtimeType} onAdOpened.'),
          onAdClosed: (Ad ad) {
            ad.dispose();
            createRewardedAd();
          },
          onApplicationExit: (Ad ad) =>
              print('${ad.runtimeType} onApplicationExit.'),
          onRewardedAdUserEarnedReward: (RewardedAd ad, RewardItem reward) {
            print(
              '$RewardedAd with reward $RewardItem(${reward.amount}, ${reward.type})',
            );
          }),
    )..load();
  }

  void showInterstitialAd() {
    if (showAds) {
      interstitialAd!.show();
      interstitialReady = false;
      interstitialAd = null;
    }
  }

  void showRewardedAd() {
    if (rewardedAd == null) createRewardedAd();
    rewardedAd!.show();
    rewardedReady = false;
    rewardedAd = null;
  }
}

class BannerAdWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => BannerAdState();
}

class BannerAdState extends State<BannerAdWidget> {
  late BannerAd _bannerAd;
  final Completer<BannerAd> bannerCompleter = Completer<BannerAd>();

  @override
  void initState() {
    super.initState();
    _bannerAd = BannerAd(
      adUnitId: bannerAdUnitId,
      request: AdRequest(),
      size: Platform.isAndroid ? AdSize.smartBanner : AdSize.fullBanner,
      listener: AdListener(
        onAdLoaded: (Ad ad) {
          bannerCompleter.complete(ad as BannerAd);
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          ad.dispose();
          bannerCompleter.completeError(error);
        },
        onAdOpened: (Ad ad) => {},
        onAdClosed: (Ad ad) => {},
        onApplicationExit: (Ad ad) => {},
      ),
    );
    Future<void>.delayed(Duration(seconds: 1), () => _bannerAd.load());
  }

  @override
  void dispose() {
    super.dispose();
    _bannerAd.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<BannerAd>(
      future: bannerCompleter.future,
      builder: (BuildContext context, AsyncSnapshot<BannerAd> snapshot) {
        Widget child;

        switch (snapshot.connectionState) {
          case ConnectionState.none:
          case ConnectionState.waiting:
          case ConnectionState.active:
            child = Container();
            break;
          case ConnectionState.done:
            if (snapshot.hasData) {
              child = AdWidget(ad: _bannerAd);
            } else {
              child = Text('Error loading $BannerAd');
            }
        }

        return child;
      },
    );
  }
}

class NativeAdWidget extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => NativeAdState();
}

class NativeAdState extends State<NativeAdWidget> {
  late NativeAd _nativeAd;
  final Completer<NativeAd> nativeAdCompleter = Completer<NativeAd>();

  @override
  void initState() {
    super.initState();
    _nativeAd = NativeAd(
      adUnitId: nativeAdUnitId,
      request: AdRequest(),
      factoryId: 'adFactoryExample',
      listener: AdListener(
        onAdLoaded: (Ad ad) {
          print('$NativeAd loaded.');
          nativeAdCompleter.complete(ad as NativeAd);
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          ad.dispose();
          print('$NativeAd failedToLoad: $error');
          nativeAdCompleter.completeError(error);
        },
        onAdOpened: (Ad ad) => print('$NativeAd onAdOpened.'),
        onAdClosed: (Ad ad) => print('$NativeAd onAdClosed.'),
        onApplicationExit: (Ad ad) => print('$NativeAd onApplicationExit.'),
      ),
    );
    Future<void>.delayed(Duration(seconds: 1), () => _nativeAd.load());
  }

  @override
  void dispose() {
    super.dispose();
    _nativeAd.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<NativeAd>(
      future: nativeAdCompleter.future,
      builder: (BuildContext context, AsyncSnapshot<NativeAd> snapshot) {
        Widget child;

        switch (snapshot.connectionState) {
          case ConnectionState.none:
          case ConnectionState.waiting:
          case ConnectionState.active:
            child = Container();
            break;
          case ConnectionState.done:
            if (snapshot.hasData) {
              child = AdWidget(ad: _nativeAd);
            } else {
              child = Text('Error loading $NativeAd');
            }
        }

        return Container(
          width: double.infinity,
          height: nativeHeight,
          color: Colors.blueGrey,
          child: child,
        );
      },
    );
  }
}

final AdState adState = AdState();
```

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

<details>
<summary>Logs</summary>

```
flutter analyze
Analyzing my_rents...                                                   

   info • Don't import implementation files from another package • lib/generated_plugin_registrant.dart:8:8 • implementation_imports
   info • The value of the local variable 'daysFromTodayToEndDate' isn't used • lib/helpers/helpers.dart:422:9 • unused_local_variable
   info • The value of the local variable 'daysFromTodayToStartDate' isn't used • lib/helpers/helpers.dart:423:9 • unused_local_variable
   info • The value of the local variable 'locale' isn't used • lib/helpers/helpers.dart:525:12 • unused_local_variable
   info • The operand can't be null, so the condition is always true • lib/models/invoice.dart:22:29 • unnecessary_null_comparison
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/screens/Invoices/invoice_details.dart:33:36 •
          deprecated_member_use
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/screens/Invoices/my_invoice.dart:476:43 •
          deprecated_member_use
   info • The operand can't be null, so the condition is always true • lib/screens/Invoices/taxes_withholdings.dart:132:46 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/screens/Invoices/taxes_withholdings.dart:184:44 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/screens/Invoices/taxes_withholdings.dart:207:22 • unnecessary_null_comparison
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: TaxesWithholdingsGroupsScreen._mainColor •
          lib/screens/Invoices/taxes_withholdings_group.dart:14:7 • must_be_immutable
   info • The value of the local variable 'size' isn't used • lib/screens/Login/components/body.dart:30:10 • unused_local_variable
   info • The value of the field '_events' isn't used • lib/screens/calendar.dart:17:37 • unused_field
   info • The declaration '_fileDownloadProgress' isn't referenced • lib/screens/expense.dart:637:10 • unused_element
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/screens/lease.dart:355:39 • deprecated_member_use
   info • The operand can't be null, so the condition is always true • lib/screens/new_event.dart:229:32 • unnecessary_null_comparison
   info • The value of the field '_invoiceFile' isn't used • lib/screens/new_expense.dart:72:9 • unused_field
   info • The value of the field '_invoiceUrl' isn't used • lib/screens/new_expense.dart:73:11 • unused_field
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/screens/new_expense.dart:727:41 •
          deprecated_member_use
   info • The declaration '_total' isn't referenced • lib/screens/new_expense.dart:745:10 • unused_element
   info • The declaration '_buildCurrencyDialogItem' isn't referenced • lib/screens/options.dart:247:10 • unused_element
   info • The declaration '_generateBorderRadius' isn't referenced • lib/screens/portfolio_info.dart:644:3 • unused_element
   info • The declaration '_statOptions' isn't referenced • lib/screens/portfolio_info.dart:653:3 • unused_element
   info • The value of the field '_selectedEvents' isn't used • lib/screens/rent.dart:65:22 • unused_field
   info • The value of the field '_isLoading' isn't used • lib/screens/rent.dart:73:13 • unused_field
   info • The declaration '_pickImageOptions' isn't referenced • lib/screens/rent.dart:683:3 • unused_element
   info • The declaration '_showPaymentConfirmation' isn't referenced • lib/screens/rent.dart:1102:10 • unused_element
   info • The declaration '_calendarActions' isn't referenced • lib/screens/rent.dart:1238:10 • unused_element
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/screens/rent.dart:1261:39 • deprecated_member_use
   info • The value of the local variable 'createPaymentDayEventCopy' isn't used • lib/screens/rent.dart:1281:21 • unused_local_variable
   info • The declaration '_fileDownloadProgress' isn't referenced • lib/screens/rent.dart:2116:10 • unused_element
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/screens/rent.dart:2327:45 • deprecated_member_use
   info • The declaration '_stopLease' isn't referenced • lib/screens/rent.dart:2584:10 • unused_element
   info • The declaration '_deleteDocument' isn't referenced • lib/screens/rent.dart:2745:3 • unused_element
   info • The operand can't be null, so the condition is always true • lib/screens/rent.dart:2848:11 • unnecessary_null_comparison
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/screens/rent.dart:2855:16 • deprecated_member_use
   info • Equality operator `==` invocation with references of unrelated types • lib/screens/rent.dart:2926:25 • unrelated_type_equality_checks
   info • The declaration '_buildActionForTask' isn't referenced • lib/screens/rent.dart:2949:10 • unused_element
   info • The value of the field '_events' isn't used • lib/screens/table_events.dart:57:37 • unused_field
   info • The value of the local variable 'snackBar' isn't used • lib/screens/table_events.dart:380:31 • unused_local_variable
   info • The declaration '_updatePaymentDate' isn't referenced • lib/screens/table_events.dart:492:3 • unused_element
   info • The declaration '_removePayDays' isn't referenced • lib/screens/table_events.dart:504:3 • unused_element
   info • Cancel instances of dart.async.StreamSubscription • lib/screens/versions.dart:25:23 • cancel_subscriptions
   info • 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in flutter.dev/go/material-button-migration-guide). This feature was deprecated after
          v1.26.0-18.0.pre. • lib/screens/versions.dart:340:12 • deprecated_member_use
   info • The value of the field '_db' isn't used • lib/services/auth.dart:25:27 • unused_field
   info • The value of the local variable 'user' isn't used • lib/services/auth.dart:41:18 • unused_local_variable
   info • The value of the local variable 'user' isn't used • lib/services/auth.dart:67:18 • unused_local_variable
   info • The operand can't be null, so the condition is always true • lib/services/create_invoice_pdf.dart:160:18 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/services/create_invoice_pdf.dart:161:18 • unnecessary_null_comparison
   info • The operand can't be null, so the condition is always true • lib/services/create_invoice_pdf.dart:162:18 • unnecessary_null_comparison
   info • The declaration '_formatDate' isn't referenced • lib/services/create_invoice_pdf.dart:659:8 • unused_element
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/services/phone_contact.dart:49:28 •
          deprecated_member_use
   info • The declaration '_showError' isn't referenced • lib/services/phone_contact.dart:53:3 • unused_element
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/services/phone_contact.dart:57:26 •
          deprecated_member_use
   info • The value of the local variable '_timer' isn't used • lib/widgets/important_message.dart:9:11 • unused_local_variable
   info • 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. • lib/widgets/important_message.dart:20:25 •
          deprecated_member_use
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: MySwitch.param, MySwitch.callback • lib/widgets/my_switch.dart:4:7
          • must_be_immutable
   info • The operand can't be null, so the condition is always true • lib/widgets/phone_number_selector.dart:42:49 • unnecessary_null_comparison
   info • The value of the local variable 'deletedPortfolio' isn't used • lib/widgets/portfolio_options.dart:59:23 • unused_local_variable
   info • The value of the local variable 'eventListener' isn't used • lib/widgets/rents.dart:85:19 • unused_local_variable
   info • Name types using UpperCamelCase • lib/widgets/taxes_groups_dropdown.dart:134:9 • camel_case_types

61 issues found. (ran in 11.1s)

```

```
 flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/dani/development/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dani/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android 10 (API 29) (emulator)
    • iPhone X iOS 13 (mobile)           • FADD3176-C4E8-4DA4-83DD-E6C2D30D9498 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 92.0.4515.131

• No issues found!

```

</details>

**Comment by erkihindo** [comment] 2021-08-13 06:59
Same with 0.13.3, everything is so slow when banner is shown

**Comment by anuragsoni300** [comment] 2021-08-13 07:26
same #318

**Comment by maheshmnj** [comment] 2021-08-16 05:29
closing this issue as a duplicate of #318

**Closed by maheshmnj** 2021-08-16 05:29 UTC
Labels: in triage
