### ISSUE TITLE
NullPointerException in version 3.0.0

### ISSUE THREAD

**Issue by Tobias-Keller** [googleads/googleads-mobile-flutter#838] opened 2023-05-09 07:37 UTC
## Plugin Version
3.0.0
Flutter 3.7.12 

## Steps to Reproduce
App crashes only in Live Build on the following device:
- Redmi spesn (Redmi Note 11
- Android 12 SDK 31

**Expected results:** 
App should not crash

**Actual results:** 
App crashes with the following stacktrace:

Typ: java.lang.NullPointerException. 

`Exception java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.size()' on a null object reference
  at android.os.Parcel.createExceptionOrNull (Parcel.java:2432)
  at android.os.Parcel.createException (Parcel.java:2410)
  at android.os.Parcel.readException (Parcel.java:2393)
  at android.os.Parcel.readException (Parcel.java:2335)
  at android.view.IWindowManager$Stub$Proxy.getSupportedDisplayHashAlgorithms (IWindowManager.java:6342)
  at android.view.displayhash.DisplayHashManager.getSupportedHashAlgorithms (DisplayHashManager.java:71)
  at com.google.android.gms.ads.eventattestation.internal.l.<init> (:com.google.android.gms.policy_ads_fdr_dynamite@231004601@231004600057.513700577.513700577:2)
  at com.google.android.gms.ads.nonagon.ad.j.e (:com.google.android.gms.policy_ads_fdr_dynamite@231004601@231004600057.513700577.513700577:9)
  at com.google.android.gms.ads.nonagon.ad.g.run (:com.google.android.gms.policy_ads_fdr_dynamite@231004601@231004600057.513700577.513700577)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
  at java.lang.Thread.run (Thread.java:1012)`

**Comment by huycozy** [comment] 2023-05-09 09:32
Hi @Tobias-Keller 
This is a known issue at https://github.com/googleads/googleads-mobile-flutter/issues/821. It has been addressed that it is caused by Android GMS on the device.

Closing this issue as a duplicate.

**Closed by huycozy** 2023-05-09 09:32 UTC
