### ISSUE TITLE
Could not get unknown property 'android' for project ':webview_flutter_android' of type org.gradle.api.Project

### ISSUE THREAD

**Issue by yokoyama899** [googleads/googleads-mobile-flutter#923] opened 2023-09-22 10:26 UTC
Failed to notify project evaluation listener.
2
   > Could not get unknown property 'android' for project ':webview_flutter_android' of type org.gradle.api.Project.
   
Cannot build
   
![スクリーンショット 2023-09-22 192410](https://github.com/googleads/googleads-mobile-flutter/assets/87350249/2856e476-095d-448e-a0f1-2e78991dac26)

[√] Flutter (Channel stable, 3.13.2, on Microsoft Windows [Version 10.0.22621.2283], locale ja-JP)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.82.2)
[√] Connected device (4 available)
[√] Network resources

**Comment by yokoyama899** [comment] 2023-09-22 10:28
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':webview_flutter_android'.
> Could not load compiled classes for build file 'C:\Users\myname\AppData\Local\Pub\Cache\hosted\pub.dev\webview_flutter_android-3.10.1\android\build.gradle' from cache.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':webview_flutter_android' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':webview_flutter_android' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by huycozy** [comment] 2023-09-22 11:38
Hi @yokoyama899 
Is this issue caused by ad plugin? (as I see there is an error with `webview_flutter_android` package instead). This looks like an issue with gradle version, please check [this](https://stackoverflow.com/questions/62071166/could-not-get-unknown-property-android-for-project-shared-preferences-of-ty) to see if it helps.

**Comment by huycozy** [comment] 2023-09-27 11:07
Sorry for replying late. I just tried adding `webview_flutter` plugin to my existing project which had ads plugin already, but can't reproduce this issue. 

Please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that doesn’t include other 3rd party plugins or complex production code so that we may verify this. 

Thank you!

**Comment by Aashrut** [comment] 2023-09-30 10:41
@yokoyama899 , did you try cleaning project with `flutter clean`? And then get the dependencies using `pub get`, and then upgrade them using `pub upgrade`.
And if that didn't work, then 'Open android module in Android Studio', and then use AGP upgrade assistant to upgrade the gradle, then go to settings and then Kotlin Compiler to check if you are using compatible Kotlin and Java Versions. Let me know if it works.

**Comment by malandr2** [comment] 2023-10-04 14:47
@yokoyama899 can you confirm if the suggestion from @Aashrut resolved your issue?

**Comment by yokoyama899** [comment] 2023-10-05 10:33
@Aashrut 
I updated the java version from 8 to 17 and "Flutter clean" followed by "Flutter pub get" solved the problem.
Thanks a lot.

**Comment by huycozy** [comment] 2023-10-05 10:42
Glad you solved it. Closing the issue!

**Closed by huycozy** 2023-10-05 10:42 UTC
Labels: in triage

**Comment by Aashrut** [comment] 2023-10-05 10:47
@yokoyama899 , You're welcome.

**Comment by rafiramadian** [comment] 2025-03-27 09:08
@yokoyama899 hi, I want to ask how you update the java version in android flutter?
