### ISSUE TITLE
Error: Type 'WriteBuffer' not found and Error: Type 'ReadBuffer' not found.

### ISSUE THREAD

**Issue by zhonghanwen** [googleads/googleads-mobile-flutter#889] opened 2023-07-20 10:44 UTC
### [REQUIRED] Step 1: Describe your environment
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (1 year, 2 months ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

## Plugin Version
google_mobile_ads: ^2.3.0

### [REQUIRED] Step 2: Describe the problem

```
../../../.pub-cache/hosted/pub.flutter-io.cn/google_mobile_ads-2.1.0/lib/src/ump/user_messaging_codec.dart:27:19: Error: Type 'WriteBuffer' not found.
  void writeValue(WriteBuffer buffer, dynamic value) {
                  ^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/google_mobile_ads-2.1.0/lib/src/ump/user_messaging_codec.dart:45:41: Error: Type 'ReadBuffer' not found.
```

**Comment by huycozy** [comment] 2023-07-20 11:31
Hi @zhonghanwen 
It seems this issue is caused by pub-cache. You can try following [this solution](https://github.com/googleads/googleads-mobile-flutter/issues/668#issuecomment-1365849434) (`flutter clean` > `flutter pub get`) or try again on the [latest Flutter SDK](https://github.com/googleads/googleads-mobile-flutter/issues/769#issuecomment-1448727942) and plugin version.

Closing the issue. If above solutions are not applicable, please write in the comments and I will reopen issue for further investigation.

**Closed by huycozy** 2023-07-20 11:31 UTC
Labels: in triage

**Comment by AvaiyaKashyap** [comment] 2023-09-27 06:44
@zhonghanwen you can try the solution at #769
