### ISSUE TITLE
Unresponsive button in IDFA explainer message when Using the Flutter app Designed for iPad on Mac

### ISSUE THREAD

**Issue by iskamal** [googleads/googleads-mobile-flutter#1209] opened 2024-11-12 21:07 UTC
Plugin Version: google_mobile_ads: ^5.2.0

Describe the problem:
The Continue button as shown in the image in IDFA explainer message is unresponsive when Using the Flutter app Designed for iPad on Mac and there is no way to skip or remove it.
<img width="406" alt="Screenshot 2024-11-12 at 10 53 21 PM" src="https://github.com/user-attachments/assets/71850f59-2987-4702-8329-bc74e0dda732">

## Steps to Reproduce

The code used to show the Form: 

void loadForm() {
    ConsentForm.loadConsentForm(
    (ConsentForm consentForm) async {
      var status = await ConsentInformation.instance.getConsentStatus();
      if (status == ConsentStatus.required) {
        consentForm.show(
          (FormError? formError) {
            loadForm();
          },
        );
      }
    },
    (formError) {
      // Handle the error
    },
  );
}

## Expected results: 
To trigger the iOS ATT alert

## Actual results: 
Stuck in  Explainer message

**Comment by malandr2** [comment] 2024-11-14 00:01
Hi @iskamal, can you confirm you're using version 5.2.0 and Google Mobile Ads iOS SDK version >= 11.9.0?

**Comment by iskamal** [comment] 2024-11-14 00:12
Yes. 
The following is taken from the Podfile.lock of the app:

  - Google-Mobile-Ads-SDK (11.10.0):
    - GoogleUserMessagingPlatform (>= 1.1)
  - google_mobile_ads (5.2.0):
    - Flutter
    - Google-Mobile-Ads-SDK (~> 11.10.0)
    - webview_flutter_wkwebview

**Comment by malandr2** [comment] 2024-11-14 21:15
Hi @iskamal, got it. This is a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/1206 - our iOS engineering team is currently working on this issue. I'll follow up here as soon I have an update to share

**Comment by malandr2** [comment] 2024-12-03 15:57
Hi @iskamal, closing this issue out because it is confirmed not be a Flutter but rather an iOS issue on M1 Macs. Our iOS team is currently working on a fix that will be incorporated into a future UMP SDK version. 

Closing out the ticket but will provide updates here when I have anything to share. I am expecting an update around EOY

**Closed by malandr2** 2024-12-03 15:57 UTC
Labels: in triage, platform-ios
