### ISSUE TITLE
my app crushes after building...i've been trying to implement Native ads & there is no simpler way to do it. 

### ISSUE THREAD

**Issue by ReggieMiller1** [googleads/googleads-mobile-flutter#773] opened 2023-02-15 09:13 UTC
![image](https://user-images.githubusercontent.com/52163493/218983964-2bb6298d-1a67-4798-ba8b-ca90daf80694.png)

**Comment by huycozy** [comment] 2023-02-15 12:28
@ReggieMiller1 Please try running [plugin sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and check if there is the same issue. You may compare your setup with the sample project to find the cause as well.

If the issue still occurs, please provide the crash log in text format instead of a screenshot for better readability and we can continue investigating the issue. 

Also, please provide the plugin version you are using as well. Thanks!

**Comment by ReggieMiller1** [comment] 2023-02-15 14:35
> @ReggieMiller1 Please try running [plugin sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and check if there is the same issue. You may compare your setup with the sample project to find the cause as well.
> 
> If the issue still occurs, please provide the crash log in text format instead of a screenshot for better readability and we can continue investigating the issue.
> 
> Also, please provide the plugin version you are using as well. Thanks!

i'm using **google_mobile_ads: ^2.3.0**, i tested the _plugin sample code_ and updated the package but it showed errors in the native ad template. to add to this, property _nativeTemplateStyle_ is no more supported but a _factoryId_ is required.

**Comment by huycozy** [comment] 2023-02-17 10:47
@ReggieMiller1 Please provide the output of `flutter run -v` which contains error message so that we may verify the issue. Thanks!

**Comment by ReggieMiller1** [comment] 2023-03-06 22:22
i finally found a work around but this it the error it shows now:

+31 ms] W/ConnectionStatusConfig(13603): Dynamic lookup for intent failed for action: com.google.android.gms.ads.service.START
[+2346 ms] I/Ads     (13603): Ad failed to load : 3
[  +81 ms] I/flutter (13603): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[   +2 ms] I/flutter (13603): │ #0   _ShowAdState.initState.<anonymous closure> (package:hashtag/pages/controller/ads.dart:42:20)
[   +9 ms] I/flutter (13603): │ #1   AdInstanceManager._invokeOnAdFailedToLoad (package:google_mobile_ads/src/ad_instance_manager.dart:231:37)
[   +5 ms] I/flutter (13603): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
[   +4 ms] I/flutter (13603): │ 💡 LoadAdError(code: 3, domain: com.google.android.gms.ads, message: Ad unit doesn't match format. <https://support.google.com/admob/answer/9905175#4>, responseInfo:
ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: [], loadedAdapterResponseInfo: null), responseExtras: {})
[  +29 ms] I/flutter (13603): └───────────

**Comment by ReggieMiller1** [comment] 2023-03-06 22:49
i also tried to change the unit ID and i got the following error:

 Received log message: <Google:HTML> Incorrect native ad response. Click actions were not properly specified
I/Ads     (15316): Ad failed to load : 0
I/flutter (15316): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (15316): │ #0   _ShowAdState.initState.<anonymous closure> (package:hashtag/pages/controller/ads.dart:42:20)
ads.dart:42
I/flutter (15316): │ #1   AdInstanceManager._invokeOnAdFailedToLoad (package:google_mobile_ads/src/ad_instance_manager.dart:231:37)
ad_instance_manager.dart:231
I/flutter (15316): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (15316): │ ⛔ LoadAdError(code: 0, domain: com.google.android.gms.ads, message: Internal error., responseInfo: ResponseInfo(responseId: CL79pduvyP0CFSMfBgAdQTwJ6A, mediationAdapterClassName: , adapterResponses: [AdapterResponseInfo(adapterClassName: com.google.ads.mediation.admob.AdMobAdapter, latencyMillis: 33, description: {
I/flutter (15316): │ ⛔   "Adapter": "com.google.ads.mediation.admob.AdMobAdapter",
I/flutter (15316): │ ⛔   "Latency": 33,
I/flutter (15316): │ ⛔   "Ad Source Name": "Reservation campaign",
I/flutter (15316): │ ⛔   "Ad Source ID": "7068401028668408324",
I/flutter (15316): │ ⛔   "Ad Source Instance Name": "[DevRel] [DO NOT EDIT] Native Ads Campaign",
I/flutter (15316): │ ⛔   "Ad Source Instance ID": "3518433842871043",
I/flutter (15316): │ ⛔   "Credentials": {},
I/flutter (15316): │ ⛔   "Ad Error": {
I/flutter (15316): │ ⛔     "Code": 0,
I/flutter (15316): │ ⛔     "Message": "Internal error.",
I/flutter (15316): │ ⛔     "Domain": "com.google.android.gms.ads",
I/flutter (15316): │ ⛔     "Cause": "null"
I/flutter (15316): │ ⛔   }
I/flutter (15316): │ ⛔ }, adUnitMapping: {}, adError: AdError(code: 0, domain: com.google.android.gms.ads, message: Internal error.), adSourceName: Reservation campaign, adSourceId: 7068401028668408324, adSourceInstanceName: [DevRel] [DO NOT EDIT] Native Ads Campaign, adSourceInstanceId: 3518433842871043)], loadedAdapterResponseInfo: null), responseExtras: {mediation_group_name: Campaign})
I/flutter (15316): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by huycozy** [comment] 2023-03-07 09:45
>i also tried to change the unit ID 

Before changing ad ID, does the issue happen with test IDs on plugin sample code? Also, please provide the complete output of `flutter run -v` so that we may verify the issue. Thanks!

**Comment by ReggieMiller1** [comment] 2023-03-07 12:48
[admob log error.txt](https://github.com/googleads/googleads-mobile-flutter/files/10909458/admob.log.error.txt)

i have provided the log as txt file....i was using a **_test ID_** when i faced the error.

**Comment by ReggieMiller1** [comment] 2023-03-07 19:36
okay found what the problems was...the **_App ID_** was causing (i was using a test app ID) the error (i was using a test app ID) but when i changed to the one i got from _admob_ it worked. i was using a test ad unit as well not the real one.

**Comment by huycozy** [comment] 2023-03-08 05:10
The sample App ID should work too. However, since the issue is solved, closing it from here.

**Closed by huycozy** 2023-03-08 05:10 UTC
Labels: in triage
