### ISSUE TITLE
Interstitial ad cannot be closed

### ISSUE THREAD

**Issue by tal412** [googleads/googleads-mobile-flutter#317] opened 2021-07-22 08:49 UTC
## Steps to Reproduce

So I got this report from a user using an iPhone 12.
I could not reproduce it myself on an emulator and I don't own iPhone 12 in order to test this. 

You can see that this ad cannot be closed because the X button is located just under the clock:
![image](https://user-images.githubusercontent.com/36299714/126612836-7f648e2f-f6ba-40c7-ac1e-bba9e61c3e7d.png)

Please help me out with this.

**Comment by maheshmnj** [comment] 2021-08-03 12:20
Hi @tal412, Please share the output of `flutter doctor -v` And possibly the minimal reproducible code did you try wrapping  your ad widget in SafeArea widget?

**Comment by tal412** [comment] 2021-08-08 06:25
> Hi @tal412, Please share the output of `flutter doctor -v` And possibly the minimal reproducible code And did you try wrapping your ad widget in SafeArea widget?

Hi and thanks for the reply. 
I don't actually have an ad widget, all I do is using `Interstitial.load()`. 
I have no control on the way the ad looks.

**Comment by maheshmnj** [comment] 2021-08-10 07:06
Closing this issue as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/191, feel free to comment if you disagree and I will reopen it.

Thank you for your contribution.

**Closed by maheshmnj** 2021-08-10 07:06 UTC
Labels: feedback required, in triage
