### ISSUE TITLE
The full screen AD cannot be displayed on a perforated phone

### ISSUE THREAD

**Issue by crazecoder** [googleads/googleads-mobile-flutter#1167] opened 2024-09-04 20:38 UTC
## Steps to Reproduce

1. ```SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge, overlays: []);```
2. on Android 
```
getWindow().getDecorView().setSystemUiVisibility(
    View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
    View.SYSTEM_UI_FLAG_LAYOUT_STABLE |
    View.SYSTEM_UI_FLAG_FULLSCREEN |
    View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
);
```
3. ```RewardedInterstitialAd.show```

**Expected results:** 

I wanted to display a fullscreen AD, but on the perforated phone, the status bar was not covered by the AD, Or set it to a black background instead of a transparent one

**Actual results:** 
<img width="362" alt="image" src="https://github.com/user-attachments/assets/5f5ae245-3c9e-45f0-857b-dee1534f92ff">

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by malandr2** [comment] 2024-09-05 14:53
Hi @crazecoder, this may also be the default behavior on Android. Are you able to reproduce with our [Android Rewarded Interstitial](https://github.com/googleads/googleads-mobile-android-examples/tree/main/kotlin/admob/RewardedInterstitialExample) sample?

**Comment by crazecoder** [comment] 2024-09-05 16:52
<img width="361" alt="image" src="https://github.com/user-attachments/assets/fe1a2c55-c6be-444e-b3e9-d996b0721839">

@malandr2 This problem also occurs in the Android Rewarded Interstitial example
just change style.xml
```xml
<!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowTranslucentNavigation">true</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
        <!-- Customize your theme here. -->
    </style>
```
and set activity_main.xml a red background
```xml
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/holo_red_dark" //add this
    tools:context="com.google.ads.rewardedinterstitialexample.MainActivity">
```

**Comment by malandr2** [comment] 2024-09-07 17:48
Hi @crazecoder, thanks for checking that. Because the flutter plguin behaves the same, this appears to be the intended behavior. To further clarify if this is expected (for Android), please create a new thread in the [AdMob Developers Forum](https://groups.google.com/g/google-admob-ads-sdk) to the confirm Android behavior. If this is unexpected, Android will have to address in the Android SDK. 

Closing this out for now. Thanks!

**Closed by malandr2** 2024-09-07 17:48 UTC
