### ISSUE TITLE
Plugin is making video_player laggy

### ISSUE THREAD

**Issue by CripyIce** [googleads/googleads-mobile-flutter#444] opened 2021-11-22 08:34 UTC
## Plugin Version

I'm using `google_mobile_ads` version `1.0.0` and `video_player` version `2.2.7`.

## Details

1. Using WordPress API to get post content.
2. Parsing the html code into widgets using `flutter_html` library.
3. The library finds video content and replaces it with a `chewie` widget which is based on `video_player`.
4. Running `flutter build apk` and installing it directly on a device works perfectly fine.
5. When uploading to Play Store all the videos becomes extremely laggy.

After opening an [issue](https://github.com/flutter/flutter/issues/93614) at `video_player` repository, it seems that the following code resolved my issue:
```dart
  if (Platform.isAndroid) {
    PlatformViewsService.synchronizeToNativeViewHierarchy(false);
  }
```
Is the above code a legit solution?

**Target Platform:** Android
**Target OS version:** 11.0
**Devices:** Samsung Galaxy Note 20

**Comment by CripyIce** [comment] 2021-11-22 11:56
Hi @maheshmnj , I've seen this issue #189 and found that code snippet that helps solving this issue.
Also, when removing the ads from the videos list, I see no lags anymore. But when returning the ads (without the code snippet I attached) it becomes super laggy once again.

**Comment by maheshmnj** [comment] 2021-11-22 12:31
Thanks for the info @CripyIce, 

> Is the above code a legit solution?

As suggested in the https://github.com/googleads/googleads-mobile-flutter/issues/189#issuecomment-884491594 you may continue to use that proposed solution until the proper fix lands in the plugin. 

Closing this issue as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/269, And You may follow up on this issue  for further updates.

**Closed by maheshmnj** 2021-11-22 12:31 UTC
Labels: in triage
