### ISSUE TITLE
Ios Pod Error GoogleAppMeasurement Firebase 10

### ISSUE THREAD

**Issue by cnkygmr** [googleads/googleads-mobile-flutter#673] opened 2022-10-19 11:02 UTC
```
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 10.0.1, which depends on
      Firebase/Analytics (= 10.0.0) was resolved to 10.0.0, which depends on
        Firebase/Core (= 10.0.0) was resolved to 10.0.0, which depends on
          FirebaseAnalytics (~> 10.0.0) was resolved to 10.0.0, which depends on
            FirebaseAnalytics/AdIdSupport (= 10.0.0) was resolved to 10.0.0, which depends on
              GoogleAppMeasurement (= 10.0.0)

    google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
      Google-Mobile-Ads-SDK (= 9.10.0) was resolved to 9.10.0, which depends on
        GoogleAppMeasurement (< 10.0, >= 7.0)

```

**Comment by huycozy** [comment] 2022-10-19 12:28
Hi @cnkygmr 
Is this issue reproducible locally? If so, please try running [example code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) and share the output of `flutter run -v` so that we may verify the issue.

**Comment by JulienDev** [comment] 2022-10-19 14:34
Same error after updating Firebase libraries. This is my current libraries configuration : 
```
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.0.1
  firebase_analytics: ^10.0.1
  firebase_remote_config: ^3.0.1
  google_mobile_ads: ^2.1.0
```
and the error associated :

> [!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
>   In Podfile:
>     firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 10.0.1, which depends on
>       Firebase/Analytics (= 10.0.0) was resolved to 10.0.0, which depends on
>         Firebase/Core (= 10.0.0) was resolved to 10.0.0, which depends on
>           FirebaseAnalytics (~> 10.0.0) was resolved to 10.0.0, which depends on
>             FirebaseAnalytics/AdIdSupport (= 10.0.0) was resolved to 10.0.0, which depends on
>               GoogleAppMeasurement (= 10.0.0)
> 
>     google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
>       Google-Mobile-Ads-SDK (= 9.10.0) was resolved to 9.10.0, which depends on
>         GoogleAppMeasurement (< 10.0, >= 7.0)

**Comment by ragotrebor-ned** [comment] 2022-10-19 15:02
> 

Hi, same error here.

I found is an old closed issue.
https://github.com/googleads/googleads-mobile-flutter/issues/594

**Comment by Tom3652** [comment] 2022-10-20 12:33
Same error after updating to the latest version of Firebase. 
```GoogleAppMeasurement``` should be updated here in my understanding

**Comment by Ali1Ammar** [comment] 2022-10-20 14:27
using @jslattery26 fork will solve the problems temporarily
```
  google_mobile_ads: 
    git: 
      url: https://github.com/jslattery26/googleads-mobile-flutter
      path: packages/google_mobile_ads
```

**Comment by large** [comment] 2022-10-20 22:07
Same error for `RewardedAd.load` too, even if I use @jslattery26  fork:

```log
======== Exception caught by services library ======================================================
The following _TypeError was thrown during a platform message callback:
type 'Null' is not a subtype of type 'String'

When the exception was thrown, this was the stack: 
#0      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1007:31)
#1      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1003:38)
#2      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1022:11)
#3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:479:12)
#4      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:531:39)
#5      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1108:22)
#6      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:479:12)
#7      StandardMethodCodec.decodeMethodCall (package:flutter/src/services/message_codecs.dart:612:44)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:534:35)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#11     _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#15     _invoke2 (dart:ui/hooks.dart:188:10)
#16     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#17     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#18     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#19     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#20     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 3 frames from dart:async)
====================================================================================================
```

Ref code for loading Reward ad:
```dart
    RewardedAd.load(
        adUnitId: AdHelper.rewardedAdUnitId,
        request: const AdRequest(),
        rewardedAdLoadCallback: RewardedAdLoadCallback(
          onAdLoaded: (RewardedAd ad) {
            print('$ad loaded.');
            // Keep a reference to the ad so you can show it later.
            reward = ad;
            reward!.fullScreenContentCallback = FullScreenContentCallback(
              onAdShowedFullScreenContent: (RewardedAd ad) =>
                  print('$ad onAdShowedFullScreenContent.'),
              onAdDismissedFullScreenContent: (RewardedAd ad) {
                print('$ad onAdDismissedFullScreenContent.');
                ad.dispose();
                reward = null;
              },
              onAdFailedToShowFullScreenContent:
                  (RewardedAd ad, AdError error) {
                print('$ad onAdFailedToShowFullScreenContent: $error');
                ad.dispose();
                reward = null;
              },
              onAdImpression: (RewardedAd ad) => impressionTrigger = true,
            );

            //Fire away
            reward!.show(
                onUserEarnedReward: (AdWithoutView ad, RewardItem rewardItem) {
              // Reward the user for watching an ad.
              print("You got your reward, yey!");
            });
          },
          onAdFailedToLoad: (LoadAdError error) {
            print('RewardedAd failed to load: $error');
            reward = null;
          },
        ));
```

**Comment by huycozy** [comment] 2022-10-21 03:29
Hi everyone facing this issue,
This issue seems to have been fixed on version `2.0.0` of the plugin onward as mentioned at https://github.com/googleads/googleads-mobile-flutter/issues/594#issuecomment-1196970456. So, please try use the latest version and check if the issue still reproduces.

**Comment by derjohng** [comment] 2022-10-21 09:28
same issue.
google_mobile_ads: ^2.1.0
firebase_core: ^2.1.0
firebase_crashlytics: ^3.0.2
firebase_analytics: ^10.0.2

**Comment by Ali1Ammar** [comment] 2022-10-21 12:32
> Hi everyone facing this issue, This issue seems to have been fixed on version `2.0.0` of the plugin onward as mentioned at [#594 (comment)](https://github.com/googleads/googleads-mobile-flutter/issues/594#issuecomment-1196970456). So, please try use the latest version and check if the issue still reproduces.

the error still exist in version 2.1.0 when using with the latest firebase version 


using the fork above fix the build problem but introduce a new bug when calling the load method 

the only fix for now is use old firebase versions

**Comment by Ali1Ammar** [comment] 2022-10-21 15:33
the plugin that i use
```yaml
  firebase_analytics: ^10.0.0
  firebase_remote_config: ^3.0.1
  firebase_messaging: ^14.0.1
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.0.1
  firebase_storage: ^11.0.1
  firebase_auth: ^4.0.1
  firebase_database: ^10.0.1
  firebase_in_app_messaging: ^0.7.0+1

  google_mobile_ads: ^2.1.0
```
error:
```terminal
mac@alimac ios % pod install
Analyzing dependencies
firebase_analytics: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
Run script to upload symbols already exists.
firebase_crashlytics: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_database: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_in_app_messaging: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 10.0.1, which depends on
      Firebase/Analytics (= 10.0.0) was resolved to 10.0.0, which depends on
        Firebase/Core (= 10.0.0) was resolved to 10.0.0, which depends on
          FirebaseAnalytics (~> 10.0.0) was resolved to 10.0.0, which depends on
            FirebaseAnalytics/AdIdSupport (= 10.0.0) was resolved to 10.0.0, which depends on
              GoogleAppMeasurement (= 10.0.0)

    google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
      Google-Mobile-Ads-SDK (= 9.10.0) was resolved to 9.10.0, which depends on
        GoogleAppMeasurement (< 10.0, >= 7.0)
mac@alimac ios % 
```

i also try using
pod repo update
pod update 
removeing Podfile.lock
flutter clean

**Comment by Ali1Ammar** [comment] 2022-10-21 15:43
> Same error for `RewardedAd.load` too, even if I use @jslattery26 fork:
> 
> ```
> ======== Exception caught by services library ======================================================
> The following _TypeError was thrown during a platform message callback:
> type 'Null' is not a subtype of type 'String'
> 
> When the exception was thrown, this was the stack: 
> #0      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1007:31)
> #1      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1003:38)
> #2      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1022:11)
> #3      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:479:12)
> #4      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:531:39)
> #5      AdMessageCodec.readValueOfType (package:google_mobile_ads/src/ad_instance_manager.dart:1108:22)
> #6      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:479:12)
> #7      StandardMethodCodec.decodeMethodCall (package:flutter/src/services/message_codecs.dart:612:44)
> #8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:534:35)
> #9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:529:34)
> #10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
> #11     _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
> #15     _invoke2 (dart:ui/hooks.dart:188:10)
> #16     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
> #17     _Channel.push (dart:ui/channel_buffers.dart:132:31)
> #18     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
> #19     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
> #20     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
> (elided 3 frames from dart:async)
> ====================================================================================================
> ```
> 
> Ref code for loading Reward ad:
> 
> ```dart
>     RewardedAd.load(
>         adUnitId: AdHelper.rewardedAdUnitId,
>         request: const AdRequest(),
>         rewardedAdLoadCallback: RewardedAdLoadCallback(
>           onAdLoaded: (RewardedAd ad) {
>             print('$ad loaded.');
>             // Keep a reference to the ad so you can show it later.
>             reward = ad;
>             reward!.fullScreenContentCallback = FullScreenContentCallback(
>               onAdShowedFullScreenContent: (RewardedAd ad) =>
>                   print('$ad onAdShowedFullScreenContent.'),
>               onAdDismissedFullScreenContent: (RewardedAd ad) {
>                 print('$ad onAdDismissedFullScreenContent.');
>                 ad.dispose();
>                 reward = null;
>               },
>               onAdFailedToShowFullScreenContent:
>                   (RewardedAd ad, AdError error) {
>                 print('$ad onAdFailedToShowFullScreenContent: $error');
>                 ad.dispose();
>                 reward = null;
>               },
>               onAdImpression: (RewardedAd ad) => impressionTrigger = true,
>             );
> 
>             //Fire away
>             reward!.show(
>                 onUserEarnedReward: (AdWithoutView ad, RewardItem rewardItem) {
>               // Reward the user for watching an ad.
>               print("You got your reward, yey!");
>             });
>           },
>           onAdFailedToLoad: (LoadAdError error) {
>             print('RewardedAd failed to load: $error');
>             reward = null;
>           },
>         ));
> ```

that right this error present in version 2.1.0 too  , i removed it from my above comment

**Comment by huycozy** [comment] 2022-10-24 09:30
I also can reproduce this issue with `firebase_analytics: ^10.0.2` and `google_mobile_ads: ^2.1.0`.

<details>
<summary>Logs</summary>

```bash
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In snapshot (Podfile.lock):
    GoogleAppMeasurement (< 10.0, = 9.6.0, >= 7.0)

  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 10.0.2, which depends on
      Firebase/Analytics (= 10.0.0) was resolved to 10.0.0, which depends on
        Firebase/Core (= 10.0.0) was resolved to 10.0.0, which depends on
          FirebaseAnalytics (~> 10.0.0) was resolved to 10.0.0, which depends on
            FirebaseAnalytics/AdIdSupport (= 10.0.0) was resolved to 10.0.0, which depends on
              GoogleAppMeasurement (= 10.0.0)

    google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
      Google-Mobile-Ads-SDK (= 9.10.0) was resolved to 9.10.0, which depends on
        GoogleAppMeasurement (< 10.0, >= 7.0)

```
</details>

/cc: @jjliu15

**Comment by leonschwanitz** [comment] 2022-10-24 13:10
Same issue here.

**Closed** 2022-10-24 18:07 UTC
Labels: bug, p1-high, e1-hours, platform-ios

**Comment by FisherWL** [comment] 2022-10-26 00:21
same issue.

**Comment by guiguito** [comment] 2022-10-26 22:13
same issue for me

**Comment by oke007** [comment] 2022-10-28 08:50
same issue for me with latest firebase and google_mobile_ads version.

dependencies
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  firebase_analytics: ^10.0.3
  firebase_dynamic_links: ^5.0.3
  google_mobile_ads: ^2.1.0

Error:
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
      In Podfile:
        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 10.0.3, which depends on
          Firebase/Analytics (= 10.0.0) was resolved to 10.0.0, which depends on
            Firebase/Core (= 10.0.0) was resolved to 10.0.0, which depends on
              FirebaseAnalytics (~> 10.0.0) was resolved to 10.0.0, which depends on
                FirebaseAnalytics/AdIdSupport (= 10.0.0) was resolved to 10.0.0, which depends on
                  GoogleAppMeasurement (= 10.0.0)

        google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
          Google-Mobile-Ads-SDK (= 9.10.0) was resolved to 9.10.0, which depends on
            GoogleAppMeasurement (< 10.0, >= 7.0)

**Comment by under3415** [comment] 2022-10-29 02:14
Yay, this is fixed in google_mobile_ads: ^2.2.0

**Comment by j796160836** [comment] 2022-11-24 08:42
I comment this line in `Podfile` and it works for me.

```
# platform :ios, '10.0'
```

**Comment by CoryLWright** [comment] 2023-08-03 02:45
Just had this issue today while using  

google_mobile_ads: ^3.0.0. 
firebase_core: ^2.15.0
firebase_analytics: ^10.4.4

Couldn't get it to work at all until I changed to  google_mobile_ads: ^2.4.0 in my subspec.yaml file. Then I ran

flutter pub get
pod repo update
pod install
flutter build iOS
flutter run

Now all is good. Mac M2 chip. Hope this helps someone.
