### ISSUE TITLE
Missing methods and getters to update user consent

### ISSUE THREAD

**Issue by absar** [googleads/googleads-mobile-flutter#1003] opened 2024-02-07 14:21 UTC
These methods and getters to give an option to the user to update consent are missing in Flutter implementation whereas these are available in both Android and iOS since July-2023
`ConsentInformation.privacyOptionsRequirementStatus`
`UserMessagingPlatform.showPrivacyOptionsForm`

While there is `ConsentInformation.reset` as per the docs it should only be used for testing purposes to simulate a user's first install experience or to remove UMP SDK completely

**Comment by malandr2** [comment] 2024-02-07 16:52
Hey @absar, this is a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/944 so am I going to close this one out, but we plan to implement those APIs for Flutter (along with others) in Q2/Q3 of 2024

**Closed by malandr2** 2024-02-07 16:52 UTC

**Comment by Phlphat746** [comment] 2024-02-07 18:03
Thank you brather so much "I subscribing" email anytink sure.

**Comment by Phlphat746** [comment] 2024-02-07 18:09
brother sure I apologize for my language  But I will definitely reply to you or my brother. But I work on this every day, but I think it's more of a weak point for me because I haven't succeeded yet. It would be better if I practiced for a long time.  definitely  But Flutter at  I chose this API, it's definitely suitable for me.
