### ISSUE TITLE
google_mobile_ads > 5.2.0  Error (Xcode): Undefined symbols:

### ISSUE THREAD

**Issue by michelmelo** [googleads/googleads-mobile-flutter#1201] opened 2024-10-29 07:05 UTC
Hello, I have a problem with version 5.2.0, after I updated it started giving the error below.

XCODE:
```
ld: warning: Could not find or use auto-linked library 'swiftXPC': library 'swiftXPC' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'MarketplaceKit': framework 'MarketplaceKit' not found
ld: Undefined symbols:
```

FLUTTER:
```
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXX
Running pod install...                                              5,8s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         7,9s
Xcode build done.                                           80,1s
Failed to build iOS app
Error (Xcode): Undefined symbols:


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)


Encountered error while building for device.
```

**Comment by malandr2** [comment] 2024-10-29 14:03
Duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/1185

See https://github.com/googleads/googleads-mobile-flutter/issues/1185#issuecomment-2407498420 for context. The minimum Xcode version was raised with the latest to Xcode >= 15.3

**Closed by malandr2** 2024-10-29 14:03 UTC
