### ISSUE TITLE
I am getting this issue when add this dependencies into my flutter project and run my app

### ISSUE THREAD

**Issue by luqreh** [googleads/googleads-mobile-flutter#1220] opened 2024-12-29 10:44 UTC
### Step 0: Are you in the right place?

  * For general technical questions, or help with project-specific issues like setting up ads in
   your app, reach out to our support team on the
   [Developer Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk).
  * For assistance with your AdMob account, reach out to
   [AdMob Support](https://support.google.com/admob/?hl=en#topic=7383088).
  * For feedback on [our documentation](https://developers.google.com/admob/flutter/quick-start),
   send your feedback by pressing the **Send Feedback** button at the top right of the
   documentation page you are on.
  * For issues related to __the code in this repository__, continue filing this GitHub issue.

  * Once you've read this section and determined that your issue is appropriate for
    this repository, **please delete this section**.

---

### [REQUIRED] Step 1: Describe your environment
Android Studio LadyBug Patch 3
Flutter version 3.27.1 on channel

## Plugin Version

Latest version or 3.0.0 version

### [REQUIRED] Step 2: When Run my app getting this error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webview_flutter_android:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':webview_flutter_android:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: C:\Users\Rehman\AppData\Local\Android\sdk\platforms\android-34\core-for-system-modules.jar.
         > Error while executing process C:\Program Files\Android\Android Studio\jbr\bin\jlink.exe with arguments {--module-path C:\Users\Rehman\.gradle\caches\transforms-3\fb247f22548bfd545efa0cbc10d96775\transformed\output\temp\jmod --add-modules java.base --output C:\Users\Rehman\.gradle\caches\transforms-3\fb247f22548bfd545efa0cbc10d96775\transformed\output\jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 22s

## Steps to Reproduce

After adding dependecies and run my app get this error. Also not have added any ads code into my files.. I also tried to add a banner ad but getting same error. Try to fix using chat gpt search on google but no solution found.

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by malandr2** [comment] 2024-12-30 18:00
Hi @luqreh, this looks like a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/1200

Try upgrading your kotlin version to `1.9.0` and take a look at our [banner_example](https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/banner_example) for applicable configuration settings

**Closed by malandr2** 2024-12-30 18:00 UTC

**Comment by luqreh** [comment] 2024-12-31 03:33
@malandr2 hi issue is solved successfully I just need to change the gradle plugin version in my gradle.build file when I change it the issue is successfully resolved thanku
