### ISSUE TITLE
Native Ad blurs widgets with backdrop filter on iOS

### ISSUE THREAD

**Issue by Kristina-Isakovich** [googleads/googleads-mobile-flutter#903] opened 2023-08-10 16:41 UTC
If I use a modal with BackdropFilter (filter: ImageFilter.blur), then I get this result:

<details><summary>Result</summary>
<img src="https://github.com/googleads/googleads-mobile-flutter/assets/73427550/426bdf86-4772-4c02-828c-4b594b8e718f" width="200">
</details>

There was a similar problem, but it is closed: #91.

Help me please! 😊

**Comment by huycozy** [comment] 2023-08-11 10:54
Closing this issue as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/91 and re-opening that issue as well.

**Closed by huycozy** 2023-08-11 10:54 UTC
Labels: in triage
