### ISSUE TITLE
A manifest file in one of your active artifacts doesn't include the com.google.android.gms.permission.AD_ID permission.

### ISSUE THREAD

**Issue by a-ahmed116** [googleads/googleads-mobile-flutter#922] opened 2023-09-17 08:45 UTC
Hello There!

I am using this plugin for many apps and it's working fine but one of my apps is having an issue when uploading to the Play Store

It says the androidmanifest.xml doesn't contain the "com.google.android.gms.permission.AD_ID permission"

Below you can find the dependencies of this app:

> dependencies:
>   flutter:
>     sdk: flutter
>   provider: ^6.0.0
>   shared_preferences: ^2.0.15
>   transparent_image: ^2.0.0
>   dio: ^5.0.2
>   intl: ^0.18.0
>   timeago: ^3.4.0
>   share_plus: ^6.3.1
>   version: ^3.0.2
>   package_info_plus: ^3.0.3
>   firebase_messaging: ^14.6.2
>   open_store: ^0.5.0
>   sliding_clipped_nav_bar: ^3.1.0+4
>   in_app_review: ^2.0.6
>   google_mobile_ads: ^3.0.0
>   permission_handler: ^10.2.0
>   loadmore: ^2.1.0
>   community_charts_flutter: ^1.0.1
>   flutter_html: ^3.0.0-alpha.3
>   fl_chart: ^0.62.0
>   flutter_local_notifications: ^14.1.1

![image](https://github.com/googleads/googleads-mobile-flutter/assets/83700410/c15ac107-b02f-4f27-8c38-8f902175f3d1)

## Flutter doctor -v
> [√] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.22000.1817], locale en-US)
>     • Flutter version 3.10.4 on channel stable at C:\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 682aa387cf (3 months ago), 2023-06-05 18:04:56 -0500
>     • Engine revision 2a3401c9bb
>     • Dart version 3.0.3
>     • DevTools version 2.23.1
> 
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
>     • Android SDK at C:\Users\amrah\android
>     • Platform android-33-ext4, build-tools 33.0.1
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.23)
>     • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
>     • Visual Studio Build Tools 2019 version 16.11.33214.272
>     • Windows 10 SDK version 10.0.19041.0
> 
> [√] Android Studio (version 2022.1)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
> 
> [√] VS Code, 64-bit edition (version 1.82.1)
>     • VS Code at C:\Program Files\Microsoft VS Code
>     • Flutter extension version 3.72.0
> 
> [√] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.1817]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.188
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 117.0.2045.31
> 
> [√] Network resources
>     • All expected network resources are available.
> 
> • No issues found!

**Comment by agelospanagiotakis** [comment] 2023-09-18 07:11
i hace the same issue.

**Comment by huycozy** [comment] 2023-09-18 11:36
Hi. This is caused by your missing AD_ID permission on AndroidManifest.xml file. You can follow the solution provided at https://stackoverflow.com/questions/71473553/action-requested-declare-your-ad-id-permission. 

Your question is best suited for support channels like StackOverflow, so please ask the same there for solutions if you have similar questions. Closing for now.

**Closed by huycozy** 2023-09-18 11:36 UTC
Labels: in triage

**Comment by a-ahmed116** [comment] 2023-09-18 11:54
I thought the plugin should automatically add the permission, However, i already add the permission to android manifest but i got the same error

there's something weird here .. i am using the same plugin with the same configuration in many apps but in this one every time i upload a new version i get this error

**Comment by huycozy** [comment] 2023-09-19 10:11
@a-ahmed116 This should be handled on Android side and not a part of this plugin. Please make sure you added this one (without `tools:node="remove"`):

```xml
<uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
```

Another clue is to make sure you have rolled out 100% users (Admob side).  Please see https://groups.google.com/g/google-admob-ads-sdk for the resource and ask the same there.

**Comment by gaabrielricci** [comment] 2023-12-19 16:43
i have the same issue here. 
![image](https://github.com/googleads/googleads-mobile-flutter/assets/27814206/cc075d89-5c46-4222-8fcb-a7781ebdd7a2)

![image](https://github.com/googleads/googleads-mobile-flutter/assets/27814206/860f2109-4daf-4b6e-9df3-f33acce6c533)

**Comment by gerripro** [comment] 2024-01-08 18:01
@gaabrielricci have u had a chance to resolve it?
I've got the same issue and dont know what to do. Ads simply dont appear

**Comment by nmbgeek** [comment] 2024-01-23 01:20
Check your other release tracks in Play console - https://support.google.com/googleplay/android-developer/thread/249720680/com-google-android-gms-permission-ad-id-permission-error-even-when-in-the-androidmanifest-xml?hl=en

**Comment by jakenoble** [comment] 2024-09-09 12:06
Does this mean @nmbgeek - the warning will never go because someone, somewhere might have a version that still contains the offending app?
