### ISSUE TITLE
Google ads on the list page or video playback page cause jank

### ISSUE THREAD

**Issue by mondongxr** [googleads/googleads-mobile-flutter#443] opened 2021-11-22 02:43 UTC
## Plugin Version
1.0.0

## Details

When using Google ads on a list page or a video play page, the page can get jank.

**Target Platform:**
Android
**Target OS version:**
Android P, Android 10, Android 11
**Devices:**
Pixel 2

## Logs

<details>
<summary>Logs</summary>

Add dependencies
```
dependencies:
  video_player: ^2.2.7
```

Sample
```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:video_player/video_player.dart';

class VideoPage extends StatefulWidget {
  const VideoPage({Key? key}) : super(key: key);

  @override
  _VideoPageState createState() => _VideoPageState();
}

class _VideoPageState extends State<VideoPage> {
  VideoPlayerController? _controller;

  BannerAd? _bannerAd;
  bool _bannerAdIsLoaded = false;

  @override
  void initState() {
    super.initState();

    _controller = VideoPlayerController.asset("assets/Butterfly-209.mp4");

    _controller
      ?..setLooping(true)
      ..initialize().then((value) => setState(() {}))
      ..play();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Video player'),
      ),
      resizeToAvoidBottomInset: false,
      body: Container(
        alignment: Alignment.center,
        child: _realContent(),
      ),
    );
  }

  Widget _realContent() {
    if (_controller?.value.isInitialized ?? false) {
      return Column(
        children: [
          _buildVideoSection(),
          const SizedBox(
            height: 20,
          ),
          _bannerAdView(),
        ],
      );
    }
    return Container();
  }

  Widget _bannerAdView() {
    final BannerAd? bannerAd = _bannerAd;
    if (_bannerAdIsLoaded && bannerAd != null) {
      return SizedBox(
          height: bannerAd.size.height.toDouble(),
          width: bannerAd.size.width.toDouble(),
          child: AdWidget(ad: bannerAd));
    } else {
      return Container();
    }
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    // Create the ad objects and load ads.
    _bannerAd = BannerAd(
        size: AdSize.banner,
        adUnitId:
            Platform.isAndroid ? 'ca-app-pub-3940256099942544/6300978111' : 'ca-app-pub-3940256099942544/2934735716',
        listener: BannerAdListener(
          onAdLoaded: (Ad ad) {
            print('BannerAd loaded.');
            setState(() {
              _bannerAdIsLoaded = true;
            });
          },
          onAdFailedToLoad: (Ad ad, LoadAdError error) {
            print('BannerAd failedToLoad: $error');
            ad.dispose();
          },
          onAdOpened: (Ad ad) => print('BannerAd onAdOpened.'),
          onAdClosed: (Ad ad) => print('BannerAd onAdClosed.'),
        ),
        request: const AdRequest())
      ..load();
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
    _bannerAd?.dispose();
  }

  Widget _buildVideoSection() {
    MediaQueryData mediaQuery = MediaQuery.of(context);
    final double previewRatio = _controller!.value.aspectRatio;
    final double maxSize = mediaQuery.size.width;
    return Container(
      width: maxSize,
      height: maxSize / previewRatio,
      margin: const EdgeInsets.only(top: 20),
      child: Center(
        child: Container(
          decoration: BoxDecoration(
              border: Border.all(color: const Color(0xFFBFBFBF), width: 1),
              borderRadius: const BorderRadius.all(Radius.circular(8))),
          child: _buildPreviewContent(),
        ),
      ),
    );
  }

  Widget _buildPreviewContent() {
    return ClipRRect(
      borderRadius: BorderRadius.circular(8),
      child: Stack(
        alignment: Alignment.bottomCenter,
        children: <Widget>[
          VideoPlayer(_controller!),
          SizedBox(
            height: 4,
            child: VideoProgressIndicator(
              _controller!,
              allowScrubbing: true,
              padding: const EdgeInsets.only(bottom: 0),
              colors: VideoProgressColors(playedColor: const Color(0xFF5465FF)),
            ),
          ),
        ],
      ),
    );
  }
}
```

flutter doctor -v 
```
[✓] Flutter (Channel beta, 2.6.0-5.2.pre, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.6.0-5.2.pre at /Users/xxx/fvm/versions/2.6.0-5.2.pre
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 400608f101 (10 weeks ago), 2021-09-15 15:50:26 -0700
    • Engine revision 1d521d89d8
    • Dart version 2.15.0 (build 2.15.0-82.2.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • Pixel 2 (mobile) • HT7AH1A03662 • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome       • web-javascript • Google Chrome 96.0.4664.55
```

</details>

**Comment by maheshmnj** [comment] 2021-11-22 12:33
Hi @mondongxr, Thanks for filing the issue. This is a known issue and is being [tracked here](https://github.com/googleads/googleads-mobile-flutter/issues/269) you may try the solution [mentioned here](https://github.com/googleads/googleads-mobile-flutter/issues/189#issuecomment-884491594)  until this gets fixed. 

Closing as a duplicate of the linked issue.

**Closed** 2021-11-22 12:34 UTC
Labels: in triage
