### ISSUE TITLE
Issue: Screen flickering when navigating to a new screen

### ISSUE THREAD

**Issue by aquiroga96** [googleads/googleads-mobile-flutter#490] opened 2022-01-14 20:06 UTC
Screen is flickering when navigating to a new screen within drawer.
This happens after updating to the latest Flutter version (2.8.1). Before the update, everything worked well (in Flutter version 2.5.3). If I remove banner ad navigation works well.
I've noticed that this problem has affected many developers.

**Comment by pynner** [comment] 2022-01-17 19:59
@aquiroga96 they've acknowledged it here https://github.com/googleads/googleads-mobile-flutter/issues/467

**Comment by aquiroga96** [comment] 2022-01-17 20:06
@pynner do you know when is stable 2.10 version going to be for release?

**Comment by Caqil** [comment] 2022-01-18 07:05
im using this very smooth and no flicker

google_mobile_ads:
    git:
      url: https://github.com/SuaMusica/googleads-mobile-flutter.git
      path: packages/google_mobile_ads
      ref: feature/suamusica

**Comment by maheshmnj** [comment] 2022-01-18 11:10
Hi @aquiroga96, Thanks for filing the issue. This issue is a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/467, This issue occurred due to changes in the flutter framework in `stable 2.8.1`, This has been fixed and the fix is available on the latest master channel and will land on stable in the upcoming `stable 2.10.` which will be very soon.

**Closed by maheshmnj** 2022-01-18 11:10 UTC
Labels: in triage
