### ISSUE TITLE
Namespace error: Latest gradle plugin requires to specify a namespace for your project. The plugin doesn't automatically update namespace

### ISSUE THREAD

**Issue by kotaibaw** [googleads/googleads-mobile-flutter#899] opened 2023-08-05 11:14 UTC
The package’s android/build.gradle file should already have a namespace attribute that matches the package name.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':google_mobile_ads'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

     If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

**Comment by huycozy** [comment] 2023-08-07 11:55
Hi @kotaibaw 
It seems you are using AGP 8.x. Closing the issue as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/839. In the meantime, you can use a fork at https://github.com/googleads/googleads-mobile-flutter/issues/839#issuecomment-1570496105.

**Closed by huycozy** 2023-08-07 11:55 UTC
Labels: in triage
