### ISSUE TITLE
Banner ad failed to load: LoadAdError code: 3

### ISSUE THREAD

**Issue by dutch-game-studio** [googleads/googleads-mobile-flutter#296] opened 2021-07-02 17:58 UTC
## Plugin Version

google_mobile_ads: ^0.13.2

## Steps to Reproduce

Add this widget

```
class MyAppBannerAd extends StatefulWidget {

  const MyAppBannerAd({this.alternativeColors = false});

  @override
  _MyAppBannerAdState createState() => _MyAppBannerAdState();
}

class _MyAppBannerAdState extends State<MyAppBannerAd> {
  BannerAd bannerAd;
  bool adLoaded = false;

  @override
  void initState() {
    super.initState();
    bannerAd = Provider.of<AdService>(context, listen: false)?.getBannerAd(
      SizerUtil.deviceType == DeviceType.mobile
          ? AdSize.largeBanner
          : SizerUtil.orientation == Orientation.portrait
              ? AdSize.leaderboard
              : AdSize.largeBanner,
      onFailedLoad: (ad, error) {
        print('banner ad failed to load: $error');
        ad.dispose();
      },
      onLoad: (ad) => setState(() => adLoaded = true),
    );

    bannerAd?.load();
  }

  @override
  void dispose() {
    bannerAd?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.transparent,
      width: bannerAd.size.width.toDouble(),
      height: bannerAd.size.height.toDouble(),
      child: Center(
        child: Container(
          color: Colors.white,
          child: AdWidget(
            ad: bannerAd,
          ),
        ),
      ),
    );
  }
}

```

And this service

```
class AdService {
  final isAndroid = Platform.isAndroid;
  final isDebug = !kReleaseMode;

  @override
  BannerAd getBannerAd(AdSize size, {void Function(Ad, LoadAdError) onFailedLoad, void Function(Ad) onLoad}) {
    return BannerAd(
      adUnitId: isDebug
          ? BannerAd.testAdUnitId
          : isAndroid
              ? 'androidBanneId'
              : 'iosBannerId',
      request: AdRequest(),
      size: size,
      listener: BannerAdListener(
        onAdFailedToLoad: onFailedLoad ??
            (ad, error) {
              ad.dispose();
            },
        onAdLoaded: onLoad,
      ),
    );
  }

  @override
  void getInterstitualAd({void Function(LoadAdError) onFailedLoad, void Function(InterstitialAd) onLoad}) {
    InterstitialAd.load(
      adUnitId: isDebug
          ? InterstitialAd.testAdUnitId
          : isAndroid
              ? 'androidBanneId'
              : 'iosBannerId',
      request: AdRequest(),
      adLoadCallback: InterstitialAdLoadCallback(
        onAdLoaded: onLoad ??
            (ad) => ad.fullScreenContentCallback = FullScreenContentCallback(
                  onAdDismissedFullScreenContent: (ad) => ad.dispose(),
                  onAdFailedToShowFullScreenContent: (ad, error) => ad.dispose(),
                ),
        onAdFailedToLoad: onFailedLoad,
      ),
    );
  }

  @override
  void getRewardAd({@required String userId, void Function(LoadAdError) onFailedLoad, void Function(RewardedAd) onLoad}) {
    RewardedAd.load(
      adUnitId: isDebug
          ? RewardedAd.testAdUnitId
          : isAndroid
              ? 'androidBanneId'
              : 'iosBannerId',
      request: AdRequest(),
      rewardedAdLoadCallback: RewardedAdLoadCallback(
        onAdLoaded: onLoad ??
            (ad) => ad.fullScreenContentCallback = FullScreenContentCallback(
                  onAdDismissedFullScreenContent: (ad) => ad.dispose(),
                  onAdFailedToShowFullScreenContent: (ad, error) => ad.dispose(),
                ),
        onAdFailedToLoad: onFailedLoad,
      ),
      serverSideVerificationOptions: ServerSideVerificationOptions(userId: userId),
    );
  }
}
```

**Expected results:** 

We are testing this with ads from a live app that we are making. Those ads work perfectly fine. But those apps are native.

**Actual results:**

The ads are not displaying and we get the following error on Android

```
I/flutter (29600): banner ad failed to load: LoadAdError(code: 3, domain: com.google.android.gms.ads, message: No ad config., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))
android
```

We tried banner, rewarded and intersitual ads. Which are working perfectly fine in the live app.

On IOS get a error that says no ads to show even though the are showing in the live app. It has error code 1

**Comment by michael-ottink** [comment] 2021-07-15 10:42
Add your Phone as test device in Google Admob over at the Settings. Then it should work! When releasing to play store make sure to state that your app is using Ads in the console.

Is what seems to work.

But the error message could be more clear.

**Comment by TahaTesser** [comment] 2021-08-05 14:45
Hi @dutch-game-studio 
This seems to be a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/59
Please upvote the the duplicate issue, closing

**Closed by TahaTesser** 2021-08-05 14:45 UTC
Labels: in triage
