### ISSUE TITLE
macOS m1 CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":

### ISSUE THREAD

**Issue by terrasuscompany** [googleads/googleads-mobile-flutter#303] opened 2021-07-08 11:31 UTC
macOS M1 device
## Plugin Version
0.13.2

## Steps to Reproduce

1. Run `pod install`.

**Expected results:** 

**Actual results:** CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
  In Podfile:
    flutter_admob_app_open (from `.symlinks/plugins/flutter_admob_app_open/ios`) was resolved to 0.0.1, which depends on
      Google-Mobile-Ads-SDK (= 7.69.0)

    google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
      Google-Mobile-Ads-SDK (= 8.5.0)

    native_ads (from `.symlinks/plugins/native_ads/ios`) was resolved to 0.5.0, which depends on
      Google-Mobile-Ads-SDK

<details>
  <summary>CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":</summary>

```
```

```
```

[✓] Flutter (Channel master, 2.4.0-1.0.pre.112, on macOS 11.4 20F71 darwin-arm, locale en-TR)
    • Flutter version 2.4.0-1.0.pre.112 at /usr/local/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3bac804112 (4 hours ago), 2021-07-08 03:01:04 -0400
    • Engine revision 99a2904675
    • Dart version 2.14.0 (build 2.14.0-288.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[!] Android Studio
    • Android Studio at /Users/salim/Downloads/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554                        • android-arm64  • Android 11 (API 30)
      (emulator)
    • iPhone 11 Pro (mobile)    • D3BF5B93-2167-46DE-9AAA-C1699AC6B65E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)              • chrome                               • web-javascript • Google Chrome 91.0.4472.114

</details>

**Comment by kama-tech** [comment] 2021-08-11 06:07
any fix ?

**Comment by maheshmnj** [comment] 2021-08-19 05:51
Hi @terrasuscompany, Running pod install is not recommended because when you run the flutter app flutter executes pod install for you. Could you please try 

```
flutter clean
flutter pub get
```
and then share the output of `flutter run -v`, You will likely need to attach it instead of pasting it.

**Comment by onatcipli** [comment] 2021-08-24 11:30
Hi @maheshmnj, I got the same issue and your recommendation not working for me, Do you have any other advice?

**Comment by maheshmnj** [comment] 2021-08-24 12:12
@onatcipli make sure you are on the latest stable channel and using the latest google ads plugin `0.13.3` and if you are still facing the issue please share the output of `flutter doctor -v` along with `flutter run -v` preferably attach this as a file since the output will be long.

**Comment by kama-tech** [comment] 2021-09-03 03:32
here my flutter doctor 

![issue](https://user-images.githubusercontent.com/17535459/131946590-8c9f03ff-8705-457f-9de4-b74f6b635a9a.png)

**Comment by kama-tech** [comment] 2021-09-03 03:39
this version google_mobile_ads: ^0.12.0  work well on android and ios , but is to old and show deprecated messages

**Comment by maheshmnj** [comment] 2021-09-03 05:01
@kama-tech I would suggest you to please switch to the latest stable by running

```
flutter channel stable
flutter clean
```
and use the latest ads plugin `0.13.4` and if the issue still persists, please share the output of `flutter doctor -v` (text output) and `flutter run -v`

**Comment by kama-tech** [comment] 2021-09-06 02:24
@maheshmnj  here flutter doctor 

MacBook-Air ios % flutter doctor -v
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale en-PR)
    • Flutter version 2.2.3 at /Users/kama/development/flutter
    • Framework revision f4abaa0735 (9 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/kama/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /Users/kama/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • CFF4F0F0-EC3F-4176-980A-796EEBF190A1 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 92.0.4515.159

• No issues found!

**Comment by kama-tech** [comment] 2021-09-06 02:28
@maheshmnj  here fluter run 

[   +9 ms] Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
           To update the CocoaPods specs, run:
             pod repo update
           
[  +15 ms] Error running pod install
[   +1 ms] Error launching application on iPhone 12 Pro Max.
[+2087 ms] "flutter run" took 13,724ms.
[  +45 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:663:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[ +103 ms] ensureAnalyticsSent: 96ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**Comment by maheshmnj** [comment] 2021-09-06 07:00
@kama-tech Can you try running `pod repo update` as suggested in the logs
>To update the CocoaPods specs, run:
             pod repo update

and also please share the complete logs of `flutter run` if it still fails

**Comment by kama-tech** [comment] 2021-09-06 15:38
@maheshmnj  after pod repo update 

pod repo update
Updating spec repo `trunk`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod repo update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.11.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Error

```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle, 0x0009): could not use '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle' because it is not a compatible arch - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:5:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.0/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.0/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.0/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.0/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.0/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.0/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.0/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:141:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:140:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:139:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:139:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:137:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/sources_manager.rb:137:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+could+not+use+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%27+because+it+is+not+a+compatible+arch+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

**Comment by kama-tech** [comment] 2021-09-06 16:55
flutter run
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...                                             797ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A google_mobile_ads
      - Flutter
      - device_info
      - path_provider
      - pdf_render
      - sqflite

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `google_mobile_ads` from `.symlinks/plugins/google_mobile_ads/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `pdf_render` from `.symlinks/plugins/pdf_render/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in
      repo update
      CDN: trunk Relative path: all_pods_versions_5_9_a.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/5/9/a/Google-Mobile-Ads-SDK/8.0.0/Google-Mobile-Ads-SDK.podspec.json exists!
      Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning local because checking is only
      performed in repo update
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local because checking
      is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "Google-Mobile-Ads-SDK":
      In Podfile:
        google_mobile_ads (from `.symlinks/plugins/google_mobile_ads/ios`) was resolved to 0.0.1, which depends on
          Google-Mobile-Ads-SDK (= 8.5.0)

    None of your spec sources contain a spec satisfying the dependency: `Google-Mobile-Ads-SDK (= 8.5.0)`.

    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * mistyped the name or version.
     * not added the source repo that hosts the Podspec to your Podfile.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:1078:in `block in
    resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:1076:in
    `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:241:in `block in
    resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update



Error running pod install
Error launching application on iPhone 12 Pro Max.

**Comment by maheshmnj** [comment] 2021-09-07 06:15
Can you please share your podfile and also try 
```
pod update
```

**Comment by kama-tech** [comment] 2021-09-08 02:41
@maheshmnj    podfile

# Uncomment this line to define a global platform for your project
 platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

**Comment by maheshmnj** [comment] 2021-09-08 09:07
@kama-tech thanks for the info the `podfile` looks fine to me. Are you experiencing this issue on a new flutter project too? And I hope you are using the latest ads plugin `0.13.4`.

**Comment by kama-tech** [comment] 2021-09-11 23:24
@maheshmnj  im trying everything and same issue. 
latest ads plugin 0.13.4
flutter 2.5

**Comment by maheshmnj** [comment] 2021-09-13 04:55
@kama-tech, I am labeling this issue as a bug for further investigation.

Thanks

**Comment by kama-tech** [comment] 2021-09-22 23:10
any update ?

**Comment by jjliu15** [comment] 2021-09-22 23:33
Based on https://github.com/googleads/googleads-mobile-flutter/issues/303#issuecomment-913734105 is seems like `pod repo update` failed. Can you try the workarounds in https://github.com/CocoaPods/CocoaPods/issues/10287 to see if you can successfully update?

Also does the error only happen on macOS M1 devices? Is it reproducible on iOS device?

**Comment by terrasuscompany** [comment] 2021-11-12 09:37
I update and upgrade everything. now its working fine. mac update, plugin update,  flutter dart. everything.

**Comment by ct7ct7ct7** [comment] 2022-05-26 13:46
this problem same in my M1-macbook,
try this to reinstall pod:

`sudo arch -x86_64 gem install ffi `
`arch -x86_64 pod install`

...

`flutter clean`
`flutter pub get`


Good luck

**Comment by srichakradhar** [comment] 2022-07-20 22:25
Closing as it seems to be a transient issue.

**Closed by srichakradhar** 2022-07-20 22:25 UTC
Labels: bug, p2-medium, e3-weeks, platform-ios

**Comment by udoy-touhid** [comment] 2023-11-28 09:45
> this problem same in my M1-macbook, try this to reinstall pod:
> 
> `sudo arch -x86_64 gem install ffi ` `arch -x86_64 pod install`
> 
> ...
> 
> `flutter clean` `flutter pub get`
> 
> Good luck

This doesn't solve the issue on my macbook pro m2 max
