### ISSUE TITLE
App open ads

### ISSUE THREAD

**Issue by WouterVandenputte** [googleads/googleads-mobile-flutter#219] opened 2021-05-09 09:11 UTC
## Proposal

When will this package support [App Open advertisements](https://developers.google.com/admob/android/app-open-ads)?
I would expect that when this library was finally released, it would support the ads that the makes themself publish. But as for now, we have to rely on unofficial third parties packages such as [flutter_admob_app_open](https://pub.dev/packages/flutter_admob_app_open)

**Comment by jjliu15** [comment] 2021-06-08 04:55
This is a duplicate of #171

**Closed by jjliu15** 2021-06-08 04:55 UTC
Labels: duplicate
