### ISSUE TITLE
iOS : MediaView is too small for video

### ISSUE THREAD

**Issue by alixumer** [googleads/googleads-mobile-flutter#1041] opened 2024-03-28 23:42 UTC
![000000](https://github.com/googleads/googleads-mobile-flutter/assets/70147892/321282f5-58b8-4a8b-8cdd-091b0c03fb20)

## Plugin Version

google_mobile_ads: 5.0.0

**Comment by malandr2** [comment] 2024-03-29 14:36
Duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/844

See comment https://github.com/googleads/googleads-mobile-flutter/issues/844#issuecomment-1652432974. This is working as intended.

**Closed by malandr2** 2024-03-29 14:36 UTC
