### ISSUE TITLE
No sound when silent mode is activited

### ISSUE THREAD

**Issue by saddem123** [googleads/googleads-mobile-flutter#766] opened 2023-02-03 16:38 UTC
## Plugin Version
Any version

## Steps to Reproduce

1. Pick IOS device
2. Create native ads with media
3. Pick only videos ad unit or pick the  test ad unit of native advanced video
4. Enable silent mode

Ads sound is not working. 
Taking the example of youtube, video ads sound is working even in silent mode.

**Comment by huycozy** [comment] 2023-02-06 12:06
Hi @saddem123, I'm not sure I can entirely understand the issue.
Can you specify `Actual result` and `Expected result` in detail? It could be helpful if you can provide a recorded video for this.

Also, please provide a [completed and minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) so that we may verify this. 

Or you may try using [plugin sample code](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example), update it corresponding to your case and then update your `Steps to Reproduce` so that we may verify it, thanks!

**Comment by saddem123** [comment] 2023-02-09 10:43
@huycozy
Enable silent mode in ios (the button on the left of the phone on top of the volume buttons) and go to a native ad with video content ->  unmute the ad
`Expected result: sound works`
`Actual result: no sound until remove silent mode `
Taking the example of youtube ads sound works even in silent mode

**Comment by huycozy** [comment] 2023-02-09 11:47
@saddem123 Currently my native ads returns image+text ad so I can not verify NativeAd. 

But when testing with RewardedAd, I see the same result on both Flutter and native code. When turning on silent mode on iPhone, they are no sound on the video ad.


- Flutter: https://github.com/googleads/googleads-mobile-flutter/tree/main/samples/admob/rewarded_example
- iOS native: https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Objective-C/admob/RewardedVideoExample

So I think this is intentional. You may try with NativeAd on [iOS native sample code](https://github.com/googleads/googleads-mobile-ios-examples/tree/main/Objective-C/admob/NativeAdvancedExample) to check this.

**Comment by saddem123** [comment] 2023-02-09 14:42
@huycozy but why is it that when I unmute ads there's no sound too? If the bug is on the ios version, we should discuss it with the google ads ios team to explain how it's working like that. As a user when I unmute content that has a mute/unmute button and there's no sound I consider it a bug what do you think?

**Comment by saddem123** [comment] 2023-02-10 08:32
@huycozy this a project with video ads i created [reproduction](https://github.com/saddem123/Native-ads-impelemntation/tree/reproduce-no-sound-ios) and you run it take on consideration this issue [#458](https://github.com/googleads/googleads-mobile-flutter/issues/458) so you should somtimes re-run the project.

**Comment by huycozy** [comment] 2023-02-10 12:28
>@huycozy but why is it that when I unmute ads there's no sound too?

Do you mean you mute the video by `VideoOptions`'s `startMuted` or mute video manually in runtime? Can you provide a recorded video along with detailed `Steps to reproduce` this?

>If the bug is on the ios version, we should discuss it with the google ads ios team to explain how it's working like that. 

If it's also happening on iOS native plugin, this is out of this plugin's scope. I recommend filing an issue at: https://groups.google.com/g/google-admob-ads-sdk for better support.

**Comment by saddem123** [comment] 2023-02-14 10:29
@huycozy so this a video show how even i want to enable (unmute) the ad sound when silent mode is enabled it's not working. I wish that is clear for you now.
[video of reproduction ](https://drive.google.com/file/d/1Dpl88zJiGUgA5y9cleTQrzTHTTVBxD-8/view?usp=sharing)

**Comment by huycozy** [comment] 2023-02-15 12:24
@saddem123 I watched your video and see it works the same as the result in my [previous comment](https://github.com/googleads/googleads-mobile-flutter/issues/766#issuecomment-1424059604). And I believe it is intentional, please see https://groups.google.com/g/google-admob-ads-sdk/c/DSR2hHCtSI4/m/6kGK-G2gAwAJ.

Closing the issue since it works as intended. Please follow up or leave there your comment on google-admob-ads-sdk group if any.

**Closed by huycozy** 2023-02-15 12:24 UTC
Labels: in triage

**Comment by saddem123** [comment] 2023-02-15 16:43
@huycozy I read the discussion but in a flutter, we don't have the possibility to do a custom player like in native ios & the following feature has not yet been released  [#713](https://github.com/googleads/googleads-mobile-flutter/issues/713)  & don't even have this simple feature [#553](https://github.com/googleads/googleads-mobile-flutter/issues/553) so at least give us the ability to those simple feature how can we work with native ads.
