### ISSUE TITLE
Modified ad behavior Must fix: 3.1.0

### ISSUE THREAD

**Issue by bugrevealingbme** [googleads/googleads-mobile-flutter#948] opened 2023-11-03 15:14 UTC
Every application I updated the Admob version started to give this warning. Only the opening advert has this problem.

Modified ad behavior Must fix
Publishers are not permitted to alter the behavior or targeting of Google ads. This includes implementing the AdSense ad code in a "floating box script," or altering the ad-targeting using hidden keywords or IFRAMES.

Version: google_mobile_ads: ^3.1.0

**Comment by huycozy** [comment] 2023-11-06 11:40
Hi @bugrevealingbme 
This issue seems to be caused by your ad implementation, please see a known issue [here](https://stackoverflow.com/a/70286268/5921933) with Android native as well. And he solved it by following [Implementation guidance](https://support.google.com/admob/answer/2936217?hl=en&ref_topic=9756841&sjid=8073689794858182868-AP).

You may also check [Behavioral policies](https://support.google.com/admob/answer/2753860?hl=en) if it's helpful.

With this, I would recommend raising this to Product support team via [AdMob Help Center](https://support.google.com/admob/community?hl=en) instead. Closing this issue as it doesn't seem to Flutter ad plugin issue.

**Closed by huycozy** 2023-11-06 11:40 UTC
Labels: in triage
