### ISSUE TITLE
NPE caused by native ads after switching between pages and sending the app to background

### ISSUE THREAD

**Issue by kreativityapps** [googleads/googleads-mobile-flutter#480] opened 2022-01-02 18:14 UTC
## Plugin Version

google_mobile_ads 1.0.1

## Steps to Reproduce

1. Implement native ads following the Kotlin example from [codelabs](https://codelabs.developers.google.com/codelabs/admob-inline-ads-in-flutter#7)
2. Open app, check that the native ad is loaded and visible
3. Open a drawer in the app or open a different page in the app so the native ad is covered
4. Send the app to background

**Expected results:** App doesn't crash

**Actual results:** App crashes

<details>
  <summary>Logs</summary>

```
E/AndroidRuntime(30623): FATAL EXCEPTION: main
E/AndroidRuntime(30623): Process: com.my.app, PID: 30623
E/AndroidRuntime(30623): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchWindowVisibilityChanged(int)' on a null object reference
E/AndroidRuntime(30623): 	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
E/AndroidRuntime(30623): 	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
E/AndroidRuntime(30623): 	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
E/AndroidRuntime(30623): 	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
E/AndroidRuntime(30623): 	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1290)
E/AndroidRuntime(30623): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1813)
E/AndroidRuntime(30623): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
E/AndroidRuntime(30623): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7091)
E/AndroidRuntime(30623): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
E/AndroidRuntime(30623): 	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
E/AndroidRuntime(30623): 	at android.view.Choreographer.doFrame(Choreographer.java:638)
E/AndroidRuntime(30623): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
E/AndroidRuntime(30623): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(30623): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(30623): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(30623): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime(30623): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30623): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime(30623): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
    • Flutter version 2.8.1 at /Users/me/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (2 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/me/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME =
      /usr/local/opt/python@3.8/bin:/Users/me/.rvm/gems/ruby-2.7.0/bin:/Users/me/.rvm/gems/ruby-2.7.0@global/bin:/Users/me/.rvm/rubies/ruby-2.7.0/bin:/usr/local/bin:/usr/local
      /bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/me/n/bin:/Users/me/.rvm/bin:/Users/me/Library/Android/sdk/tools:/Users/me/Library/Android/sdk:/Use
      rs/me/Library/Android/sdk/platform-tools:/Users/me/Library/Android/sdk/tools
    • ANDROID_SDK_ROOT = /Users/me/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2020.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 56.0.1
    • Dart plugin version 201.9380

[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • SM G920F (mobile) • 03157df394036a23    • android-arm64  • Android 7.0 (API 24)

• No issues found!

```

</details>

The crash occurs on Android, reproduced it on devices from Android 7 to Android 11 and there are several crashes in production as well.
Tried with older version of Flutter, same crash. Also older versions of the plugin provoke the same issue.

Is the codelabs example missing some additional setup or is this plugin just unusable in the current state?

**Comment by Deep-Focus-lab** [comment] 2022-01-03 08:57
Same problem with banner ads! Tested on Android 11 & Android 12, flutter-beta(2.9.0-0.1.pre) channel, dart sdk 2.15.0

**Comment by maheshmnj** [comment] 2022-01-03 13:12
Hi @kreativityapps, Thanks for filing the issue. I ran this [codelabs example](https://github.com/googlecodelabs/admob-inline-ads-in-flutter/tree/main/complete_kotlin_swift) and I am unable to reproduce the issue. Let me know if I am missing anything.

https://user-images.githubusercontent.com/31410839/147934117-9c8e11bf-ebf2-4e1c-90b9-9811ea92fead.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>


<details>
<summary>logs</summary>

```
W/ContentCatcher(29640): Failed to notify a WebView
Restarted application in 4,761ms.
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5113544, downTime=5113544 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5113600, downTime=5113544 } moveCount:0
D/DynamitePackage(29640): Instantiating com.google.android.gms.ads.ChimeraAdLoaderBuilderCreatorImpl
I/Ads     (29640): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("7533D24B76F3D928E20EB84A8C420B39")) to get test ads on this device.
I/AudioManager(29640): In isSpeakerphoneOn(), calling application: com.codelab.flutter.admobinlineads
D/EgretLoader(29640): EgretLoader(Context context)
D/EgretLoader(29640): The context is not activity
I/DynamiteModule(29640): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:214106404
I/DynamiteModule(29640): Selected remote version of com.google.android.gms.ads.dynamite, version >= 214106404
D/DynamitePackage(29640): Instantiating com.google.android.gms.ads.ChimeraNativeAdViewDelegateCreatorImpl
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5115731, downTime=5115731 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5116176, downTime=5115731 } moveCount:48
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5116587, downTime=5116587 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5116771, downTime=5116587 } moveCount:10
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5117384, downTime=5117384 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5117509, downTime=5117384 } moveCount:9
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5117853, downTime=5117853 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5117979, downTime=5117853 } moveCount:9
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5122796, downTime=5122796 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5122912, downTime=5122796 } moveCount:7
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5123358, downTime=5123358 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5123483, downTime=5123358 } moveCount:11
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5126884, downTime=5126884 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5127695, downTime=5126884 } moveCount:60
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5128403, downTime=5128403 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5128511, downTime=5128403 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5129218, downTime=5129218 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5129292, downTime=5129218 } moveCount:0
D/DynamitePackage(29640): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     (29640): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("7533D24B76F3D928E20EB84A8C420B39")) to get test ads on this device.
I/AudioManager(29640): In isSpeakerphoneOn(), calling application: com.codelab.flutter.admobinlineads
D/EgretLoader(29640): EgretLoader(Context context)
D/EgretLoader(29640): The context is not activity
I/DynamiteModule(29640): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:214106404
I/DynamiteModule(29640): Selected remote version of com.google.android.gms.ads.dynamite, version >= 214106404
W/ContentCatcher(29640): Failed to notify a WebView
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5130466, downTime=5130466 } moveCount:0
W/System  (29640): A resource failed to call release.
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5130979, downTime=5130466 } moveCount:51
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5131373, downTime=5131373 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5131802, downTime=5131373 } moveCount:45
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5135463, downTime=5135463 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5137553, downTime=5135463 } moveCount:209

```
</details>

 Thanks

**Comment by maheshmnj** [comment] 2022-01-03 13:12
Hi @kreativityapps, Thanks for filing the issue. I ran this [codelabs example](https://github.com/googlecodelabs/admob-inline-ads-in-flutter/tree/main/complete_kotlin_swift) and I am unable to reproduce the issue. Let me know if I am missing anything.

https://user-images.githubusercontent.com/31410839/147934117-9c8e11bf-ebf2-4e1c-90b9-9811ea92fead.mov

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 2.8.1 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Redmi K20 Pro (mobile) • 192.168.1.2:5555 • android-arm64  • Android 11 (API 30)
    • macOS (desktop)        • macos            • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)           • chrome           • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```
</details>


<details>
<summary>logs</summary>

```
W/ContentCatcher(29640): Failed to notify a WebView
Restarted application in 4,761ms.
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5113544, downTime=5113544 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5113600, downTime=5113544 } moveCount:0
D/DynamitePackage(29640): Instantiating com.google.android.gms.ads.ChimeraAdLoaderBuilderCreatorImpl
I/Ads     (29640): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("7533D24B76F3D928E20EB84A8C420B39")) to get test ads on this device.
I/AudioManager(29640): In isSpeakerphoneOn(), calling application: com.codelab.flutter.admobinlineads
D/EgretLoader(29640): EgretLoader(Context context)
D/EgretLoader(29640): The context is not activity
I/DynamiteModule(29640): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:214106404
I/DynamiteModule(29640): Selected remote version of com.google.android.gms.ads.dynamite, version >= 214106404
D/DynamitePackage(29640): Instantiating com.google.android.gms.ads.ChimeraNativeAdViewDelegateCreatorImpl
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5115731, downTime=5115731 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5116176, downTime=5115731 } moveCount:48
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5116587, downTime=5116587 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5116771, downTime=5116587 } moveCount:10
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5117384, downTime=5117384 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5117509, downTime=5117384 } moveCount:9
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5117853, downTime=5117853 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5117979, downTime=5117853 } moveCount:9
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5122796, downTime=5122796 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5122912, downTime=5122796 } moveCount:7
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5123358, downTime=5123358 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5123483, downTime=5123358 } moveCount:11
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5126884, downTime=5126884 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5127695, downTime=5126884 } moveCount:60
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5128403, downTime=5128403 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5128511, downTime=5128403 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5129218, downTime=5129218 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5129292, downTime=5129218 } moveCount:0
D/DynamitePackage(29640): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     (29640): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("7533D24B76F3D928E20EB84A8C420B39")) to get test ads on this device.
I/AudioManager(29640): In isSpeakerphoneOn(), calling application: com.codelab.flutter.admobinlineads
D/EgretLoader(29640): EgretLoader(Context context)
D/EgretLoader(29640): The context is not activity
I/DynamiteModule(29640): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:214106404
I/DynamiteModule(29640): Selected remote version of com.google.android.gms.ads.dynamite, version >= 214106404
W/ContentCatcher(29640): Failed to notify a WebView
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5130466, downTime=5130466 } moveCount:0
W/System  (29640): A resource failed to call release.
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5130979, downTime=5130466 } moveCount:51
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5131373, downTime=5131373 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5131802, downTime=5131373 } moveCount:45
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_DOWN, id[0]=0, pointerCount=1, eventTime=5135463, downTime=5135463 } moveCount:0
D/MIUIInput(29640): [MotionEvent] ViewRootImpl { action=ACTION_UP, id[0]=0, pointerCount=1, eventTime=5137553, downTime=5135463 } moveCount:209

```
</details>

 Thanks

**Comment by Deep-Focus-lab** [comment] 2022-01-03 13:48
Please test on a app that have a page with ads.. 
open the page then navigate to another page that the ad page goes to navigation backstack.. 
then try to minimise the app..

**Comment by kreativityapps** [comment] 2022-01-03 14:22
Hi @maheshmnj , thank you for the quick reply.

After checking the code in detail I found what caused the problem in my case.

To try to improve native ad performance I called `PlatformViewsService.synchronizeToNativeViewHierarchy(false)` in Flutter main. After removing this it doesn't crashes anymore. 

Performance is still terrible because of the ad also in the example app, but that's another topic. At least the crash is gone.

Thank you!

**Comment by maheshmnj** [comment] 2022-01-04 06:57
> Please test on a app that have a page with ads..
open the page then navigate to another page that the ad page goes to navigation backstack..
then try to minimise the app..

@Deep-Focus-lab if you see in the above video There is a native ad or the banner ad and then the app is put to background. If you are still experiencing the issue. Please file a separate issue with all the requested details in the issue template.

**Comment by maheshmnj** [comment] 2022-01-04 06:57
Thanks for the info @kreativityapps, Glad you solved it.
Closing as solved.

**Closed by maheshmnj** 2022-01-04 06:57 UTC
Labels: feedback required, in triage
