### ISSUE TITLE
Ads are missing frames inside a listview builder.

### ISSUE THREAD

**Issue by Kabilan21** [googleads/googleads-mobile-flutter#239] opened 2021-05-17 18:09 UTC
I tried to integrate Admob native ads in a listview. Ad loads perfectly inside a listview build. When I scroll the list view in any direction the ad widget moves out of sync, not aligning correctly with other UI components. It a very serious issue that makes the AdMob SDK not useable for native ads.

google_mobile_ads: ^0.12.1+1
flutter:2.0.2

Steps to reproduce the problem:
   
1. Use simple native ads inside a list view or listeview.builder.
2. Scrolling the list view results in missing frames , abnormal movement of the ad widget.

2.  The repository https://github.com/googlecodelabs/admob-inline-ads-in-flutter which is given in the codelab tutorial also experiences the same problem.Ad widgets are missing frames and produce abnormal scroll behaviors.

Target Platform: Android
Target OS version: targetSdkVersion 30
Mobile Phone
No errors

<details>
<summary>Logs
 Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ContentCatcher( 3433): Failed to notify a WebView
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/Choreographer( 3433): Already have a pending vsync event.  There should only be one at a time.
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/Looper  ( 3433): Slow Frame: doFrame is 344ms late
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
I/DynamiteModule( 3433): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210890500
I/DynamiteModule( 3433): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210890500
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
D/AudioManager( 3433): getStreamVolume isRestricted mode = 0
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
W/ImageReader_JNI( 3433): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers

</summary>

flutter analyze :

   info - Unused import: 'package:google_mobile_ads/google_mobile_ads.dart' - lib\main.dart:6:8 - unused_import
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -     
          lib\ui\authpage\loginview\login_view.dart:209:18 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -     
          lib\ui\authpage\loginview\login_view.dart:298:18 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -     
          lib\ui\authpage\signinview\signin_view.dart:372:18 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -     
          lib\ui\authpage\signinview\signin_view.dart:412:18 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -     
          lib\ui\authpage\signinview\signin_view.dart:464:20 - deprecated_member_use
   info - 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. -      
          lib\ui\authpage\signinview\signin_view.dart:469:40 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\ui\authpage\signinview\signin_view.dart:623:26 - deprecated_member_use
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. - lib\ui\rootpage\root.dart:170:9 -
          deprecated_member_use
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. - lib\ui\rootpage\root.dart:180:9 -
          deprecated_member_use
   info - 'FlatButton' is deprecated and shouldn't be used. Use TextButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. - lib\ui\rootpage\ui\appupdate.dart:43:9 -     
          deprecated_member_use
   info - Unused import: 'package:hiphop/xscreens/story/bloc/storyview_bloc.dart' - lib\ui\rootpage\ui\widgets.dart:9:8 - unused_import
   info - Unused import: 'package:hiphop/xscreens/story/ui/story_list_view.dart' - lib\ui\rootpage\ui\widgets.dart:10:8 - unused_import
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\earnings\ui\earnings_view.dart:331:21 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\earnings\ui\earnings_view.dart:367:17 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\earnings\ui\earnings_view.dart:391:19 - deprecated_member_use
   info - 'showSnackBar' is deprecated and shouldn't be used. Use ScaffoldMessenger.showSnackBar. This feature was deprecated after v1.23.0-14.0.pre. -      
          lib\xscreens\editprofile\ui\profile_edit.dart:146:46 - deprecated_member_use
   info - Unused import: 'package:hiphop/common/adtype/native_ad.dart' - lib\xscreens\feeds\ui\feeds_view.dart:4:8 - unused_import
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\profile\ui\profile_top.dart:112:19 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\profile\ui\profile_top.dart:135:19 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\profile\ui\profile_top.dart:163:19 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\scratchcard\ui\scratch_view.dart:104:29 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\scratchcard\ui\scratch_view.dart:132:29 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\scratchcard\ui\scratch_view.dart:303:21 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\scratchcard\ui\scratch_view.dart:339:17 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\scratchcard\ui\scratch_view.dart:363:19 - deprecated_member_use
   info - Unused import: 'package:hiphop/helpers/timestamp_function.dart' - lib\xscreens\storyeditor\bloc\storyeditor_bloc.dart:9:8 - unused_import
   info - The value of the local variable 'nbrCircleLine' isn't used - lib\xscreens\storyeditor\ui\material_color_picker.dart:179:15 - unused_local_variable 
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\userprofile\ui\userprofile_top.dart:88:19 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\userprofile\ui\userprofile_top.dart:111:19 - deprecated_member_use
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\xscreens\userprofile\ui\userprofile_top.dart:139:19 - deprecated_member_use

31 issues found. (ran in 27.9s)

[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.18363.1379], locale en-US)
    • Flutter version 2.0.2 at C:\Users\kabil\Documents\flutter
    • Framework revision 8962f6dc68 (10 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\kabil\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\kabil\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (1 available)
    • Redmi Note 5 (mobile) • 192.168.43.1:5555 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!

**Comment by blasten** [comment] 2021-05-25 20:28
What version of Android are you using? `targetSdkVersion` isn't the OS version.

**Comment by Kabilan21** [comment] 2021-05-26 04:34
The device used to test the ad implementation runs on android oreo.

**Comment by TahaTesser** [comment] 2021-08-05 14:59
Closing as duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/269

**Closed by TahaTesser** 2021-08-05 14:59 UTC
Labels: in triage
