### ISSUE TITLE
Banner ad still displayed during page close animation

### ISSUE THREAD

**Issue by jld3103** [googleads/googleads-mobile-flutter#319] opened 2021-07-22 11:42 UTC
## Plugin Version

`0.13.2`

## Steps to Reproduce

1. Clone https://github.com/stack11/flutter_google_ads_rendering_bug
2. Run the app on android (only tested on android, issue might happen on other platforms too)
3. Click the button, wait for the banner to load and then close the page

**Expected results:**
The banner ad shouldn't be visible during the page close animation.

**Actual results:**

https://user-images.githubusercontent.com/26026535/126633527-0f3842d0-9eb0-4fec-a4e7-50e023339b96.mp4

<details>

```
Analyzing flutter_google_ads_rendering_bug...                           
No issues found! (ran in 1.6s)
```

```
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.3 at /home/work/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/work/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/work/Android/Sdk
    • Java binary at: /home/work/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Android Studio (version 4.2)
    • Android Studio at /home/work/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Chromium 92.0.4515.107 Arch Linux

• No issues found!
```

</details>

**Comment by TahaTesser** [comment] 2021-07-27 15:52
Hi @jld3103 
This is not a bug with `google_mobile_ads`, this is just transition animation, you can reproduce behavior with widget

### Ad
https://user-images.githubusercontent.com/48603081/127184501-2bad93f7-f1b7-42a6-97ad-8a7fe1886ff5.mp4
### Flutter Widget
https://user-images.githubusercontent.com/48603081/127184738-179af80c-f7f3-4b30-9acb-71dc65ed3225.mp4



<details> 
<summary>minimal code sample</summary> 

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(
    MaterialApp(
      home: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: ElevatedButton(
          onPressed: () {
            Navigator.of(context).push(MaterialPageRoute(
              builder: (context) => BannerPage(),
            ));
          },
          child: Text('open'),
        ),
      ),
    );
  }
}

class BannerPage extends StatefulWidget {
  @override
  _BannerPageState createState() => _BannerPageState();
}

class _BannerPageState extends State<BannerPage> {
  BannerAd? _anchoredBanner;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance!.addPostFrameCallback((_) async {
      final AnchoredAdaptiveBannerAdSize? size =
          await AdSize.getAnchoredAdaptiveBannerAdSize(
        Orientation.portrait,
        MediaQuery.of(context).size.width.truncate(),
      );

      if (size == null) {
        print('Unable to get height of anchored banner.');
        return;
      }

      final BannerAd banner = BannerAd(
        size: size,
        request: AdRequest(),
        adUnitId: Platform.isAndroid
            ? 'ca-app-pub-3940256099942544/6300978111'
            : 'ca-app-pub-3940256099942544/2934735716',
        listener: BannerAdListener(
          onAdLoaded: (Ad ad) {
            print('$BannerAd loaded.');
            setState(() {
              _anchoredBanner = ad as BannerAd?;
            });
          },
          onAdFailedToLoad: (Ad ad, LoadAdError error) {
            print('$BannerAd failedToLoad: $error');
            ad.dispose();
          },
          onAdOpened: (Ad ad) => print('$BannerAd onAdOpened.'),
          onAdClosed: (Ad ad) => print('$BannerAd onAdClosed.'),
        ),
      );
      banner.load();
    });
  }

  @override
  void dispose() {
    _anchoredBanner?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      // body: Center(
      //   child: FlutterLogo(
      //   size: 300,
      //   ),
      // ),
      body: Center(
        child: Builder(builder: (context) {
          if (_anchoredBanner != null) {
            return Container(
              color: Colors.green,
              width: _anchoredBanner!.size.width.toDouble(),
              height: _anchoredBanner!.size.height.toDouble(),
              child: AdWidget(ad: _anchoredBanner!),
            );
          }
          return CircularProgressIndicator();
        }),
      ),
    );
  }
}
``` 

</details>

You probably get around by using [RouteObserver](https://api.flutter.dev/flutter/widgets/RouteObserver-class.html)

Closing, as this isn't an issue with `google_mobile_ads` itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by TahaTesser** 2021-07-27 15:52 UTC
Labels: in triage

**Comment by jld3103** [comment] 2021-07-27 17:20
To me it looks a bit different. The opacity of the ad is 100% while the opacity of the rest of the page that is closing is decreasing. I will try to make measurements to confirm or deny this.

**Comment by TahaTesser** [comment] 2021-07-28 10:59
@jld3103 
I agree but it is still a Flutter issue, as some animations or widgets doesn't work properly  on platform views

**Comment by jld3103** [comment] 2021-07-28 11:02
Yes that's true. Do you know if there is an issue about that already?
