### ISSUE TITLE
Native ad causes random crash, GADInspectorExtras 

### ISSUE THREAD

**Issue by nikorehnback** [googleads/googleads-mobile-flutter#1022] opened 2024-03-12 11:04 UTC
### Env

iPhone 11 Pro, iOS version 17.3.1

google_mobile_ads: ^4.0.0

## Steps to Reproduce

1. Implement native ad widget
2. Have native ad widget rendered in screen
3. Navigate inside the app to other screens

**Expected results:** No crashes

**Actual results:** Crash occurs randomly, trace from TestFlight testing attached

<details>
  <summary>Logs</summary>

#0	(null) in __pthread_kill ()
#1	(null) in pthread_kill ()
#2	(null) in __abort ()
#3	(null) in abort ()
#4	(null) in malloc_vreport ()
#5	(null) in malloc_report ()
#6	(null) in find_zone_and_free ()
#7	(null) in -[__NSArrayM insertObject:atIndex:] ()
#8	(null) in GADMutableArrayAddObject ()
#9	(null) in GADInspectorExtras ()
#10	(null) in GADRenderServerTransaction ()
#11	(null) in GADRenderServerTransaction ()
#12	(null) in _dispatch_call_block_and_release ()
#13	(null) in _dispatch_client_callout ()
#14	(null) in _dispatch_queue_override_invoke ()
#15	(null) in _dispatch_root_queue_drain ()
#16	(null) in _dispatch_worker_thread2 ()
#17	(null) in _pthread_wqthread ()
#18	(null) in start_wqthread ()

</details>

## Flutter doctor

```
[✓] Flutter (Channel stable, 3.19.1, on macOS 13.5 22G74 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.0)
[✓] Connected device (7 available)
[✓] Network resources

• No issues found!
```

**Comment by malandr2** [comment] 2024-03-12 15:40
Hi @nikorehnback, the stack trace is a little vague and somewhat infeasible to troubleshoot without a reproducible case. Can you provide the full stack trace? Are there any more detailed reproducible steps? Can you provide a minimum reproducible sample or reproduce using our native_ad sample?

There was an Ad Inspector crash resolved in Google Mobile Ads iOS version 11.0.0 ([release notes](https://developers.google.com/admob/ios/rel-notes)) that may have inherently resolved this crash. We will be updating the Flutter google_mobile_ads plugin soon to build against the latest major version so as a result it may also address this issue.

**Comment by nikorehnback** [comment] 2024-03-12 15:54
Was it related to this? https://github.com/googleads/googleads-mobile-flutter/issues/704

I got that crash snippet from TestFlight crashes, not sure if there is any way to get larger trace out of it.

Unfortunately we have no idea how to reproduce this, it seems to be random. Any idea when plugin update containing 11.0.0 will be out?

**Comment by malandr2** [comment] 2024-03-12 16:02
@nikorehnback, it's possible but also not the most ideal because https://github.com/googleads/googleads-mobile-flutter/issues/704 is also vague. That being said we expect the plugin update to be released before the end of the month. If you are still seeing this crash in the new update my next step would be to create a thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk) as it would appear to be more closely related to the iOS Google Mobile Ads SDK.

**Comment by malandr2** [comment] 2024-03-20 20:48
Closing as `5.0.0` as been released. Please follow up / create a new thread in the forum if the issue still persists. Thanks!

**Closed by malandr2** 2024-03-20 20:48 UTC
Labels: platform-ios
