### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method _init on channel plugins.flutter.io/google_mobile_ads)

### ISSUE THREAD

**Issue by JakeGi** [googleads/googleads-mobile-flutter#1110] opened 2024-06-10 03:10 UTC
Flutter 3.19.4 
Dart 3.3.2 

Report this error according to the document integration

E/flutter (31920): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method _init on channel plugins.flutter.io/google_mobile_ads)
E/flutter (31920): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (31920): <asynchronous suspension>
E/flutter (31920): 
E/flutter (31920): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)
E/flutter (31920): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (31920): <asynchronous suspension>
E/flutter (31920): #1      AdInstanceManager.initialize (package:google_mobile_ads/src/ad_instance_manager.dart:439:13)

**Comment by malandr2** [comment] 2024-06-10 13:38
Hi @JakeGi based on an Internet search it looks like this can be resolved by running `flutter clean` and restarting.

https://stackoverflow.com/questions/71646547/unhandled-exception-missingpluginexceptionno-implementation-found-for-method-f
https://stackoverflow.com/questions/48360060/missingpluginexceptionno-implementation-found-for-method-init-on-channel-plugin

Have you tried these steps? If not, can you provided any reproducible steps to replicate in a sample project?

**Comment by malandr2** [comment] 2024-06-17 14:05
Closing due to inactivity

**Closed by malandr2** 2024-06-17 14:05 UTC
Labels: feedback required
