### ISSUE TITLE
[Feature Request] NativeAd borderRadius

### ISSUE THREAD

**Issue by jhlee-danbi** [googleads/googleads-mobile-flutter#921] opened 2023-09-15 08:54 UTC
hello.
I'm using the `NativeAd` widget.
Can I request additional features for the design?

I need a NativeAd widget with `rounded borders`.
I've searched, but I can't find this feature.

`native-ads-playbook` has a round design as shown in the following image.

https://admob.google.com/intl/ko/home/resources/native-ads-playbook/

![스크린샷 2023-09-15 오후 5 37 12](https://github.com/googleads/googleads-mobile-flutter/assets/99167999/e90bc7d4-397e-481a-aeed-aab78375dfc0)

---

The current status is as follows..

![IMG_2484](https://github.com/googleads/googleads-mobile-flutter/assets/99167999/20760e8d-6ea9-4099-81f0-31de7ed14afd)

I would like to use a round border design -> `both TemplateType.small and TemplateType.medium`.

**Comment by huycozy** [comment] 2023-09-15 12:11
Closing this as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/880. Please follow up on it for further updates. You can leave there your comment and react an upvote to the original comment will help to raise the issue.

**Closed by huycozy** 2023-09-15 12:11 UTC
Labels: in triage
