### ISSUE TITLE
Issue when initialize iOS

### ISSUE THREAD

**Issue by trungtinh961** [googleads/googleads-mobile-flutter#492] opened 2022-01-18 10:25 UTC
## Plugin Version

google_mobile_ads: ^1.0.1

## Steps to Reproduce

When I call MobileAds.instance.initialize() in main file, I receive a error as below, so ads not working

**Expected results:** 

**Actual results:** 

```
- Unhandled Exception: MissingPluginException(No implementation found for method _init on channel plugins.flutter.io/google_mobile_ads)
- Unhandled Exception: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)
<details>

  <summary>Logs</summary>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method _init on channel plugins.flutter.io/google_mobile_ads)
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:165
<asynchronous suspension>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads)
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:165
<asynchronous suspension>
#1      AdInstanceManager.initialize
package:google_mobile_ads/src/ad_instance_manager.dart:384
<asynchronous suspension>
```
</details>

**Comment by maheshmnj** [comment] 2022-01-18 11:18
Hi @trungtinh961, Thanks for filing the issue. Please share the output of `flutter doctor -v` and `flutter run -v`

Thanks

**Comment by trungtinh961** [comment] 2022-01-19 02:54
> 

flutter doctor -v:
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.1 20G224 darwin-x64, locale en-VN)
    • Flutter version 2.8.1 at /Users/nguyentrungtinh/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (5 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/nguyentrungtinh/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • iPhone X of iOS Team (mobile) • 48e068a66bf0769f248a7143e31d7415598427d1 • ios            • iOS 15.1 19B74
    • Chrome (web)                  • chrome                                   • web-javascript • Google Chrome 97.0.4692.71

! Doctor found issues in 1 category.
```

**Comment by trungtinh961** [comment] 2022-01-19 03:03
> Hi @trungtinh961, Thanks for filing the issue. Please share the output of `flutter doctor -v` and `flutter run -v`
> 
> Thanks

Here are dependencies I use in my app:
`  flutter:
    sdk: flutter
  rxdart: ^0.27.1
  dartz: ^0.10.0-nullsafety.1
  kt_dart: ^0.10.0
  intl: ^0.17.0
  readmore: ^2.0.0
  decimal: ^2.0.0
  eventual: ^0.10.4
  fbroadcast: ^1.0.2
  flutter_countdown_timer: ^4.0.2
  flutter_email_sender: ^5.0.0
  open_mail_app: ^0.4.1
  import_sorter: ^4.4.2
  qr_code_scanner: ^0.6.1
  flutter_svg: ^1.0.0
  cached_network_image: ^3.0.0
  image: ^3.0.2
  path_provider: ^2.0.1  # ANDROID IOS
  path: ^1.8.0
  injectable: ^1.2.2
  get_it: ^7.1.3
  connectivity: ^3.0.3
  dio: ^4.0.0
  device_info: ^2.0.0
  package_info: ^2.0.0
  url_launcher: ^6.0.3
  share_plus: ^3.0.4
  google_maps_flutter: ^2.0.6
  geolocator: ^8.0.0
  geocoding: ^2.0.0
  logger: ^1.0.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.7
  camera: ^0.9.4+5
  firebase_core: ^1.0.2
  firebase_crashlytics: ^2.0.0 # ios, android
  firebase_analytics: ^8.1.2
  map_launcher: ^2.0.0-nullsafety.0
  permission_handler: ^8.1.1
  app_settings: ^4.1.1
  firebase_messaging: ^11.2.0
  flutter_local_notifications: ^9.1.4
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.12
  auto_size_text: ^3.0.0-nullsafety.0
  shimmer: ^2.0.0-nullsafety.0
  flutter_keyboard_visibility: ^5.0.0
  dropdown_search: ^2.0.1
  qr_flutter: ^4.0.0
  flutter_rating_bar: ^4.0.0
  local_auth: ^1.1.5
  keyboard_actions: ^3.3.1+1
  flutter_staggered_grid_view: ^0.4.0
  extended_nested_scroll_view: ^3.0.0
  carousel_slider: ^4.0.0
  country_codes: ^2.0.1
  group_list_view: ^1.1.1
  flutter_slidable: ^1.1.0
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4
  syncfusion_flutter_datepicker: ^19.2.62
  contacts_service: ^0.6.3
  stop_watch_timer: ^1.3.1
  android_intent: ^2.0.2
  syncfusion_flutter_charts: ^19.3.44+1
  lottie: ^1.2.1
  equatable: 2.0.3
  video_player: ^2.2.11
  chewie: ^1.2.2
  flutter_inappwebview: ^5.3.2
  photo_view: ^0.13.0
  just_audio: ^0.9.18
  audio_video_progress_bar: ^0.10.0
  flutter_cache_manager: ^3.3.0
  easy_debounce: ^2.0.2+1
  emoji_picker_flutter: ^1.0.8
  flutter_link_previewer: ^2.6.2
  flutter_chat_types: ^3.2.2
  google_mobile_ads: ^1.0.1`

**Comment by LeNguyen0608** [comment] 2022-01-19 09:05
The same issue.

**Comment by trungtinh961** [comment] 2022-01-19 11:55
@maheshmnj I figured out the root cause was missing `registerWithRegistrar` library in the `GeneratedPluginRegistrant.m` file. How can I fix it other than manually overwriting it?

```
#if __has_include(<google_mobile_ads/FLTGoogleMobileAdsPlugin.h>)
#import <google_mobile_ads/FLTGoogleMobileAdsPlugin.h>
#else
@import google_mobile_ads;
#endif

[FLTGoogleMobileAdsPlugin registerWithRegistrar:[registry registrarForPlugin:@"FLTGoogleMobileAdsPlugin"]];
```

**Comment by maheshmnj** [comment] 2022-01-19 12:03
@trungtinh961  You shouldn't be editing that file it will auto-generate when you do `flutter pub get`.

Closing as solved.

**Comment by maheshmnj** [comment] 2022-01-19 12:05
@LeNguyen0608  Please check if `flutter clean` and `flutter pub get` resolved the issue.

**Comment by LeNguyen0608** [comment] 2022-01-19 12:47
> @LeNguyen0608 Please check if `flutter clean` and `flutter pub get` resolved the issue.

I ran `flutter clean` and `flutter pub get` but the problem is still not solved (automatically). However, I try to add manually like @trungtinh961 , the issue is gone.

**Comment by maheshmnj** [comment] 2022-01-19 12:49
I believe the reason it didn't work was because the  `GeneratedPluginRegistrant.m` with misconfiguration.

**Comment by LeNguyen0608** [comment] 2022-01-19 12:52
> I believe the reason it didn't work was because the `GeneratedPluginRegistrant.m` was already present with misconfiguration.

How can I check if it works correctly? And How to fix it?

**Closed** 2022-01-20 05:41 UTC
Labels: solved

**Comment by Nepherius** [comment] 2022-07-02 11:02
Having same issue on Android

**Comment by cmk961012** [comment] 2022-07-30 23:37
This issue still exists even in a fresh app. `flutter clean` and `flutter pub get` didn't help

**Comment by battlecook** [comment] 2022-08-17 04:55
The same issue.

**Comment by Sandeepgupta1998** [comment] 2023-01-18 10:13
Error: MissingPluginException(No implementation found for method MobileAds#initialize on channel plugins.flutter.io/google_mobile_ads
