### ISSUE TITLE
IOS ads not showing up when uses live Ad Ids, works fine for test Ids

### ISSUE THREAD

**Issue by Abdulah-butt** [googleads/googleads-mobile-flutter#936] opened 2023-10-11 07:37 UTC
I am getting following error in Xcode when i replace Test Ads ids with live one. For Test Ids, Ads are showing in IOS but as soon as i repalce it with live Ids, following error comes up

`flutter: BannerAd failed to load: LoadAdError(code: 1, domain: com.google.admob, message: Request Error: No ad to show., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: null, adapterResponses: [], loadedAdapterResponseInfo: AdapterResponseInfo(adapterClassName: , latencyMillis: 0, description: , adUnitMapping: {}, adError: null, adSourceName: , adSourceId: , adSourceInstanceName: , adSourceInstanceId: )), responseExtras: {})`

**Comment by huycozy** [comment] 2023-10-11 10:24
Closing this as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/458. Please take a look at https://github.com/googleads/googleads-mobile-flutter/issues/458#issuecomment-1648667926 for the details.

**Closed by huycozy** 2023-10-11 10:24 UTC
Labels: in triage

**Comment by Abdulah-butt** [comment] 2023-10-12 09:36
any fixes?
