### ISSUE TITLE
This ad may have not been loaded or has been disposed.

### ISSUE THREAD

**Issue by Xiaoqi-01** [googleads/googleads-mobile-flutter#335] opened 2021-08-11 04:00 UTC
This ad may have not been loaded or has been disposed.
Ad with the following id could not be found:0.

```
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>
```

```dart
final BannerAd banner = BannerAd(
      size: size,
      request: request,
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
      listener: BannerAdListener(
        onAdLoaded: (Ad ad) {
          print('$BannerAd loaded.');
          setState(() {
            _anchoredBanner = ad as BannerAd;
          });
        },
        onAdFailedToLoad: (Ad ad, LoadAdError error) {
          print('$BannerAd failedToLoad: $error');
          ad.dispose();
        },
        onAdOpened: (Ad ad) => print('$BannerAd onAdOpened.'),
        onAdClosed: (Ad ad) => print('$BannerAd onAdClosed.'),
      ),
    );
```

> Hi @Xiaoqi-01, Please share the output of `flutter doctor -v` and ensure that you have initialized the ads instance like this
> 
> ```
> void main() {
>   WidgetsFlutterBinding.ensureInitialized();
>   MobileAds.instance.initialize();
>   runApp(MyApp());
> }
> ```
> 
> if the problem still persists, please share the complete reproducible code sample.
> 
> Thank you.

This my flutter 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize()
  if (Platform.isAndroid) {
    SystemUiOverlayStyle systemUiOverlayStyle = SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarBrightness: Brightness.light,
      statusBarIconBrightness: Brightness.dark,
    );
    SystemChrome.setSystemUIOverlayStyle(systemUiOverlayStyle);
  }
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown
  ]);
  runApp(MyApp(
  ));
}

My flutter  project  as  a Module in Native project with flutter_boost. Then use   AdWidget(ad: _anchoredBanner)  will  error like that

**Comment by maheshmnj** [comment] 2021-08-11 11:35
Hi @Xiaoqi-01, Please share the output of `flutter doctor -v` and ensure that you have initialized the ads instance like this

```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  MobileAds.instance.initialize();
  runApp(MyApp());
}
```
 if the problem still persists, please share the complete reproducible code sample.
 
 Thank you.

**Comment by maheshmnj** [comment] 2021-09-28 13:41
closing this issue as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/388, Please follow up there for further updates, Closing this issue as a duplicate, If you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by amosogra** [comment] 2022-02-16 18:38
Hello [maheshmnj](https://github.com/maheshmnj), I disagree. The example for #388 didn't address the issue for google_mobile_ads: ^1.1.0, please reopen this issue. Thanks

**Comment by maheshmnj** [comment] 2022-02-18 06:43
Reopening based on the above comment.

@amosogra could you please share a reproducible sample project along with the steps to reproduce the issue?

Thanks

**Closed** 2022-03-11 07:06 UTC
Labels: feedback required, in triage
