### ISSUE TITLE
Native full screen ads are not displayed properly on Android

### ISSUE THREAD

**Issue by hina06botify** [googleads/googleads-mobile-flutter#1184] opened 2024-10-08 11:56 UTC
It looks like big native ads how can it display full-screen native ads in a full-screen layout .....

**Comment by malandr2** [comment] 2024-10-08 14:26
Duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/1173

You can use `Platform style` to control how the layout looks in the native (Android/iOS) layer

**Closed by malandr2** 2024-10-08 14:26 UTC
Labels: duplicate

**Comment by hina06botify** [comment] 2024-10-09 06:17
I'm trying the following code to load a native full-screen ad:
_adsController.nativeFullScreen = NativeAd(
  adUnitId: "ca-app-pub-3940256099942544/2247696110",
  factoryId: 'GoogleFullScreenAds',
  nativeAdOptions: NativeAdOptions(mediaAspectRatio: MediaAspectRatio.portrait),
  listener: NativeAdListener(
    onAdLoaded: (ad) {
      log('$NativeAd native full screen loaded successfully');
      _adsController.fullScreenNativeIsLoaded.value = true;
    },
    onAdFailedToLoad: (ad, error) {
      log('$NativeAd native full screen failed to load: $error');
      ad.dispose();
      if (_adsController.adType.value == 3) {
        _adsController.showNativeFullScreen1 = NativeAdShowType.Facebook;
        preloadFullFbNativeAd();
      }
      _adsController.fullScreenNativeAdIsError.value = true;
    },
  ),
  request: const AdRequest(),
)..load();


However, the ad does not cover the full screen. In my native ad template, the MediaView is defined as follows:

xml:
  <com.google.android.gms.ads.nativead.MediaView
    android:id="@+id/ad_media"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_above="@+id/linTopView" />
    I want the native template to display a full-screen image, but it's not displaying correctly. How can I fix this issue to ensure that the image appears in full screen?
