### ISSUE TITLE
🐛Reported framerate issues with BannerAd on some Android devices

### ISSUE THREAD

**Issue by gkovac42** [googleads/googleads-mobile-flutter#167] opened 2021-04-10 15:31 UTC
I've had multiple users report serious framerate drops when BannerAd is displayed on the screen. The issue is not consistent, rather it's present only on certain devices (wasn't able to discern a pattern as of yet) and I wasn't able to reproduce it, but it's certainly there, even after Flutter 2.0.0 update.

I'm using google_mobile_ads 0.12.1 and flutter 2.0.4

Here is the sample code of the ad itself:

```
dungeonAd = BannerAd(
      adUnitId: DUNGEON_UNIT_ID_ANDROID,
      size: AdSize.banner,
      request: AdRequest(),
      listener: AdListener(),
    )..load();

    return Container(
      height: 52,
      padding: const EdgeInsets.only(top: 2.0),
      child: AdWidget(ad: dungeonAd),
    );
```

**Comment by bdlukaa** [comment] 2021-04-11 22:15
I can reproduce this issue in my Moto X4. This seems to happen on old devices.

**Comment by bdlukaa** [comment] 2021-04-11 22:16
I had to migrate to [native_admob_flutter](https://pub.dev/packages/native_admob_flutter) because the performance of this package is too bad. The thing causing performance issues is hybrid composition, but `native_admob_flutter` uses Virtual Display in Android.

**Comment by gkovac42** [comment] 2021-04-11 23:25
Thanks for the tip! I've tried [admob_flutter](https://pub.dev/packages/admob_flutter) and this plugin so far, and both have their (somewhat serious) issues on some devices.  How is native_admob_flutter working for you?

**Comment by bdlukaa** [comment] 2021-04-12 00:09
It's working just fine. If you want to test it, run the example app

**Comment by gkovac42** [comment] 2021-04-12 07:08
I'll give it a try, thanks.

**Comment by jangruenwaldt** [comment] 2021-04-28 15:56
Can confirm on Honor 6X takes app from smooth to unusable. Too bad Flutter still has lackluster ad support, really wish there would be an improvement here

**Comment by Row7** [comment] 2021-04-29 22:18
Same problem here, im showing a Listview and frames drop so much when scrolling, making it unusable. 
With last package [firebase_admob](https://pub.dev/documentation/firebase_admob/latest/) (deprecated) didn't have any performance issues.

**Comment by blasten** [comment] 2021-07-21 21:00
We have added a flag to the Flutter master channel that helps improve the performance. 

It's not a perfect fix since the Ad may be a few frames behind the Flutter frame, but depending on the layout you use, it could be useful.  

Please try it out, and let us know if the performance is improved.

To use this flag, set `PlatformViewsService.synchronizeToNativeViewHierarchy(false)`.  For example: 

```dart
import 'package:flutter/services.dart';

void main() {
   PlatformViewsService.synchronizeToNativeViewHierarchy(false);
   runApp(MyApp());
}
```

I'm closing this issue, and moving the conversation to: https://github.com/googleads/googleads-mobile-flutter/issues/269

**Closed by blasten** 2021-07-21 21:00 UTC
Labels: duplicate
