### ISSUE TITLE
Crash simply installing "google_mobile_ads"

### ISSUE THREAD

**Issue by DarrellBrogdon** [googleads/googleads-mobile-flutter#820] opened 2023-04-16 23:58 UTC
## Plugin Version

2.4.0

## Steps to Reproduce

1. Run `flutter create admob_test`
2. Run `cd admob_test`
3. Run `flutter pub add google_mobile_ads`
4. Open `lib/main.dart`
5. Start debugging

**Expected results:** 

The default Flutter template app to run

**Actual results:** 

The app crashes

<details>
  <summary>Logs</summary>

```
Getting a "Comment is too long" error when trying to include the output.
See this Gist instead: https://gist.github.com/DarrellBrogdon/5db3f13fafb8533fe70f45681b3faa5a
See this Gist for the Runner crash report: https://gist.github.com/DarrellBrogdon/908a621d855c3497712c125dc73effa2
```

```
[17:55:17 admob_test]$ flutter analyze
Analyzing admob_test...
No issues found! (ran in 1.1s)
```

```
[17:55:20 admob_test]$ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-arm64, locale en-US)
    • Flutter version 3.7.11 on channel stable at /Users/dbrogdon/Documents/Development/BrogdonCo/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f72efea43c (5 days ago), 2023-04-11 11:57:21 -0700
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/dbrogdon/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.77.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • iPhone 13 mini (mobile) • B974562A-DD36-46A3-AD4C-1BCEF163E035 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)         • macos                                • darwin-arm64   • macOS 13.3.1 22E261 darwin-arm64
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 112.0.5615.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
[17:55:40 admob_test]$
```

</details>

**Comment by huycozy** [comment] 2023-04-17 10:22
This seems to be caused by missing Platform setup on iOS, please see https://developers.google.com/admob/flutter/quick-start#platform_specific_setup as a guideline and retry to see if the crash still occurs.

**Comment by DarrellBrogdon** [comment] 2023-04-21 17:46
Yep, that was it.  Thanks!

**Comment by huycozy** [comment] 2023-04-24 03:10
Closing the issue as solved.

**Closed by huycozy** 2023-04-24 03:10 UTC
Labels: in triage
