### ISSUE TITLE
Gradle 8.0 support. 

### ISSUE THREAD

**Issue by ps6067966** [googleads/googleads-mobile-flutter#904] opened 2023-08-11 06:53 UTC
Thank you. 

I'm getting this error on gradle 8.
![image](https://github.com/googleads/googleads-mobile-flutter/assets/26248740/c719c39d-64db-463a-a98a-907afb81141d)

If any further information required for this issue. Please let me know. I'm happy to help.

**Comment by huycozy** [comment] 2023-08-11 10:38
Closing as a duplicate of https://github.com/googleads/googleads-mobile-flutter/issues/839.

**Closed by huycozy** 2023-08-11 10:38 UTC
Labels: in triage
