### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by erperejildo** [googleads/googleads-mobile-flutter#524] opened 2022-02-25 08:54 UTC
Just cloned the repo and tried the package from the example and I cannot show any ad

**Comment by maheshmnj** [comment] 2022-02-28 13:25
Hi @erperejildo, Thanks for filing the issue. The repo currently have [three examples](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages) could you please  point which example doesn't work?

**Comment by erperejildo** [comment] 2022-03-03 17:37
https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example

**Comment by maheshmnj** [comment] 2022-03-04 11:58
Thanks for the update @erperejildo, I ran the example app on ios and android and it seems to work fine and I see all ads loading fine

<details>
<summary>logs</summary>

```
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Xcode build done.                                           79.3s
 - <Google>[I-ACS025031] AdMob App ID changed. Original, new: (nil), ca-app-pub-3940256099942544~1458002511
 - <Google>[I-ACS023007] Analytics v.80901000 started
 - <Google>[I-ACS023008] To enable debug logging set the following application argument: -APMAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
 - <Google>[I-ACS023171] Resetting App Measurement data
 - <Google>[I-ACS023014] Failed to delete old database file. Error: Error Domain=NSCocoaErrorDomain Code=4 "“google-app-measurement.sql” couldn’t be removed." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/Users/mahesh/Library/Developer/CoreSimulator/Devices/14F40EC6-3B73-469A-A1C0-8CF0B152290F/data/Containers/Data/Application/05B276CB-E22E-461B-B398-77021C595F1E/Library/Application Support/Google/Measurement/google-app-measurement.sql, NSUnderlyingError=0x600002158630 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
 - <Google>[I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
 - <Google>[I-ACS023012] Analytics collection enabled
Connecting to VM Service at ws://127.0.0.1:50309/wNuEEMYvFUo=/ws
<Google> To get test ads on this device, set:
Objective-C
	GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ kGADSimulatorID ];
Swift
	GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [ kGADSimulatorID ]
<Google> User interactions must be disabled on the asset view to enable click handling.
userInteractionEnabled has been set to NO on <UIButton: 0x12c560cc0; frame = (318 259.5; 47 34); opaque = NO; autoresize = RM+BM; userInteractionEnabled = NO; layer = <CALayer: 0x600002e69680>>.
flutter: NativeAd loaded.
flutter: Instance of 'InterstitialAd' loaded
flutter: AdManagerBannerAd loaded.
flutter: BannerAd loaded.
flutter: Instance of 'RewardedAd' loaded.
flutter: Instance of 'RewardedInterstitialAd' loaded.
 - <Google>[I-ACS023130] Configuration not found. Using default configuration
flutter: ad onAdShowedFullScreenContent.
flutter: Instance of 'InterstitialAd' onAdDismissedFullScreenContent.
flutter: Instance of 'InterstitialAd' loaded
flutter: BannerAd loaded.
flutter: ad onAdShowedFullScreenContent.
flutter: Instance of 'RewardedAd' with reward RewardItem(10.0, coins)
flutter: Instance of 'RewardedAd' onAdDismissedFullScreenContent.
flutter: Instance of 'RewardedAd' loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.
flutter: BannerAd loaded.

```
</details>

 Do you see any error in the console?  Also can you try changing your network and see if that makes any difference?

**Comment by 4ntoine** [comment] 2022-03-04 13:43
Find more details in #527

**Comment by erperejildo** [comment] 2022-03-05 10:58
> Thanks for the update @erperejildo, I ran the example app on ios and android and it seems to work fine and I see all ads loading fine
> 
> logs
> Do you see any error in the console? Also can you try changing your network and see if that makes any difference?

not really, I just can't see any ad but no errors are shown

**Comment by 4ntoine** [comment] 2022-03-05 11:30
@erperejildo that's strange, don't you have "ssl error code -101" logcat output?

**Comment by erperejildo** [comment] 2022-03-05 19:28
> @erperejildo that's strange, don't you have "ssl error code -101" logcat output?

I might get some output like that because when ads are initialised, logs go crazy, but not sure. What I mean is that I don't get a flutter error

**Comment by maheshmnj** [comment] 2022-03-08 12:45
@erperejildo Please share the output of `flutter run -v`. Also, are you using any VPN or connected to some network where the ads might be getting blocked? Because the example runs fine for me without any additional changes or configuration in the project.

**Comment by erperejildo** [comment] 2022-03-08 15:20
I moved to a different ads package. I'll close this issue for now.
Thanks

**Comment by maheshmnj** [comment] 2022-03-08 16:52
Will leave this issue open until we arrive at a conclusion

**Comment by maheshmnj** [comment] 2022-03-09 09:40
@4ntoine Could you please attach the logs when the ads don't load?

**Comment by 4ntoine** [comment] 2022-03-09 17:52
@maheshmnj i already did it in #527 . Do you need anything else?

**Comment by maheshmnj** [comment] 2022-03-10 11:40
Lets continue the discussion on #527 since it contains the required logs. Closing this issue as duplicate of the linked issue

**Closed by maheshmnj** 2022-03-10 11:40 UTC
Labels: in triage
