### ISSUE TITLE
Deprecation warnings in version 3.1.0

### ISSUE THREAD

**Issue by under3415** [googleads/googleads-mobile-flutter#940] opened 2023-10-18 04:59 UTC
Five deprecation warnings in `google_mobile_ads` version `3.1.0`
```
\pub.dev\google_mobile_ads-3.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAd.java:75: 
warning: [deprecation] get(String) in BaseBundle has been deprecated
          Object value = responseInfo.getResponseExtras().get(key);
                                                         ^
\pub.dev\google_mobile_ads-3.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAd.java:163: 
warning: [deprecation] get(String) in BaseBundle has been deprecated
          adUnitMapping.put(key, responseInfo.getCredentials().get(key).toString());
                                                              ^
\pub.dev\google_mobile_ads-3.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdLoader.java:53: 
warning: [deprecation] load(Context,String,AdRequest,int,AppOpenAdLoadCallback) in AppOpenAd has been deprecated
    AppOpenAd.load(context, adUnitId, adRequest, orientation, loadCallback);
             ^
\pub.dev\google_mobile_ads-3.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdLoader.java:62: 
warning: [deprecation] load(Context,String,AdManagerAdRequest,int,AppOpenAdLoadCallback) in AppOpenAd has been deprecated
    AppOpenAd.load(context, adUnitId, adRequest, orientation, loadCallback);
             ^
\pub.dev\google_mobile_ads-3.1.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterRequestAgentProvider.java:31: 
warning: [deprecation] getApplicationInfo(String,int) in PackageManager has been deprecated
              .getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
              ^

**Comment by huycozy** [comment] 2023-10-18 10:40
Hi @under3415 
I checked this on [plugin example](https://github.com/googleads/googleads-mobile-flutter/tree/main/packages/google_mobile_ads/example) but didn't see any deprecated warning. Can you also try this and confirm?

**Comment by under3415** [comment] 2023-10-18 19:28
Correct me if I am wrong, but if you are not seeing these warnings, that must be due to outdated build software on your end (Gradle?), my build cannot be making this stuff up.

I am using Gradle version 7.6.2 and below `build.gradle` dependencies:

```
buildscript {
    ext.kotlin_version = '1.8.22' //https://kotlinlang.org/docs/releases.html#release-details
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2' //https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.0' //https://developers.google.com/android/guides/google-services-plugin
    }
}

```

**Comment by huycozy** [comment] 2023-10-19 10:47
When I update gradle files as above, I got below error:

```
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method kotlin() for arguments [build_dawupblbof9bt7j8lphkz7zma$_run_closure2$_closure9@3b8ff79f] on extension 'android' of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.
```

The error indicated to `jvmToolchain` usage. 

Could you share a complete sample project with settings above so that I can try it on my end?

**Comment by under3415** [comment] 2023-10-19 20:31
Attached is example project with configuration modified to work with Gradle 7.6.2. If you build it you will see deprecation warnings.

[example.zip](https://github.com/googleads/googleads-mobile-flutter/files/13047497/example.zip)

**Comment by huycozy** [comment] 2023-10-20 11:53
Thanks for your update. I found the different between your project with plugin example. It is due to you declared this code block in `android/build.gradle`:

```gradle
 gradle.projectsEvaluated {
     tasks.withType(JavaCompile) {
         options.compilerArgs << "-Xlint:deprecation"
     }
 }
```

Without it, I only see this log instead:
```console
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Reproduced the issue by adding code block above to plugin sample code.

**Comment by under3415** [comment] 2023-10-20 21:17
Oh, I got that from the error message! :-)
Great you can replicate it now

**Comment by malandr2** [comment] 2023-12-11 19:04
@under3415 

This has been escalated to the engineering team to take a closer look / work on a resolution. Be on the lookout for a PR

**Comment by malandr2** [comment] 2024-03-20 14:27
Closing as #1023 has been merged in.

**Closed by malandr2** 2024-03-20 14:27 UTC
Labels: p2-medium, e3-weeks, platform-android

**Comment by under3415** [comment] 2024-03-22 22:46
I've installed version `5.0.0`, and now there are even more java deprecation warnings!

One is an existing one from this issue for `getApplicationInfo`. others are new related to deprecated `mediationNetworkExtrasProvider`. 

Do you want me to open a new issue?


```

\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdRequest.java:39: warning: [deprecation] MediationNetworkExtrasProvider in io.flutter.plugins.googlemobileads has been deprecated
  @Nullable private final MediationNetworkExtrasProvider mediationNetworkExtrasProvider;
                          ^
\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdRequest.java:51: warning: [deprecation] MediationNetworkExtrasProvider in io.flutter.plugins.googlemobileads has been deprecated
    @Nullable private MediationNetworkExtrasProvider mediationNetworkExtrasProvider;
                      ^
\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdRequest.java:101: warning: [deprecation] MediationNetworkExtrasProvider in io.flutter.plugins.googlemobileads has been deprecated
        @Nullable MediationNetworkExtrasProvider mediationNetworkExtrasProvider) {
                  ^
\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdRequest.java:149: warning: [deprecation] MediationNetworkExtrasProvider in io.flutter.plugins.googlemobileads has been deprecated
    protected MediationNetworkExtrasProvider getMediationNetworkExtrasProvider() {
              ^
\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdRequest.java:190: warning: [deprecation] MediationNetworkExtrasProvider in io.flutter.plugins.googlemobileads has been deprecated
      @Nullable MediationNetworkExtrasProvider mediationNetworkExtrasProvider,
                ^
\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterAdManagerAdRequest.java:89: warning: [deprecation] MediationNetworkExtrasProvider in io.flutter.plugins.googlemobileads has been deprecated
      @Nullable MediationNetworkExtrasProvider mediationNetworkExtrasProvider,
                ^
\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\AdMessageCodec.java:74: warning: [deprecation] MediationNetworkExtrasProvider in io.flutter.plugins.googlemobileads has been deprecated
  @Nullable private MediationNetworkExtrasProvider mediationNetworkExtrasProvider;
                    ^
\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\AdMessageCodec.java:99: warning: [deprecation] MediationNetworkExtrasProvider in io.flutter.plugins.googlemobileads has been deprecated
      @Nullable MediationNetworkExtrasProvider mediationNetworkExtrasProvider) {
                ^
\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\FlutterRequestAgentProvider.java:31: warning: [deprecation] getApplicationInfo(String,int) in PackageManager has been deprecated
              .getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
              ^
\AppData\Local\Pub\Cache\hosted\pub.dev\google_mobile_ads-5.0.0\android\src\main\java\io\flutter\plugins\googlemobileads\GoogleMobileAdsPlugin.java:71: warning: [deprecation] MediationNetworkExtrasProvider in io.flutter.plugins.googlemobileads has been deprecated
  @Nullable private MediationNetworkExtrasProvider mediationNetworkExtrasProvider;
                    ^
10 warnings
```
